/*
 * Copyright ish group pty ltd. All rights reserved. https?://www.ish.com.au
 * No copying or use of this code is allowed without permission in writing from ish.
 */

import { Country, Location, Language, User } from '@api/model';
import { ConfirmState } from 'ish-ui';
import { DocumentsState } from '../common/components/form/documents/reducers/state';
import { GoogleApiResponse } from '../common/components/google-maps/reducers';
import { AccessState } from '../common/reducers/accessReducer';
import { ProcessState } from '../common/reducers/processReducer';
import { UserPreferencesState } from '../common/reducers/userPreferencesReducer';
import { AutomationState } from '../containers/automation/reducers';
import { AvetmissExportState } from '../containers/avetmiss-export/reducers/state';
import { DashboardState } from '../containers/dashboard/reducers/state';
import { BankingState } from '../containers/entities/bankings/reducers/state';
import { CertificatesState } from '../containers/entities/certificates/reducers';
import { ContactsState } from '../containers/entities/contacts/reducers';
import { CourseClassState } from '../containers/entities/courseClasses/reducers';
import { CourseClassBulkSession } from '../containers/entities/courseClasses/reducers/state';
import { CustomFieldTypesState } from '../containers/entities/customFieldTypes/reducers/state';
import { DiscountsState } from '../containers/entities/discounts/reducers/state';
import { EnrolmentsState } from '../containers/entities/enrolments/reducers/state';
import { InvoicesState } from '../containers/entities/invoices/reducers/state';
import { PaymentInState } from '../containers/entities/paymentsIn/reducers/state';
import { PaymentOutState } from '../containers/entities/paymentsOut/reducers/state';
import { PayrollsState } from '../containers/entities/payrolls/reducers/state';
import { SaleState } from '../containers/entities/sales/reducers/state';
import { SiteState } from '../containers/entities/sites/reducers/state';
import { TaxesState } from '../containers/entities/taxes/reducers';
import { VoucherProductState } from '../containers/entities/voucherProducts/reducers/state';
import { LoginState } from '../containers/login/reducers/state';
import { PreferencesState } from '../containers/preferences/reducers/state';
import { SecurityState } from '../containers/security/reducers/state';
import { TagsState } from '../containers/tags/reducers/state';
import { CheckoutState } from '../model/checkout';
import { ActionsQueueState } from '../model/common/ActionsQueue';
import { Drawer } from '../model/common/drawer/DrawerModel';
import { SwipeableDrawer } from '../model/common/drawer/SwipeableDrawerModel';
import { Fetch } from '../model/common/Fetch';
import { ListState } from '../model/common/ListView';
import { AppMessage } from '../model/common/Message';
import { CommonPlainRecordSearchState } from '../model/common/Plain';
import { SendMessageState } from '../model/common/SendMessage';
import { ShareState } from '../model/common/Share';
import { TimetableState } from '../model/timetable';

// global app state
export interface State {
  automation?: AutomationState;
  confirm?: ConfirmState;
  courseClass?: CourseClassState;
  courseClassesBulkSession?: CourseClassBulkSession;
  preferences?: PreferencesState;
  userPreferences?: UserPreferencesState;
  access?: AccessState;
  timezones?: string[];
  countries?: Country[];
  languages?: Language[];
  fetch?: Fetch;
  enums?: any;
  form?: any;
  drawer?: Drawer;
  swipeableDrawer?: SwipeableDrawer;
  login?: LoginState;
  security?: SecurityState;
  tags?: TagsState;
  export?: AvetmissExportState;
  process?: ProcessState;
  fieldProcessing?: Record<string, boolean>;
  list?: ListState;
  taxes?: TaxesState;
  share?: ShareState;
  lastLocation?: string;
  sites?: SiteState;
  googleApiResponse?: GoogleApiResponse;
  documents?: DocumentsState;
  dashboard?: DashboardState;
  payrolls?: PayrollsState;
  contacts?: ContactsState;
  certificates?: CertificatesState;
  location?: Location;
  usiSoftwareId?: string;
  banking?: BankingState;
  lockedDate?: string;
  discounts?: DiscountsState;
  sales?: SaleState;
  timetable?: TimetableState;
  customFieldTypes?: CustomFieldTypesState;
  voucherProducts?: VoucherProductState;
  invoices?: InvoicesState;
  paymentsIn?: PaymentInState;
  paymentsOut?: PaymentOutState;
  actionsQueue?: ActionsQueueState;
  message?: AppMessage;
  checkout?: CheckoutState;
  enrolments?: EnrolmentsState;
  plainSearchRecords?: CommonPlainRecordSearchState;
  nextLocation?: string;
  systemUser?: User;
  sendMessage?: SendMessageState;
}
