/*
 * Copyright ish group pty ltd. All rights reserved. https://www.ish.com.au
 * No copying or use of this code is allowed without permission in writing from ish.
 */


export type ManualType =
  | "avetmiss-reporting"
  | "accounting"
  | "banking-and-reconciliation"
  | "export-templates"
  | "importing"
  | "tutor-pay-rates"
  | "audit-logging"
  | "navigating-the-application-window"
  | "assessment-tasks-list-view"
  | "batch-payments-in"
  | "certification"
  | "classes"
  | "concessions-and-memberships-1"
  | "creating-and-modifying-contacts"
  | "corporate-pass"
  | "working-with-courses"
  | "data-collection-forms-and-rules"
  | "setting-and-modifying-outcomes"
  | "importing-and-adding-prior-learning"
  | "introduction-to-discounts"
  | "document-management-documents-in-oncourse"
  | "message-templates"
  | "external-integrations"
  | "setting-your-general-preferences#avetmiss"
  | "setting-your-general-preferences#class-defaults"
  | "setting-your-general-preferences#college"
  | "setting-your-general-preferences#concession-types"
  | "setting-your-general-preferences#contact-relation-types"
  | "setting-your-general-preferences#sellable-items-relationships"
  | "setting-your-general-preferences#custom-field-types"
  | "setting-your-general-preferences#financial"
  | "setting-your-general-preferences#funding-contracts"
  | "setting-your-general-preferences#holidays"
  | "setting-your-general-preferences#ldap"
  | "setting-your-general-preferences#maintenance"
  | "setting-your-general-preferences#messaging"
  | "setting-your-general-preferences#payment-types"
  | "setting-your-general-preferences#tax-types"
  | "importing-and-exporting"
  | "about-invoices"
  | "kiosk-mode-for-sites"
  | "leads"
  | "sending-messages"
  | "tutor-pay"
  | "terms-and-definitions"
  | "processing-a-payment-in"
  | "refunding-a-credit-note-via-payment-out"
  | "navigating-around-the-product-window"
  | "using-reports"
  | "print-backgrounds"
  | "cpd-and-oncourse-modules"
  | "viewing-qualifications-and-units-of-competency"
  | "navigating-the-sales-list-window"
  | "navigating-the-automations-view-and-library"
  | "working-with-sites-and-rooms"
  | "working-with-sites-and-rooms#rooms"
  | "tags-in-oncourse"
  | "security-settings"
  | "users"
  | "user-roles"
  | "vouchers"
  | "vet-reporting"
  | "why-use-waiting-lists";
