package ish.oncourse.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.College;
import ish.oncourse.model.Tag;
import ish.oncourse.model.Taggable;

/**
 * Class _TaggableTag was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TaggableTag extends CayenneDataObject {

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String DELETED_PROPERTY = "deleted";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String TAG_PROPERTY = "tag";
    public static final String TAGGABLE_PROPERTY = "taggable";

    public static final String TAG_ID_PK_COLUMN = "tagId";
    public static final String TAGGABLE_ID_PK_COLUMN = "taggableId";

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setDeleted(Boolean deleted) {
        writeProperty("deleted", deleted);
    }
    public Boolean getDeleted() {
        return (Boolean)readProperty("deleted");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void setTag(Tag tag) {
        setToOneTarget("tag", tag, true);
    }

    public Tag getTag() {
        return (Tag)readProperty("tag");
    }


    public void setTaggable(Taggable taggable) {
        setToOneTarget("taggable", taggable, true);
    }

    public Taggable getTaggable() {
        return (Taggable)readProperty("taggable");
    }


}
