package ish.oncourse.model.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.College;
import ish.oncourse.model.DiscountConcessionType;
import ish.oncourse.model.DiscountCourseClass;
import ish.oncourse.model.DiscountEnrolment;
import ish.oncourse.model.Enrolment;
import ish.oncourse.model.InvoiceLineDiscount;

/**
 * Class _Discount was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Discount extends CayenneDataObject {

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CODE_PROPERTY = "code";
    public static final String COMBINATION_TYPE_PROPERTY = "combinationType";
    public static final String CREATED_PROPERTY = "created";
    public static final String DETAIL_PROPERTY = "detail";
    public static final String DETAIL_TEXTILE_PROPERTY = "detailTextile";
    public static final String DISCOUNT_AMOUNT_PROPERTY = "discountAmount";
    public static final String DISCOUNT_RATE_PROPERTY = "discountRate";
    public static final String IS_CODE_REQUIRED_PROPERTY = "isCodeRequired";
    public static final String IS_DELETED_PROPERTY = "isDeleted";
    public static final String MAXIMUM_DISCOUNT_PROPERTY = "maximumDiscount";
    public static final String MINIMUM_DISCOUNT_PROPERTY = "minimumDiscount";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String ROUNDING_MODE_PROPERTY = "roundingMode";
    public static final String STUDENT_AGE_PROPERTY = "studentAge";
    public static final String STUDENT_AGE_OPERATOR_PROPERTY = "studentAgeOperator";
    public static final String STUDENT_ENROLLED_WITHIN_DAYS_PROPERTY = "studentEnrolledWithinDays";
    public static final String STUDENT_POSTCODES_PROPERTY = "studentPostcodes";
    public static final String STUDENTS_QUALIFIER_PROPERTY = "studentsQualifier";
    public static final String TIME_ZONE_PROPERTY = "timeZone";
    public static final String VALID_FROM_PROPERTY = "validFrom";
    public static final String VALID_TO_PROPERTY = "validTo";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String DISCOUNT_CONCESSION_TYPES_PROPERTY = "discountConcessionTypes";
    public static final String DISCOUNT_COURSE_CLASSES_PROPERTY = "discountCourseClasses";
    public static final String DISCOUNT_ENROLMENTS_PROPERTY = "discountEnrolments";
    public static final String ENROLMENTS_PROPERTY = "enrolments";
    public static final String INVOICE_LINE_DISCOUNTS_PROPERTY = "invoiceLineDiscounts";

    public static final String ID_PK_COLUMN = "id";

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCode(String code) {
        writeProperty("code", code);
    }
    public String getCode() {
        return (String)readProperty("code");
    }

    public void setCombinationType(Integer combinationType) {
        writeProperty("combinationType", combinationType);
    }
    public Integer getCombinationType() {
        return (Integer)readProperty("combinationType");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setDetail(String detail) {
        writeProperty("detail", detail);
    }
    public String getDetail() {
        return (String)readProperty("detail");
    }

    public void setDetailTextile(String detailTextile) {
        writeProperty("detailTextile", detailTextile);
    }
    public String getDetailTextile() {
        return (String)readProperty("detailTextile");
    }

    public void setDiscountAmount(BigDecimal discountAmount) {
        writeProperty("discountAmount", discountAmount);
    }
    public BigDecimal getDiscountAmount() {
        return (BigDecimal)readProperty("discountAmount");
    }

    public void setDiscountRate(BigDecimal discountRate) {
        writeProperty("discountRate", discountRate);
    }
    public BigDecimal getDiscountRate() {
        return (BigDecimal)readProperty("discountRate");
    }

    public void setIsCodeRequired(Boolean isCodeRequired) {
        writeProperty("isCodeRequired", isCodeRequired);
    }
    public Boolean getIsCodeRequired() {
        return (Boolean)readProperty("isCodeRequired");
    }

    public void setIsDeleted(Boolean isDeleted) {
        writeProperty("isDeleted", isDeleted);
    }
    public Boolean getIsDeleted() {
        return (Boolean)readProperty("isDeleted");
    }

    public void setMaximumDiscount(BigDecimal maximumDiscount) {
        writeProperty("maximumDiscount", maximumDiscount);
    }
    public BigDecimal getMaximumDiscount() {
        return (BigDecimal)readProperty("maximumDiscount");
    }

    public void setMinimumDiscount(BigDecimal minimumDiscount) {
        writeProperty("minimumDiscount", minimumDiscount);
    }
    public BigDecimal getMinimumDiscount() {
        return (BigDecimal)readProperty("minimumDiscount");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setRoundingMode(Integer roundingMode) {
        writeProperty("roundingMode", roundingMode);
    }
    public Integer getRoundingMode() {
        return (Integer)readProperty("roundingMode");
    }

    public void setStudentAge(Integer studentAge) {
        writeProperty("studentAge", studentAge);
    }
    public Integer getStudentAge() {
        return (Integer)readProperty("studentAge");
    }

    public void setStudentAgeOperator(String studentAgeOperator) {
        writeProperty("studentAgeOperator", studentAgeOperator);
    }
    public String getStudentAgeOperator() {
        return (String)readProperty("studentAgeOperator");
    }

    public void setStudentEnrolledWithinDays(Integer studentEnrolledWithinDays) {
        writeProperty("studentEnrolledWithinDays", studentEnrolledWithinDays);
    }
    public Integer getStudentEnrolledWithinDays() {
        return (Integer)readProperty("studentEnrolledWithinDays");
    }

    public void setStudentPostcodes(String studentPostcodes) {
        writeProperty("studentPostcodes", studentPostcodes);
    }
    public String getStudentPostcodes() {
        return (String)readProperty("studentPostcodes");
    }

    public void setStudentsQualifier(byte[] studentsQualifier) {
        writeProperty("studentsQualifier", studentsQualifier);
    }
    public byte[] getStudentsQualifier() {
        return (byte[])readProperty("studentsQualifier");
    }

    public void setTimeZone(String timeZone) {
        writeProperty("timeZone", timeZone);
    }
    public String getTimeZone() {
        return (String)readProperty("timeZone");
    }

    public void setValidFrom(Date validFrom) {
        writeProperty("validFrom", validFrom);
    }
    public Date getValidFrom() {
        return (Date)readProperty("validFrom");
    }

    public void setValidTo(Date validTo) {
        writeProperty("validTo", validTo);
    }
    public Date getValidTo() {
        return (Date)readProperty("validTo");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void addToDiscountConcessionTypes(DiscountConcessionType obj) {
        addToManyTarget("discountConcessionTypes", obj, true);
    }
    public void removeFromDiscountConcessionTypes(DiscountConcessionType obj) {
        removeToManyTarget("discountConcessionTypes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DiscountConcessionType> getDiscountConcessionTypes() {
        return (List<DiscountConcessionType>)readProperty("discountConcessionTypes");
    }


    public void addToDiscountCourseClasses(DiscountCourseClass obj) {
        addToManyTarget("discountCourseClasses", obj, true);
    }
    public void removeFromDiscountCourseClasses(DiscountCourseClass obj) {
        removeToManyTarget("discountCourseClasses", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DiscountCourseClass> getDiscountCourseClasses() {
        return (List<DiscountCourseClass>)readProperty("discountCourseClasses");
    }


    public void addToDiscountEnrolments(DiscountEnrolment obj) {
        addToManyTarget("discountEnrolments", obj, true);
    }
    public void removeFromDiscountEnrolments(DiscountEnrolment obj) {
        removeToManyTarget("discountEnrolments", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DiscountEnrolment> getDiscountEnrolments() {
        return (List<DiscountEnrolment>)readProperty("discountEnrolments");
    }


    public void addToEnrolments(Enrolment obj) {
        addToManyTarget("enrolments", obj, true);
    }
    public void removeFromEnrolments(Enrolment obj) {
        removeToManyTarget("enrolments", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Enrolment> getEnrolments() {
        return (List<Enrolment>)readProperty("enrolments");
    }


    public void addToInvoiceLineDiscounts(InvoiceLineDiscount obj) {
        addToManyTarget("invoiceLineDiscounts", obj, true);
    }
    public void removeFromInvoiceLineDiscounts(InvoiceLineDiscount obj) {
        removeToManyTarget("invoiceLineDiscounts", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InvoiceLineDiscount> getInvoiceLineDiscounts() {
        return (List<InvoiceLineDiscount>)readProperty("invoiceLineDiscounts");
    }


}
