package ish.oncourse.model.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.College;
import ish.oncourse.model.Room;
import ish.oncourse.model.WaitingListSite;
import ish.oncourse.model.WebBlockTag;

/**
 * Class _Site was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Site extends CayenneDataObject {

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String COUNTRY_ID_PROPERTY = "countryId";
    public static final String CREATED_PROPERTY = "created";
    public static final String DRIVING_DIRECTIONS_PROPERTY = "drivingDirections";
    public static final String DRIVING_DIRECTIONS_TEXTILE_PROPERTY = "drivingDirectionsTextile";
    public static final String IS_DELETED_PROPERTY = "isDeleted";
    public static final String IS_WEB_VISIBLE_PROPERTY = "isWebVisible";
    public static final String LATITUDE_PROPERTY = "latitude";
    public static final String LONGITUDE_PROPERTY = "longitude";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String POSTCODE_PROPERTY = "postcode";
    public static final String PUBLIC_TRANSPORT_DIRECTIONS_PROPERTY = "publicTransportDirections";
    public static final String PUBLIC_TRANSPORT_DIRECTIONS_TEXTILE_PROPERTY = "publicTransportDirectionsTextile";
    public static final String SPECIAL_INSTRUCTIONS_PROPERTY = "specialInstructions";
    public static final String SPECIAL_INSTRUCTIONS_TEXTILE_PROPERTY = "specialInstructionsTextile";
    public static final String STATE_PROPERTY = "state";
    public static final String STREET_PROPERTY = "street";
    public static final String SUBURB_PROPERTY = "suburb";
    public static final String TIME_ZONE_PROPERTY = "timeZone";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String ROOMS_PROPERTY = "rooms";
    public static final String WAITING_LIST_SITES_PROPERTY = "waitingListSites";
    public static final String WEB_BLOCK_TAGS_PROPERTY = "webBlockTags";

    public static final String ID_PK_COLUMN = "id";

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCountryId(Long countryId) {
        writeProperty("countryId", countryId);
    }
    public Long getCountryId() {
        return (Long)readProperty("countryId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setDrivingDirections(String drivingDirections) {
        writeProperty("drivingDirections", drivingDirections);
    }
    public String getDrivingDirections() {
        return (String)readProperty("drivingDirections");
    }

    public void setDrivingDirectionsTextile(String drivingDirectionsTextile) {
        writeProperty("drivingDirectionsTextile", drivingDirectionsTextile);
    }
    public String getDrivingDirectionsTextile() {
        return (String)readProperty("drivingDirectionsTextile");
    }

    public void setIsDeleted(Boolean isDeleted) {
        writeProperty("isDeleted", isDeleted);
    }
    public Boolean getIsDeleted() {
        return (Boolean)readProperty("isDeleted");
    }

    public void setIsWebVisible(Boolean isWebVisible) {
        writeProperty("isWebVisible", isWebVisible);
    }
    public Boolean getIsWebVisible() {
        return (Boolean)readProperty("isWebVisible");
    }

    public void setLatitude(BigDecimal latitude) {
        writeProperty("latitude", latitude);
    }
    public BigDecimal getLatitude() {
        return (BigDecimal)readProperty("latitude");
    }

    public void setLongitude(BigDecimal longitude) {
        writeProperty("longitude", longitude);
    }
    public BigDecimal getLongitude() {
        return (BigDecimal)readProperty("longitude");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setPostcode(String postcode) {
        writeProperty("postcode", postcode);
    }
    public String getPostcode() {
        return (String)readProperty("postcode");
    }

    public void setPublicTransportDirections(String publicTransportDirections) {
        writeProperty("publicTransportDirections", publicTransportDirections);
    }
    public String getPublicTransportDirections() {
        return (String)readProperty("publicTransportDirections");
    }

    public void setPublicTransportDirectionsTextile(String publicTransportDirectionsTextile) {
        writeProperty("publicTransportDirectionsTextile", publicTransportDirectionsTextile);
    }
    public String getPublicTransportDirectionsTextile() {
        return (String)readProperty("publicTransportDirectionsTextile");
    }

    public void setSpecialInstructions(String specialInstructions) {
        writeProperty("specialInstructions", specialInstructions);
    }
    public String getSpecialInstructions() {
        return (String)readProperty("specialInstructions");
    }

    public void setSpecialInstructionsTextile(String specialInstructionsTextile) {
        writeProperty("specialInstructionsTextile", specialInstructionsTextile);
    }
    public String getSpecialInstructionsTextile() {
        return (String)readProperty("specialInstructionsTextile");
    }

    public void setState(String state) {
        writeProperty("state", state);
    }
    public String getState() {
        return (String)readProperty("state");
    }

    public void setStreet(String street) {
        writeProperty("street", street);
    }
    public String getStreet() {
        return (String)readProperty("street");
    }

    public void setSuburb(String suburb) {
        writeProperty("suburb", suburb);
    }
    public String getSuburb() {
        return (String)readProperty("suburb");
    }

    public void setTimeZone(String timeZone) {
        writeProperty("timeZone", timeZone);
    }
    public String getTimeZone() {
        return (String)readProperty("timeZone");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void addToRooms(Room obj) {
        addToManyTarget("rooms", obj, true);
    }
    public void removeFromRooms(Room obj) {
        removeToManyTarget("rooms", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Room> getRooms() {
        return (List<Room>)readProperty("rooms");
    }


    public void addToWaitingListSites(WaitingListSite obj) {
        addToManyTarget("waitingListSites", obj, true);
    }
    public void removeFromWaitingListSites(WaitingListSite obj) {
        removeToManyTarget("waitingListSites", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WaitingListSite> getWaitingListSites() {
        return (List<WaitingListSite>)readProperty("waitingListSites");
    }


    public void addToWebBlockTags(WebBlockTag obj) {
        addToManyTarget("webBlockTags", obj, true);
    }
    public void removeFromWebBlockTags(WebBlockTag obj) {
        removeToManyTarget("webBlockTags", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebBlockTag> getWebBlockTags() {
        return (List<WebBlockTag>)readProperty("webBlockTags");
    }


}
