package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.College;
import ish.oncourse.model.TagGroupRequirement;
import ish.oncourse.model.TaggableTag;

/**
 * Class _Tag was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Tag extends CayenneDataObject {

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String DELETED_PROPERTY = "deleted";
    public static final String DETAIL_PROPERTY = "detail";
    public static final String DETAIL_TEXTILE_PROPERTY = "detailTextile";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String NODE_TYPE_PROPERTY = "nodeType";
    public static final String PARENT_ID_PROPERTY = "parentId";
    public static final String SHORT_NAME_PROPERTY = "shortName";
    public static final String TAG_GROUP_PROPERTY = "tagGroup";
    public static final String WEB_VISIBLE_PROPERTY = "webVisible";
    public static final String WEIGHTING_PROPERTY = "weighting";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String TAGGABLETAGS_PROPERTY = "taggabletags";
    public static final String TAGGROUPREQUIREMENTS_PROPERTY = "taggrouprequirements";

    public static final String ID_PK_COLUMN = "id";

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setDeleted(Boolean deleted) {
        writeProperty("deleted", deleted);
    }
    public Boolean getDeleted() {
        return (Boolean)readProperty("deleted");
    }

    public void setDetail(String detail) {
        writeProperty("detail", detail);
    }
    public String getDetail() {
        return (String)readProperty("detail");
    }

    public void setDetailTextile(String detailTextile) {
        writeProperty("detailTextile", detailTextile);
    }
    public String getDetailTextile() {
        return (String)readProperty("detailTextile");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setNodeType(Integer nodeType) {
        writeProperty("nodeType", nodeType);
    }
    public Integer getNodeType() {
        return (Integer)readProperty("nodeType");
    }

    public void setParentId(Long parentId) {
        writeProperty("parentId", parentId);
    }
    public Long getParentId() {
        return (Long)readProperty("parentId");
    }

    public void setShortName(String shortName) {
        writeProperty("shortName", shortName);
    }
    public String getShortName() {
        return (String)readProperty("shortName");
    }

    public void setTagGroup(Boolean tagGroup) {
        writeProperty("tagGroup", tagGroup);
    }
    public Boolean getTagGroup() {
        return (Boolean)readProperty("tagGroup");
    }

    public void setWebVisible(Boolean webVisible) {
        writeProperty("webVisible", webVisible);
    }
    public Boolean getWebVisible() {
        return (Boolean)readProperty("webVisible");
    }

    public void setWeighting(Integer weighting) {
        writeProperty("weighting", weighting);
    }
    public Integer getWeighting() {
        return (Integer)readProperty("weighting");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void addToTaggabletags(TaggableTag obj) {
        addToManyTarget("taggabletags", obj, true);
    }
    public void removeFromTaggabletags(TaggableTag obj) {
        removeToManyTarget("taggabletags", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TaggableTag> getTaggabletags() {
        return (List<TaggableTag>)readProperty("taggabletags");
    }


    public void addToTaggrouprequirements(TagGroupRequirement obj) {
        addToManyTarget("taggrouprequirements", obj, true);
    }
    public void removeFromTaggrouprequirements(TagGroupRequirement obj) {
        removeToManyTarget("taggrouprequirements", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TagGroupRequirement> getTaggrouprequirements() {
        return (List<TagGroupRequirement>)readProperty("taggrouprequirements");
    }


}
