package ish.oncourse.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.Tag;

/**
 * Class _WebTagged was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WebTagged extends CayenneDataObject {

    public static final String CREATED_PROPERTY = "created";
    public static final String ENTITY_IDENTIFIER_PROPERTY = "entityIdentifier";
    public static final String ENTITY_RECORD_ID_PROPERTY = "entityRecordID";
    public static final String TAG_PROPERTY = "tag";

    public static final String ID_PK_COLUMN = "id";

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setEntityIdentifier(String entityIdentifier) {
        writeProperty("entityIdentifier", entityIdentifier);
    }
    public String getEntityIdentifier() {
        return (String)readProperty("entityIdentifier");
    }

    public void setEntityRecordID(Long entityRecordID) {
        writeProperty("entityRecordID", entityRecordID);
    }
    public Long getEntityRecordID() {
        return (Long)readProperty("entityRecordID");
    }

    public void setTag(Tag tag) {
        setToOneTarget("tag", tag, true);
    }

    public Tag getTag() {
        return (Tag)readProperty("tag");
    }


}
