package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.College;
import ish.oncourse.model.WebBlock;
import ish.oncourse.model.WebHostName;
import ish.oncourse.model.WebNode;
import ish.oncourse.model.WebNodeType;
import ish.oncourse.model.WebSite;

/**
 * Class _WebSite was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WebSite extends CayenneDataObject {

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CODE_PROPERTY = "code";
    public static final String CREATED_PROPERTY = "created";
    public static final String DEFAULT_URL_PATH_PROPERTY = "defaultUrlPath";
    public static final String DELETED_PROPERTY = "deleted";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String SITE_KEY_PROPERTY = "siteKey";
    public static final String SSL_HOST_NAME_PROPERTY = "sslHostName";
    public static final String BLOCKS_PROPERTY = "blocks";
    public static final String CHILD_SITES_PROPERTY = "childSites";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String HOME_PAGE_PROPERTY = "homePage";
    public static final String NODES_PROPERTY = "nodes";
    public static final String PARENT_SITE_PROPERTY = "parentSite";
    public static final String TEMPLATES_PROPERTY = "templates";
    public static final String WEB_HOST_NAMES_PROPERTY = "webHostNames";

    public static final String ID_PK_COLUMN = "id";

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCode(String code) {
        writeProperty("code", code);
    }
    public String getCode() {
        return (String)readProperty("code");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setDefaultUrlPath(String defaultUrlPath) {
        writeProperty("defaultUrlPath", defaultUrlPath);
    }
    public String getDefaultUrlPath() {
        return (String)readProperty("defaultUrlPath");
    }

    public void setDeleted(Boolean deleted) {
        writeProperty("deleted", deleted);
    }
    public Boolean getDeleted() {
        return (Boolean)readProperty("deleted");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setSiteKey(String siteKey) {
        writeProperty("siteKey", siteKey);
    }
    public String getSiteKey() {
        return (String)readProperty("siteKey");
    }

    public void setSslHostName(String sslHostName) {
        writeProperty("sslHostName", sslHostName);
    }
    public String getSslHostName() {
        return (String)readProperty("sslHostName");
    }

    public void addToBlocks(WebBlock obj) {
        addToManyTarget("blocks", obj, true);
    }
    public void removeFromBlocks(WebBlock obj) {
        removeToManyTarget("blocks", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebBlock> getBlocks() {
        return (List<WebBlock>)readProperty("blocks");
    }


    public void addToChildSites(WebSite obj) {
        addToManyTarget("childSites", obj, true);
    }
    public void removeFromChildSites(WebSite obj) {
        removeToManyTarget("childSites", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebSite> getChildSites() {
        return (List<WebSite>)readProperty("childSites");
    }


    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void setHomePage(WebNode homePage) {
        setToOneTarget("homePage", homePage, true);
    }

    public WebNode getHomePage() {
        return (WebNode)readProperty("homePage");
    }


    public void addToNodes(WebNode obj) {
        addToManyTarget("nodes", obj, true);
    }
    public void removeFromNodes(WebNode obj) {
        removeToManyTarget("nodes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebNode> getNodes() {
        return (List<WebNode>)readProperty("nodes");
    }


    public void setParentSite(WebSite parentSite) {
        setToOneTarget("parentSite", parentSite, true);
    }

    public WebSite getParentSite() {
        return (WebSite)readProperty("parentSite");
    }


    public void setTemplates(WebNodeType templates) {
        setToOneTarget("templates", templates, true);
    }

    public WebNodeType getTemplates() {
        return (WebNodeType)readProperty("templates");
    }


    public void addToWebHostNames(WebHostName obj) {
        addToManyTarget("webHostNames", obj, true);
    }
    public void removeFromWebHostNames(WebHostName obj) {
        removeToManyTarget("webHostNames", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebHostName> getWebHostNames() {
        return (List<WebHostName>)readProperty("webHostNames");
    }


}
