package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.WebNode;
import ish.oncourse.model.WebNodeContent;
import ish.oncourse.model.WebNodeTag;
import ish.oncourse.model.WebNodeType;
import ish.oncourse.model.WebSite;
import ish.oncourse.model.WebUrlAlias;
import ish.oncourse.model.WillowUser;

/**
 * Class _WebNode was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WebNode extends CayenneDataObject {

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String IS_DELETED_PROPERTY = "isDeleted";
    public static final String IS_PUBLISHED_PROPERTY = "isPublished";
    public static final String IS_RSS_FEED_PROPERTY = "isRssFeed";
    public static final String IS_WEB_NAVIGABLE_PROPERTY = "isWebNavigable";
    public static final String IS_WEB_VISIBLE_PROPERTY = "isWebVisible";
    public static final String MENU_ALIAS_ID_PROPERTY = "menuAliasId";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String NODE_NUMBER_PROPERTY = "nodeNumber";
    public static final String SHORT_NAME_PROPERTY = "shortName";
    public static final String WEIGHTING_PROPERTY = "weighting";
    public static final String PARENT_NODE_PROPERTY = "parentNode";
    public static final String SAVED_BY_USER_PROPERTY = "savedByUser";
    public static final String WEB_NODE_CONTENTS_PROPERTY = "webNodeContents";
    public static final String WEB_NODE_TAGS_PROPERTY = "webNodeTags";
    public static final String WEB_NODE_TYPE_PROPERTY = "webNodeType";
    public static final String WEB_NODES_PROPERTY = "webNodes";
    public static final String WEB_SITE_PROPERTY = "webSite";
    public static final String WEB_SITES_PROPERTY = "webSites";
    public static final String WEB_URL_ALIASES_PROPERTY = "webUrlAliases";

    public static final String ID_PK_COLUMN = "id";

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setIsDeleted(Boolean isDeleted) {
        writeProperty("isDeleted", isDeleted);
    }
    public Boolean getIsDeleted() {
        return (Boolean)readProperty("isDeleted");
    }

    public void setIsPublished(Boolean isPublished) {
        writeProperty("isPublished", isPublished);
    }
    public Boolean getIsPublished() {
        return (Boolean)readProperty("isPublished");
    }

    public void setIsRssFeed(Boolean isRssFeed) {
        writeProperty("isRssFeed", isRssFeed);
    }
    public Boolean getIsRssFeed() {
        return (Boolean)readProperty("isRssFeed");
    }

    public void setIsWebNavigable(Boolean isWebNavigable) {
        writeProperty("isWebNavigable", isWebNavigable);
    }
    public Boolean getIsWebNavigable() {
        return (Boolean)readProperty("isWebNavigable");
    }

    public void setIsWebVisible(Boolean isWebVisible) {
        writeProperty("isWebVisible", isWebVisible);
    }
    public Boolean getIsWebVisible() {
        return (Boolean)readProperty("isWebVisible");
    }

    public void setMenuAliasId(Long menuAliasId) {
        writeProperty("menuAliasId", menuAliasId);
    }
    public Long getMenuAliasId() {
        return (Long)readProperty("menuAliasId");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setNodeNumber(Integer nodeNumber) {
        writeProperty("nodeNumber", nodeNumber);
    }
    public Integer getNodeNumber() {
        return (Integer)readProperty("nodeNumber");
    }

    public void setShortName(String shortName) {
        writeProperty("shortName", shortName);
    }
    public String getShortName() {
        return (String)readProperty("shortName");
    }

    public void setWeighting(Integer weighting) {
        writeProperty("weighting", weighting);
    }
    public Integer getWeighting() {
        return (Integer)readProperty("weighting");
    }

    public void setParentNode(WebNode parentNode) {
        setToOneTarget("parentNode", parentNode, true);
    }

    public WebNode getParentNode() {
        return (WebNode)readProperty("parentNode");
    }


    public void setSavedByUser(WillowUser savedByUser) {
        setToOneTarget("savedByUser", savedByUser, true);
    }

    public WillowUser getSavedByUser() {
        return (WillowUser)readProperty("savedByUser");
    }


    public void addToWebNodeContents(WebNodeContent obj) {
        addToManyTarget("webNodeContents", obj, true);
    }
    public void removeFromWebNodeContents(WebNodeContent obj) {
        removeToManyTarget("webNodeContents", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebNodeContent> getWebNodeContents() {
        return (List<WebNodeContent>)readProperty("webNodeContents");
    }


    public void addToWebNodeTags(WebNodeTag obj) {
        addToManyTarget("webNodeTags", obj, true);
    }
    public void removeFromWebNodeTags(WebNodeTag obj) {
        removeToManyTarget("webNodeTags", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebNodeTag> getWebNodeTags() {
        return (List<WebNodeTag>)readProperty("webNodeTags");
    }


    public void setWebNodeType(WebNodeType webNodeType) {
        setToOneTarget("webNodeType", webNodeType, true);
    }

    public WebNodeType getWebNodeType() {
        return (WebNodeType)readProperty("webNodeType");
    }


    public void addToWebNodes(WebNode obj) {
        addToManyTarget("webNodes", obj, true);
    }
    public void removeFromWebNodes(WebNode obj) {
        removeToManyTarget("webNodes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebNode> getWebNodes() {
        return (List<WebNode>)readProperty("webNodes");
    }


    public void setWebSite(WebSite webSite) {
        setToOneTarget("webSite", webSite, true);
    }

    public WebSite getWebSite() {
        return (WebSite)readProperty("webSite");
    }


    public void addToWebSites(WebSite obj) {
        addToManyTarget("webSites", obj, true);
    }
    public void removeFromWebSites(WebSite obj) {
        removeToManyTarget("webSites", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebSite> getWebSites() {
        return (List<WebSite>)readProperty("webSites");
    }


    public void addToWebUrlAliases(WebUrlAlias obj) {
        addToManyTarget("webUrlAliases", obj, true);
    }
    public void removeFromWebUrlAliases(WebUrlAlias obj) {
        removeToManyTarget("webUrlAliases", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebUrlAlias> getWebUrlAliases() {
        return (List<WebUrlAlias>)readProperty("webUrlAliases");
    }


}
