jetty:
  context: /
  connectors:
    - port: 8182
      type: https2

jdbc:
  angel-test:
    url: jdbc:mysql://localhost/angelTest_trunk?autocommit=true&useUnicode=true&characterEncoding=utf8
    username: root
    password:
    driverClassName: org.mariadb.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    validationInterval: 30000
    timeBetweenEvictionRunsMillis: 3000
    maxActive: 100
    maxIdle: 5
    minIdle: 2
    removeAbandonedTimeout: 300
    removeAbandoned: true
    logAbandoned: true
    jmxEnabled: true

  angel-test-creation:
    url: jdbc:mysql://localhost:3306?autocommit=true&useUnicode=true&characterEncoding=utf8
    username: root
    password:
    driverClassName: org.mariadb.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    validationInterval: 30000
    timeBetweenEvictionRunsMillis: 3000
    maxActive: 100
    maxIdle: 5
    minIdle: 2
    removeAbandonedTimeout: 300
    removeAbandoned: true
    logAbandoned: true
    jmxEnabled: true

  angel-test-local:
    url: jdbc:mysql://127.0.0.1/oncourse_test?autocommit=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password:
    driverClassName: org.mariadb.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    validationInterval: 30000
    timeBetweenEvictionRunsMillis: 3000
    maxActive: 100
    maxIdle: 5
    minIdle: 2
    removeAbandonedTimeout: 300
    removeAbandoned: true
    logAbandoned: true
    jmxEnabled: true

cayenne:
  datasource: angel-test
  configs:
    - cayenne/cayenne-Angel.xml
