jetty:
  context: /
  connectors:
    - port: 8182
      type: https2
  staticResourceBase: classpath:static
  compactPath: true

jdbc:
  angel:
    type: uri
    driverClassName: org.mariadb.jdbc.Driver
    connectionTestQuery: SELECT 1
    maximumPoolSize: 150
    minimumIdle: 2
    idleTimeout: 1000000
    connectionTimeout: 15000
    registerMbeans: true

cayenne:
  datasource: angel
  configs:
    - cayenne/cayenne-Angel.xml
cxf:
  welcomeText: 'Angel REST API'
  urlPattern: '/a/*'

permissions:
  apiPackage: ish.oncourse.server.api.v1.service

bugsnag:
  api: 62d23ac49ee5f1667a9b4cef633b5852
