get:
  operationId: getConfigs
  description: get configs of an existing report as String
  tags:
    - PdfTemplate
  parameters:
    - name: id
      in: path
      type: integer
      format: int64
      required: true
      description: Unique identifier of script record to fetch
  responses:
    '200':
      description: Success response.
      schema:
        type: string
    '400':
      description: Bad request error.
    default:
      description: Unexpected error
  x-permission:
    mask: view
    keyCode: REPORT
    errorMessage: Sorry, you have no permissions to view report. Please contact your administrator


put:
  operationId: updateConfigs
  description: Update an existing report
  tags:
    - PdfTemplate
  parameters:
    - name: id
      in: path
      type: integer
      format: int64
      required: true
      description: Unique identifier of script record to fetch
    - name: scriptConfigs
      in: body
      schema:
        type: string
      required: true
      description: lines of yaml file to upgrade script configs
  responses:
    '204':
      description: Success response.
    '400':
      description: Bad request error.
    default:
      description: Unexpected error
  x-permission:
    mask: edit
    keyCode: REPORT
    errorMessage: Sorry, you have no permissions to update report. Please contact your administrator