
package ish.oncourse.webservices.soap.v21;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-04-09T01:32:42.264+10:00
 * Generated source version: 3.2.6
 */

@WebFault(name = "errorCode", targetNamespace = "http://repl.v21.soap.webservices.oncourse.ish/")
public class AuthFailure extends Exception {

    private ish.oncourse.webservices.v21.stubs.replication.ErrorCode errorCode;

    public AuthFailure() {
        super();
    }

    public AuthFailure(String message) {
        super(message);
    }

    public AuthFailure(String message, Throwable cause) {
        super(message, cause);
    }

    public AuthFailure(String message, ish.oncourse.webservices.v21.stubs.replication.ErrorCode errorCode) {
        super(message);
        this.errorCode = errorCode;
    }

    public AuthFailure(String message, ish.oncourse.webservices.v21.stubs.replication.ErrorCode errorCode, Throwable cause) {
        super(message, cause);
        this.errorCode = errorCode;
    }

    public ish.oncourse.webservices.v21.stubs.replication.ErrorCode getFaultInfo() {
        return this.errorCode;
    }
}
