export default {
    ADD_CLASS_TO_CART_SUCCESS: 'ADD_CLASS_TO_CART_SUCCESS',
    REMOVE_CLASS_FROM_CART_SUCCESS: 'REMOVE_CLASS_FROM_CART_SUCCESS',

    ADD_PRODUCT_TO_CART_SUCCESS: 'ADD_PRODUCT_TO_CART_SUCCESS',
    REMOVE_PRODUCT_FROM_CART_SUCCESS: 'REMOVE_PRODUCT_FROM_CART_SUCCESS',

    HIDE_POPUP: 'HIDE_POPUP',
    UPDATE_POPUP: 'UPDATE_POPUP'
};