export default {
    ADD_CLASS_TO_CART: 'ADD_CLASS_TO_CART',
    ADD_CLASS_TO_CART_SUCCESS: 'ADD_CLASS_TO_CART_SUCCESS',
    ADD_CLASS_TO_CART_FAILURE: 'ADD_CLASS_TO_CART_FAILURE',

    REMOVE_CLASS_FROM_CART: 'REMOVE_CLASS_FROM_CART',
    REMOVE_CLASS_FROM_CART_SUCCESS: 'REMOVE_CLASS_FROM_CART_SUCCESS',
    REMOVE_CLASS_FROM_CART_FAILURE: 'REMOVE_CLASS_FROM_CART_FAILURE',

    HIDE_POPUP: 'HIDE_POPUP',
    UPDATE_POPUP: 'UPDATE_POPUP'
};