swagger: '2.0'
info:
  title: onCourse Portal API
  description: An API for interacting with the portal app
  contact:
    name: ish group pty ltd
    url: http://ish.com.au
    email: support@ish.com.au
  license:
    name: Proprietary
  version: v1


schemes:
  - https
produces:
  - application/json

host: provisioning.ish.com.au
basePath: /a/v1

paths:
  /login:
    $ref: './path/login/api.yaml'
  /sso:
    $ref: './path/sso/api.yaml'
    
definitions:
  
  LoginStage:
    type: string
    description: List of email verification stages
    enum:
      - create
      - password
      - authorize
    