[[${classDoc.name()}]]
== ${helper.methodName(classDoc.name())}

${helper.methodDoc(classDoc.rawCommentText)}

<% classDoc.enumConstants.each { e -> %>\
=== ${e.name()}

${helper.methodDoc(e.rawCommentText)}
<% } %>\

<% visibleConstructors.each { constructor -> %>\
=== Constructor ${constructor.name()}(${constructor.parameters.collect { it.name() }.join(', ')})

${helper.methodDoc(constructor.rawCommentText)}

[.params]
--
<% constructor.parameters.each { param -> %>\
* [.param]#${param.name()}# [.type]#${helper.linkable( param.type )}# ${helper.paramDoc(param.name(), constructor.rawCommentText)}
<% } %>\
--
<% } %>

<% visibleMethods.sort{ it.name() }.each { method -> %>
=== ${method.name().replaceFirst(/^get([A-Z])/) {it[1].toLowerCase()}}<% if (method.parameters.size>0) { %>(${method.parameters.collect { it.name() }.join(', ') })<% } %>

${helper.methodDoc(method.rawCommentText)}

[.params]
--
<% method.parameters().each { param -> %>\
* [.param]#${param.name()}# [.type]#${ param.type ? helper.linkable( param.type ) : param.typeName() }# ${helper.paramDoc(param.name(), method.rawCommentText)}
<% } %>\
<% if ( method.returnType && !(method.returnType.typeName() in ["void", "def", ""]) ) { %>\
* Returns ${helper.getNullability(method)} [.type]#${helper.linkable( method.returnType )}# ${helper.returnDoc(method.rawCommentText)}
<% } %>\
--
<% } %>\
