= onCourse Domain Specific Language (DSL)
:doctype: book
Aristedes Maniatis

onCourse implements a DSL built on top of Apache Groovy. This provides you a powerful language for creating scripts, exports and reports inside onCourse.

This document only describes the DSL extensions to Groovy. You have the entire language at your disposal and you should take the time to read the link:http://groovy-lang.org/documentation.html[excellent documentation available]. Note that you cannot use closures inside JasperReport templates. For exports only, you can also make use of the link:http://super-csv.github.io/super-csv/[SuperCSV project] to simplify the generation of CSV export data.

<%
// this funny hack is necessary since we aren't parsing the entire src tree, so we can't get the
// superclass of the superclass and check it is a CayenneDataObject
def isCayenneEntity = { it.name().startsWith("_") }
def (enums, nonEnums) = classes.split( { it.isEnum() } )
def (entities, other) = nonEnums.split { it.parentClasses.find(isCayenneEntity) }
%>

= Script blocks and other
<% for (classDoc in other.sort{it.name()} ) { %>
include::${classDoc.fullPathName}.adoc[]
<% } %>

= Data Entities

These are objects which represent the data stored in onCourse. You will typically search for them using the onCourse query language. These objects will be in the Cayenne Context named 'context' by default, so you can make changes and store them back into onCourse using context.commitChanges(). The database tables often don't match the description of the entities here since we use inheritance and different naming to better describe the data schema in code.

<% for (classDoc in entities.sort{it.name()} ) { %>
include::${classDoc.fullPathName}.adoc[]
<% } %>

= Enumerations

These are Java classes which represent a list of options, where that list is hardcoded into the application and cannot be extended by the user. In normal use you would not care about the database value and instead use the enumeration by name. For example:

```
if (myAccount.type == AccountType.ASSET) {
   # do something
}
```

<% for (classDoc in enums.sort{it.name()} ) { %>
include::${classDoc.fullPathName}.adoc[]
<% } %>
