swagger: '2.0'
info:
  title: onCourse Billing API
  description: An API for interacting with the billing system
  contact:
    name: ish group pty ltd
    url: http://ish.com.au
    email: support@ish.com.au
  license:
    name: Proprietary
  version: v1


schemes:
  - https
produces:
  - application/json

host: provisioning.ish.com.au
basePath: /a/v1


paths:
  /college:
    get:
      operationId: verifyCollegeName
      description: |
        Check if college name is available
      tags:
        - Billing
      x-filter:
        - ish.oncourse.api.access.GuestFilter
      parameters:
        - name: collegeKey
          in: path
          description: College unique key
          required: true
          type: string
        - name: xGRecaptcha
          in: header
          description: reCaptch token
          required: false
          type: string
      responses:
        '200':
          description: verification responce
          schema:
            type: boolean

    post:
      operationId: createCollege
      description: |
        Create college
      tags:
        - Billing
      x-filter:
        - ish.oncourse.api.access.GuestFilter
      consumes:
        - application/json
      parameters:
        - name: college
          in: body
          description: College attributes
          required: true
          schema:
            $ref: '#/definitions/CollegeDTO'
      responses:
        '204':
          description: Success responce
        '400':
          description: Bad request
          schema:
            $ref: '#/definitions/ErrorDTO'

  /collegeKey:
    get:
      operationId: getCollegeKey
      description: |
        Get existing college key
      tags:
        - Billing
      x-filter:
        - ish.oncourse.api.access.AuthFilter
      responses:
        '200':
          description: college key responce
          schema:
            type: string

  /college/sites:
    get:
      operationId: getCollegeSites
      description: |
        Get existing college sites
      tags:
        - Billing
      x-filter:
        - ish.oncourse.api.access.AuthFilter
      responses:
        '200':
          description: college key responce
          schema:
            type: array
            items:
              $ref: '#/definitions/SiteDTO'
    post:
      operationId: updateCollegeSites
      description: |
        Update existing college sites
      tags:
        - Billing
      x-filter:
        - ish.oncourse.api.access.AuthFilter
      parameters:
        - name: sites
          in: body
          description: Updated sites
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/SiteDTO'
      responses:
        '200':
          description: college sites responce


definitions:
  SiteDTO:
    type: object
    properties:
      id:
        type: integer
        format: int32
      key:
        type: string
      name:
        type: string
      domains:
        type: array
        items:
          type: string

  CollegeDTO:
    type: object
    properties:
      collegeKey:
        type: string
        description: college sub domain
        example: sttrinians
      organisationName:
        type: string
        description: College name
        example: Training ish onCourse
      abn:
        type: string
        description: College abn
        example: 123 456 789
      tradingName:
        type: string
        description: College traiding name
        example: Ish Learning Pty Ltd
      address:
        type: string
        description: College address
        example: Level 1, 30 Wilson St
      suburb:
        type: string
        description: College suburb
        example: Newtown
      state:
        type: string
        description: College state
        example: NSW
      postcode:
        type: string
        description: College postcode
        example: 2042
      country:
        type: string
        description: College country
        example: Australia
      timeZone:
        type: string
        description: College time zone
        example: Australia/sydney
      userEmail:
        type: string
        format: email
        description: user email
        example: john.smith@gmail.com
      userFirstName:
        type: string
        description: user first name
        example: John
      userLastName:
        type: string
        description: user last name
        example: john.smith@gmail.com
      userPhone:
        type: string
        description: user phone number
        example: 0412345678
      webSiteTemplate:
        description: web site template
        $ref: '#/definitions/SiteTemplate'

  SiteTemplate:
    type: string
    enum:
      - a
      - b
      - c
      - d
      - e
      - f
  ErrorDTO:
    type: object
    properties:
      message:
        type: string
        description: Error description
        example: College name is required
