swagger: '2.0'
info:
  title: onCourse Billing API
  description: An API for interacting with the billing system
  contact:
    name: ish group pty ltd
    url: http://ish.com.au
    email: support@ish.com.au
  license:
    name: Proprietary
  version: v1


schemes:
  - https
produces:
  - application/json

host: provisioning.ish.com.au
basePath: /a/v1


paths:
  /college:
    post:
      operationId: createCollege
      description: |
        Create college
      tags:
        - Billing
      consumes:
        - application/json
      parameters:
        - name: college
          in: body
          description: College attributes 
          required: true
          schema:
            $ref: '#/definitions/CollegeDTO'
      responses:
        '204':
          description: Success responce
        '400':
          description: Login unsuccessful. Invalid login name or password.
          schema:
            $ref: '#/definitions/ErrorDTO'
            
definitions:

  CollegeDTO:
    type: object
    properties:
      email:
        type: string
        format: email
        description: user email
        example: john.smith@gmail.com
      collegeKey:
        type: string
        description: college sub domain
        example: sttrinians
        
  ErrorDTO:
    type: object
    properties:
      message:
        type: string
        description: Error description
        example: College name is required