swagger: '2.0'
info:
  title: onCourse Billing API
  description: An API for interacting with the billing system
  contact:
    name: ish group pty ltd
    url: http://ish.com.au
    email: support@ish.com.au
  license:
    name: Proprietary
  version: v1


schemes:
  - https
produces:
  - application/json

host: provisioning.ish.com.au
basePath: /a/v1


paths:
  /properties:
    $ref: './path/properties/api.yaml'
  /college:
    $ref: './path/college/api.yaml'
  /college/key:
    $ref: './path/college/key/api.yaml'
  /college/site:
    $ref: './path/college/site/api.yaml'