/*
 * Copyright ish group pty ltd 2020.
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License version 3 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 */
package ish.oncourse.common;

import java.util.Arrays;
import java.util.List;

public interface NodeInterface {

	String ILLEGAL_NODE_SHORTNAME_PATTERN = "/[0-9].*";

	List<String> NODE_NAMES_FORBIDDEN_CASE_INSENSITIVE = Arrays.asList("attachment",
            "attachmentData",
            "attachmentInfo",
            "attachmentInfos",
            "attachmentInfoRelation",
            "attachmentInfoRelations",
            "course",
            "courses",
            "class",
            "classes",
            "site",
            "sites",
            "room",
            "rooms",
            "enrolnow",
            "enrol",
            "admin",
            "ajax",
            "binary",
            "cgi-bin",
            "code",
            "concession",
            "detail",
            "discount",
            "enrol",
            "enrolnow",
            "head",
            "list",
            "login",
            "module",
            "modules",
            "oncourse",
            "promo",
            "promotion",
            "qualification",
            "qualifications",
            "refresh",
            "s",
            "session",
            "stats",
            "tag",
            "tags",
            "timeline",
            "timetable",
            "trainingpackage",
            "trainingpackages",
            "waitinglist",
            "layout-header",
            "layout-footer",
            "layout-leftnav",
            "layout-rightnav",
            "layout-content",
            "binaryData",
            "binaryInfo",
            "binaryInfos",
            "binaryInfoRelation",
            "binaryInfoRelations",
            "college",
            "colleges",
            "collegeDomain",
            "collegeDomains",
            "contact",
            "contacts",
            "country",
            "countries",
            "course",
            "courses",
            "courseClass",
            "courseClasses",
            "courseModule",
            "courseModules",
            "directAction",
            "directActions",
            "discount",
            "discounts",
            "discountCourseClass",
            "discountCourseClasses",
            "discountEnrolment",
            "discountEnrolments",
            "enrolment",
            "enrolments",
            "language",
            "languages",
            "log",
            "logs",
            "message",
            "messages",
            "messagePerson",
            "messagePersons",
            "messageTemplate",
            "messageTemplates",
            "module",
            "modules",
            "payment",
            "payments",
            "paymentTransaction",
            "paymentTransactions",
            "preference",
            "preferences",
            "qualification",
            "qualifications",
            "queuedRecord",
            "queuedRecords",
            "room",
            "rooms",
            "session",
            "sessions",
            "sessionTutor",
            "sessionTutors",
            "site",
            "sites",
            "student",
            "students",
            "tag",
            "tags",
            "tagGroupRequirement",
            "tagGroupRequirements",
            "taggable",
            "taggables",
            "taggableTag",
            "taggableTags",
            "trainingPackage",
            "trainingPackages",
            "tutor",
            "tutors",
            "tutorRole",
            "tutorRoles",
            "waitingList",
            "waitingLists",
            "waitingListSite",
            "waitingListSites",
            "willowUser",
            "willowUsers");
}
