
package au.gov.usi._2015.ws.servicepolicy;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.16
 * 2016-11-08T21:50:02.108+11:00
 * Generated source version: 2.6.16
 */

@WebFault(name = "ArrayOfErrorInfo", targetNamespace = "http://usi.gov.au/2015/ws")
public class IUSIServiceBulkUploadErrorInfoFaultFaultMessage extends Exception {
    
    private au.gov.usi._2015.ws.ArrayOfErrorInfo arrayOfErrorInfo;

    public IUSIServiceBulkUploadErrorInfoFaultFaultMessage() {
        super();
    }
    
    public IUSIServiceBulkUploadErrorInfoFaultFaultMessage(String message) {
        super(message);
    }
    
    public IUSIServiceBulkUploadErrorInfoFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IUSIServiceBulkUploadErrorInfoFaultFaultMessage(String message, au.gov.usi._2015.ws.ArrayOfErrorInfo arrayOfErrorInfo) {
        super(message);
        this.arrayOfErrorInfo = arrayOfErrorInfo;
    }

    public IUSIServiceBulkUploadErrorInfoFaultFaultMessage(String message, au.gov.usi._2015.ws.ArrayOfErrorInfo arrayOfErrorInfo, Throwable cause) {
        super(message, cause);
        this.arrayOfErrorInfo = arrayOfErrorInfo;
    }

    public au.gov.usi._2015.ws.ArrayOfErrorInfo getFaultInfo() {
        return this.arrayOfErrorInfo;
    }
}
