package ish.oncourse.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import ish.common.types.ApplicationStatus;
import ish.common.types.PaymentSource;
import ish.math.Money;
import ish.oncourse.model.College;
import ish.oncourse.model.Course;
import ish.oncourse.model.Student;

/**
 * Class _Application was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Application extends CayenneDataObject {

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String ENROL_BY_PROPERTY = "enrolBy";
    public static final String FEE_OVERRIDE_PROPERTY = "feeOverride";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String REASON_PROPERTY = "reason";
    public static final String SOURCE_PROPERTY = "source";
    public static final String STATUS_PROPERTY = "status";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String COURSE_PROPERTY = "course";
    public static final String STUDENT_PROPERTY = "student";

    public static final String ID_PK_COLUMN = "id";

    public void setAngelId(Long angelId) {
        writeProperty(ANGEL_ID_PROPERTY, angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty(ANGEL_ID_PROPERTY);
    }

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setEnrolBy(Date enrolBy) {
        writeProperty(ENROL_BY_PROPERTY, enrolBy);
    }
    public Date getEnrolBy() {
        return (Date)readProperty(ENROL_BY_PROPERTY);
    }

    public void setFeeOverride(Money feeOverride) {
        writeProperty(FEE_OVERRIDE_PROPERTY, feeOverride);
    }
    public Money getFeeOverride() {
        return (Money)readProperty(FEE_OVERRIDE_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setReason(String reason) {
        writeProperty(REASON_PROPERTY, reason);
    }
    public String getReason() {
        return (String)readProperty(REASON_PROPERTY);
    }

    public void setSource(PaymentSource source) {
        writeProperty(SOURCE_PROPERTY, source);
    }
    public PaymentSource getSource() {
        return (PaymentSource)readProperty(SOURCE_PROPERTY);
    }

    public void setStatus(ApplicationStatus status) {
        writeProperty(STATUS_PROPERTY, status);
    }
    public ApplicationStatus getStatus() {
        return (ApplicationStatus)readProperty(STATUS_PROPERTY);
    }

    public void setCollege(College college) {
        setToOneTarget(COLLEGE_PROPERTY, college, true);
    }

    public College getCollege() {
        return (College)readProperty(COLLEGE_PROPERTY);
    }


    public void setCourse(Course course) {
        setToOneTarget(COURSE_PROPERTY, course, true);
    }

    public Course getCourse() {
        return (Course)readProperty(COURSE_PROPERTY);
    }


    public void setStudent(Student student) {
        setToOneTarget(STUDENT_PROPERTY, student, true);
    }

    public Student getStudent() {
        return (Student)readProperty(STUDENT_PROPERTY);
    }


}
