package ish.oncourse.model.auto;

import ish.common.types.ApplicationStatus;
import ish.common.types.ConfirmationStatus;
import ish.common.types.PaymentSource;
import ish.math.Money;
import ish.oncourse.model.College;
import ish.oncourse.model.Course;
import ish.oncourse.model.Student;
import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import java.util.Date;

/**
 * Class _Application was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Application extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String ANGEL_ID_PROPERTY = "angelId";
    @Deprecated
    public static final String CONFIRMATION_STATUS_PROPERTY = "confirmationStatus";
    @Deprecated
    public static final String CREATED_PROPERTY = "created";
    @Deprecated
    public static final String ENROL_BY_PROPERTY = "enrolBy";
    @Deprecated
    public static final String FEE_OVERRIDE_PROPERTY = "feeOverride";
    @Deprecated
    public static final String MODIFIED_PROPERTY = "modified";
    @Deprecated
    public static final String REASON_PROPERTY = "reason";
    @Deprecated
    public static final String SOURCE_PROPERTY = "source";
    @Deprecated
    public static final String STATUS_PROPERTY = "status";
    @Deprecated
    public static final String COLLEGE_PROPERTY = "college";
    @Deprecated
    public static final String COURSE_PROPERTY = "course";
    @Deprecated
    public static final String STUDENT_PROPERTY = "student";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = new Property<Long>("angelId");
    public static final Property<ConfirmationStatus> CONFIRMATION_STATUS = new Property<ConfirmationStatus>("confirmationStatus");
    public static final Property<Date> CREATED = new Property<Date>("created");
    public static final Property<Date> ENROL_BY = new Property<Date>("enrolBy");
    public static final Property<Money> FEE_OVERRIDE = new Property<Money>("feeOverride");
    public static final Property<Date> MODIFIED = new Property<Date>("modified");
    public static final Property<String> REASON = new Property<String>("reason");
    public static final Property<PaymentSource> SOURCE = new Property<PaymentSource>("source");
    public static final Property<ApplicationStatus> STATUS = new Property<ApplicationStatus>("status");
    public static final Property<College> COLLEGE = new Property<College>("college");
    public static final Property<Course> COURSE = new Property<Course>("course");
    public static final Property<Student> STUDENT = new Property<Student>("student");

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setConfirmationStatus(ConfirmationStatus confirmationStatus) {
        writeProperty("confirmationStatus", confirmationStatus);
    }
    public ConfirmationStatus getConfirmationStatus() {
        return (ConfirmationStatus)readProperty("confirmationStatus");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setEnrolBy(Date enrolBy) {
        writeProperty("enrolBy", enrolBy);
    }
    public Date getEnrolBy() {
        return (Date)readProperty("enrolBy");
    }

    public void setFeeOverride(Money feeOverride) {
        writeProperty("feeOverride", feeOverride);
    }
    public Money getFeeOverride() {
        return (Money)readProperty("feeOverride");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setReason(String reason) {
        writeProperty("reason", reason);
    }
    public String getReason() {
        return (String)readProperty("reason");
    }

    public void setSource(PaymentSource source) {
        writeProperty("source", source);
    }
    public PaymentSource getSource() {
        return (PaymentSource)readProperty("source");
    }

    public void setStatus(ApplicationStatus status) {
        writeProperty("status", status);
    }
    public ApplicationStatus getStatus() {
        return (ApplicationStatus)readProperty("status");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void setCourse(Course course) {
        setToOneTarget("course", course, true);
    }

    public Course getCourse() {
        return (Course)readProperty("course");
    }


    public void setStudent(Student student) {
        setToOneTarget("student", student, true);
    }

    public Student getStudent() {
        return (Student)readProperty("student");
    }


    protected abstract void onPostAdd();

}
