package ish.oncourse.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.College;
import ish.oncourse.model.Contact;
import ish.oncourse.model.ContactRelationType;

/**
 * Class _ContactRelation was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ContactRelation extends CayenneDataObject {

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String FROM_CONTACT_PROPERTY = "fromContact";
    public static final String RELATION_TYPE_PROPERTY = "relationType";
    public static final String TO_CONTACT_PROPERTY = "toContact";

    public static final String ID_PK_COLUMN = "id";

    public void setAngelId(Long angelId) {
        writeProperty(ANGEL_ID_PROPERTY, angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty(ANGEL_ID_PROPERTY);
    }

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setCollege(College college) {
        setToOneTarget(COLLEGE_PROPERTY, college, true);
    }

    public College getCollege() {
        return (College)readProperty(COLLEGE_PROPERTY);
    }


    public void setFromContact(Contact fromContact) {
        setToOneTarget(FROM_CONTACT_PROPERTY, fromContact, true);
    }

    public Contact getFromContact() {
        return (Contact)readProperty(FROM_CONTACT_PROPERTY);
    }


    public void setRelationType(ContactRelationType relationType) {
        setToOneTarget(RELATION_TYPE_PROPERTY, relationType, true);
    }

    public ContactRelationType getRelationType() {
        return (ContactRelationType)readProperty(RELATION_TYPE_PROPERTY);
    }


    public void setToContact(Contact toContact) {
        setToOneTarget(TO_CONTACT_PROPERTY, toContact, true);
    }

    public Contact getToContact() {
        return (Contact)readProperty(TO_CONTACT_PROPERTY);
    }


}
