package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.College;
import ish.oncourse.model.ContactRelation;
import ish.oncourse.model.DiscountMembershipRelationType;

/**
 * Class _ContactRelationType was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ContactRelationType extends CayenneDataObject {

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String FROM_CONTACT_NAME_PROPERTY = "fromContactName";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String TO_CONTACT_NAME_PROPERTY = "toContactName";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String CONTACT_RELATIONS_PROPERTY = "contactRelations";
    public static final String MEMBESHIP_DISCOUNT_RELATIONS_PROPERTY = "membeshipDiscountRelations";

    public static final String ID_PK_COLUMN = "id";

    public void setAngelId(Long angelId) {
        writeProperty(ANGEL_ID_PROPERTY, angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty(ANGEL_ID_PROPERTY);
    }

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setFromContactName(String fromContactName) {
        writeProperty(FROM_CONTACT_NAME_PROPERTY, fromContactName);
    }
    public String getFromContactName() {
        return (String)readProperty(FROM_CONTACT_NAME_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setToContactName(String toContactName) {
        writeProperty(TO_CONTACT_NAME_PROPERTY, toContactName);
    }
    public String getToContactName() {
        return (String)readProperty(TO_CONTACT_NAME_PROPERTY);
    }

    public void setCollege(College college) {
        setToOneTarget(COLLEGE_PROPERTY, college, true);
    }

    public College getCollege() {
        return (College)readProperty(COLLEGE_PROPERTY);
    }


    public void addToContactRelations(ContactRelation obj) {
        addToManyTarget(CONTACT_RELATIONS_PROPERTY, obj, true);
    }
    public void removeFromContactRelations(ContactRelation obj) {
        removeToManyTarget(CONTACT_RELATIONS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ContactRelation> getContactRelations() {
        return (List<ContactRelation>)readProperty(CONTACT_RELATIONS_PROPERTY);
    }


    public void addToMembeshipDiscountRelations(DiscountMembershipRelationType obj) {
        addToManyTarget(MEMBESHIP_DISCOUNT_RELATIONS_PROPERTY, obj, true);
    }
    public void removeFromMembeshipDiscountRelations(DiscountMembershipRelationType obj) {
        removeToManyTarget(MEMBESHIP_DISCOUNT_RELATIONS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DiscountMembershipRelationType> getMembeshipDiscountRelations() {
        return (List<DiscountMembershipRelationType>)readProperty(MEMBESHIP_DISCOUNT_RELATIONS_PROPERTY);
    }


}
