package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.College;
import ish.oncourse.model.Contact;
import ish.oncourse.model.CourseClass;
import ish.oncourse.model.Invoice;

/**
 * Class _CorporatePass was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CorporatePass extends CayenneDataObject {

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String EXPIRY_DATE_PROPERTY = "expiryDate";
    public static final String INVOICE_EMAIL_PROPERTY = "invoiceEmail";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String PASSWORD_PROPERTY = "password";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String CONTACT_PROPERTY = "contact";
    public static final String INVOICE_PROPERTY = "invoice";
    public static final String VALID_CLASSES_PROPERTY = "validClasses";

    public static final String ID_PK_COLUMN = "id";

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setExpiryDate(Date expiryDate) {
        writeProperty("expiryDate", expiryDate);
    }
    public Date getExpiryDate() {
        return (Date)readProperty("expiryDate");
    }

    public void setInvoiceEmail(String invoiceEmail) {
        writeProperty("invoiceEmail", invoiceEmail);
    }
    public String getInvoiceEmail() {
        return (String)readProperty("invoiceEmail");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setPassword(String password) {
        writeProperty("password", password);
    }
    public String getPassword() {
        return (String)readProperty("password");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void setContact(Contact contact) {
        setToOneTarget("contact", contact, true);
    }

    public Contact getContact() {
        return (Contact)readProperty("contact");
    }


    public void addToInvoice(Invoice obj) {
        addToManyTarget("invoice", obj, true);
    }
    public void removeFromInvoice(Invoice obj) {
        removeToManyTarget("invoice", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Invoice> getInvoice() {
        return (List<Invoice>)readProperty("invoice");
    }


    public void addToValidClasses(CourseClass obj) {
        addToManyTarget("validClasses", obj, true);
    }
    public void removeFromValidClasses(CourseClass obj) {
        removeToManyTarget("validClasses", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CourseClass> getValidClasses() {
        return (List<CourseClass>)readProperty("validClasses");
    }


}
