package ish.oncourse.model.auto;

import ish.common.types.CourseClassAttendanceType;
import ish.math.Money;
import ish.oncourse.model.*;
import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * Class _CourseClass was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CourseClass extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String ANGEL_ID_PROPERTY = "angelId";
    @Deprecated
    public static final String ATTENDANCE_TYPE_PROPERTY = "attendanceType";
    @Deprecated
    public static final String CANCELLED_PROPERTY = "cancelled";
    @Deprecated
    public static final String CENSUS_DATE_PROPERTY = "censusDate";
    @Deprecated
    public static final String CODE_PROPERTY = "code";
    @Deprecated
    public static final String COUNT_OF_SESSIONS_PROPERTY = "countOfSessions";
    @Deprecated
    public static final String CREATED_PROPERTY = "created";
    @Deprecated
    public static final String DELIVERY_MODE_PROPERTY = "deliveryMode";
    @Deprecated
    public static final String DETAIL_PROPERTY = "detail";
    @Deprecated
    public static final String DETAIL_TEXTILE_PROPERTY = "detailTextile";
    @Deprecated
    public static final String END_DATE_PROPERTY = "endDate";
    @Deprecated
    public static final String EXPECTED_HOURS_PROPERTY = "expectedHours";
    @Deprecated
    public static final String FEE_EX_GST_PROPERTY = "feeExGst";
    @Deprecated
    public static final String FEE_GST_PROPERTY = "feeGst";
    @Deprecated
    public static final String FEE_HELP_CLASS_PROPERTY = "feeHelpClass";
    @Deprecated
    public static final String FULL_TIME_LOAD_PROPERTY = "fullTimeLoad";
    @Deprecated
    public static final String IS_ACTIVE_PROPERTY = "isActive";
    @Deprecated
    public static final String IS_DISTANT_LEARNING_COURSE_PROPERTY = "isDistantLearningCourse";
    @Deprecated
    public static final String IS_WEB_VISIBLE_PROPERTY = "isWebVisible";
    @Deprecated
    public static final String MATERIALS_PROPERTY = "materials";
    @Deprecated
    public static final String MATERIALS_TEXTILE_PROPERTY = "materialsTextile";
    @Deprecated
    public static final String MAX_STUDENT_AGE_PROPERTY = "maxStudentAge";
    @Deprecated
    public static final String MAXIMUM_DAYS_PROPERTY = "maximumDays";
    @Deprecated
    public static final String MAXIMUM_PLACES_PROPERTY = "maximumPlaces";
    @Deprecated
    public static final String MIN_STUDENT_AGE_PROPERTY = "minStudentAge";
    @Deprecated
    public static final String MINIMUM_PLACES_PROPERTY = "minimumPlaces";
    @Deprecated
    public static final String MINUTES_PER_SESSION_PROPERTY = "minutesPerSession";
    @Deprecated
    public static final String MODIFIED_PROPERTY = "modified";
    @Deprecated
    public static final String REPORTING_PERIOD_PROPERTY = "reportingPeriod";
    @Deprecated
    public static final String SESSION_DETAIL_PROPERTY = "sessionDetail";
    @Deprecated
    public static final String SESSION_DETAIL_TEXTILE_PROPERTY = "sessionDetailTextile";
    @Deprecated
    public static final String START_DATE_PROPERTY = "startDate";
    @Deprecated
    public static final String STARTING_MINUTE_PER_SESSION_PROPERTY = "startingMinutePerSession";
    @Deprecated
    public static final String TIME_ZONE_PROPERTY = "timeZone";
    @Deprecated
    public static final String COLLEGE_PROPERTY = "college";
    @Deprecated
    public static final String COURSE_PROPERTY = "course";
    @Deprecated
    public static final String DISCOUNT_COURSE_CLASSES_PROPERTY = "discountCourseClasses";
    @Deprecated
    public static final String DISCUSSIONS_PROPERTY = "discussions";
    @Deprecated
    public static final String ENROLMENTS_PROPERTY = "enrolments";
    @Deprecated
    public static final String INVOICE_LINES_PROPERTY = "invoiceLines";
    @Deprecated
    public static final String PAYMENT_PLAN_LINES_PROPERTY = "paymentPlanLines";
    @Deprecated
    public static final String ROOM_PROPERTY = "room";
    @Deprecated
    public static final String SESSIONS_PROPERTY = "sessions";
    @Deprecated
    public static final String TUTOR_ROLES_PROPERTY = "tutorRoles";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = new Property<Long>("angelId");
    public static final Property<CourseClassAttendanceType> ATTENDANCE_TYPE = new Property<CourseClassAttendanceType>("attendanceType");
    public static final Property<Boolean> CANCELLED = new Property<Boolean>("cancelled");
    public static final Property<Date> CENSUS_DATE = new Property<Date>("censusDate");
    public static final Property<String> CODE = new Property<String>("code");
    public static final Property<Integer> COUNT_OF_SESSIONS = new Property<Integer>("countOfSessions");
    public static final Property<Date> CREATED = new Property<Date>("created");
    public static final Property<Integer> DELIVERY_MODE = new Property<Integer>("deliveryMode");
    public static final Property<String> DETAIL = new Property<String>("detail");
    public static final Property<String> DETAIL_TEXTILE = new Property<String>("detailTextile");
    public static final Property<Date> END_DATE = new Property<Date>("endDate");
    public static final Property<BigDecimal> EXPECTED_HOURS = new Property<BigDecimal>("expectedHours");
    public static final Property<Money> FEE_EX_GST = new Property<Money>("feeExGst");
    public static final Property<Money> FEE_GST = new Property<Money>("feeGst");
    public static final Property<Boolean> FEE_HELP_CLASS = new Property<Boolean>("feeHelpClass");
    public static final Property<String> FULL_TIME_LOAD = new Property<String>("fullTimeLoad");
    public static final Property<Boolean> IS_ACTIVE = new Property<Boolean>("isActive");
    public static final Property<Boolean> IS_DISTANT_LEARNING_COURSE = new Property<Boolean>("isDistantLearningCourse");
    public static final Property<Boolean> IS_WEB_VISIBLE = new Property<Boolean>("isWebVisible");
    public static final Property<String> MATERIALS = new Property<String>("materials");
    public static final Property<String> MATERIALS_TEXTILE = new Property<String>("materialsTextile");
    public static final Property<Integer> MAX_STUDENT_AGE = new Property<Integer>("maxStudentAge");
    public static final Property<Integer> MAXIMUM_DAYS = new Property<Integer>("maximumDays");
    public static final Property<Integer> MAXIMUM_PLACES = new Property<Integer>("maximumPlaces");
    public static final Property<Integer> MIN_STUDENT_AGE = new Property<Integer>("minStudentAge");
    public static final Property<Integer> MINIMUM_PLACES = new Property<Integer>("minimumPlaces");
    public static final Property<Integer> MINUTES_PER_SESSION = new Property<Integer>("minutesPerSession");
    public static final Property<Date> MODIFIED = new Property<Date>("modified");
    public static final Property<Integer> REPORTING_PERIOD = new Property<Integer>("reportingPeriod");
    public static final Property<String> SESSION_DETAIL = new Property<String>("sessionDetail");
    public static final Property<String> SESSION_DETAIL_TEXTILE = new Property<String>("sessionDetailTextile");
    public static final Property<Date> START_DATE = new Property<Date>("startDate");
    public static final Property<Integer> STARTING_MINUTE_PER_SESSION = new Property<Integer>("startingMinutePerSession");
    public static final Property<String> TIME_ZONE = new Property<String>("timeZone");
    public static final Property<College> COLLEGE = new Property<College>("college");
    public static final Property<Course> COURSE = new Property<Course>("course");
    public static final Property<List<DiscountCourseClass>> DISCOUNT_COURSE_CLASSES = new Property<List<DiscountCourseClass>>("discountCourseClasses");
    public static final Property<List<Discussion>> DISCUSSIONS = new Property<List<Discussion>>("discussions");
    public static final Property<List<Enrolment>> ENROLMENTS = new Property<List<Enrolment>>("enrolments");
    public static final Property<List<InvoiceLine>> INVOICE_LINES = new Property<List<InvoiceLine>>("invoiceLines");
    public static final Property<List<CourseClassPaymentPlanLine>> PAYMENT_PLAN_LINES = new Property<List<CourseClassPaymentPlanLine>>("paymentPlanLines");
    public static final Property<Room> ROOM = new Property<Room>("room");
    public static final Property<List<Session>> SESSIONS = new Property<List<Session>>("sessions");
    public static final Property<List<TutorRole>> TUTOR_ROLES = new Property<List<TutorRole>>("tutorRoles");

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setAttendanceType(CourseClassAttendanceType attendanceType) {
        writeProperty("attendanceType", attendanceType);
    }
    public CourseClassAttendanceType getAttendanceType() {
        return (CourseClassAttendanceType)readProperty("attendanceType");
    }

    public void setCancelled(boolean cancelled) {
        writeProperty("cancelled", cancelled);
    }
	public boolean isCancelled() {
        Boolean value = (Boolean)readProperty("cancelled");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setCensusDate(Date censusDate) {
        writeProperty("censusDate", censusDate);
    }
    public Date getCensusDate() {
        return (Date)readProperty("censusDate");
    }

    public void setCode(String code) {
        writeProperty("code", code);
    }
    public String getCode() {
        return (String)readProperty("code");
    }

    public void setCountOfSessions(Integer countOfSessions) {
        writeProperty("countOfSessions", countOfSessions);
    }
    public Integer getCountOfSessions() {
        return (Integer)readProperty("countOfSessions");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setDeliveryMode(Integer deliveryMode) {
        writeProperty("deliveryMode", deliveryMode);
    }
    public Integer getDeliveryMode() {
        return (Integer)readProperty("deliveryMode");
    }

    public void setDetail(String detail) {
        writeProperty("detail", detail);
    }
    public String getDetail() {
        return (String)readProperty("detail");
    }

    public void setDetailTextile(String detailTextile) {
        writeProperty("detailTextile", detailTextile);
    }
    public String getDetailTextile() {
        return (String)readProperty("detailTextile");
    }

    public void setEndDate(Date endDate) {
        writeProperty("endDate", endDate);
    }
    public Date getEndDate() {
        return (Date)readProperty("endDate");
    }

    public void setExpectedHours(BigDecimal expectedHours) {
        writeProperty("expectedHours", expectedHours);
    }
    public BigDecimal getExpectedHours() {
        return (BigDecimal)readProperty("expectedHours");
    }

    public void setFeeExGst(Money feeExGst) {
        writeProperty("feeExGst", feeExGst);
    }
    public Money getFeeExGst() {
        return (Money)readProperty("feeExGst");
    }

    public void setFeeGst(Money feeGst) {
        writeProperty("feeGst", feeGst);
    }
    public Money getFeeGst() {
        return (Money)readProperty("feeGst");
    }

    public void setFeeHelpClass(Boolean feeHelpClass) {
        writeProperty("feeHelpClass", feeHelpClass);
    }
    public Boolean getFeeHelpClass() {
        return (Boolean)readProperty("feeHelpClass");
    }

    public void setFullTimeLoad(String fullTimeLoad) {
        writeProperty("fullTimeLoad", fullTimeLoad);
    }
    public String getFullTimeLoad() {
        return (String)readProperty("fullTimeLoad");
    }

    public void setIsActive(Boolean isActive) {
        writeProperty("isActive", isActive);
    }
    public Boolean getIsActive() {
        return (Boolean)readProperty("isActive");
    }

    public void setIsDistantLearningCourse(Boolean isDistantLearningCourse) {
        writeProperty("isDistantLearningCourse", isDistantLearningCourse);
    }
    public Boolean getIsDistantLearningCourse() {
        return (Boolean)readProperty("isDistantLearningCourse");
    }

    public void setIsWebVisible(Boolean isWebVisible) {
        writeProperty("isWebVisible", isWebVisible);
    }
    public Boolean getIsWebVisible() {
        return (Boolean)readProperty("isWebVisible");
    }

    public void setMaterials(String materials) {
        writeProperty("materials", materials);
    }
    public String getMaterials() {
        return (String)readProperty("materials");
    }

    public void setMaterialsTextile(String materialsTextile) {
        writeProperty("materialsTextile", materialsTextile);
    }
    public String getMaterialsTextile() {
        return (String)readProperty("materialsTextile");
    }

    public void setMaxStudentAge(Integer maxStudentAge) {
        writeProperty("maxStudentAge", maxStudentAge);
    }
    public Integer getMaxStudentAge() {
        return (Integer)readProperty("maxStudentAge");
    }

    public void setMaximumDays(Integer maximumDays) {
        writeProperty("maximumDays", maximumDays);
    }
    public Integer getMaximumDays() {
        return (Integer)readProperty("maximumDays");
    }

    public void setMaximumPlaces(Integer maximumPlaces) {
        writeProperty("maximumPlaces", maximumPlaces);
    }
    public Integer getMaximumPlaces() {
        return (Integer)readProperty("maximumPlaces");
    }

    public void setMinStudentAge(Integer minStudentAge) {
        writeProperty("minStudentAge", minStudentAge);
    }
    public Integer getMinStudentAge() {
        return (Integer)readProperty("minStudentAge");
    }

    public void setMinimumPlaces(Integer minimumPlaces) {
        writeProperty("minimumPlaces", minimumPlaces);
    }
    public Integer getMinimumPlaces() {
        return (Integer)readProperty("minimumPlaces");
    }

    public void setMinutesPerSession(Integer minutesPerSession) {
        writeProperty("minutesPerSession", minutesPerSession);
    }
    public Integer getMinutesPerSession() {
        return (Integer)readProperty("minutesPerSession");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setReportingPeriod(Integer reportingPeriod) {
        writeProperty("reportingPeriod", reportingPeriod);
    }
    public Integer getReportingPeriod() {
        return (Integer)readProperty("reportingPeriod");
    }

    public void setSessionDetail(String sessionDetail) {
        writeProperty("sessionDetail", sessionDetail);
    }
    public String getSessionDetail() {
        return (String)readProperty("sessionDetail");
    }

    public void setSessionDetailTextile(String sessionDetailTextile) {
        writeProperty("sessionDetailTextile", sessionDetailTextile);
    }
    public String getSessionDetailTextile() {
        return (String)readProperty("sessionDetailTextile");
    }

    public void setStartDate(Date startDate) {
        writeProperty("startDate", startDate);
    }
    public Date getStartDate() {
        return (Date)readProperty("startDate");
    }

    public void setStartingMinutePerSession(Integer startingMinutePerSession) {
        writeProperty("startingMinutePerSession", startingMinutePerSession);
    }
    public Integer getStartingMinutePerSession() {
        return (Integer)readProperty("startingMinutePerSession");
    }

    public void setTimeZone(String timeZone) {
        writeProperty("timeZone", timeZone);
    }
    public String getTimeZone() {
        return (String)readProperty("timeZone");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void setCourse(Course course) {
        setToOneTarget("course", course, true);
    }

    public Course getCourse() {
        return (Course)readProperty("course");
    }


    public void addToDiscountCourseClasses(DiscountCourseClass obj) {
        addToManyTarget("discountCourseClasses", obj, true);
    }
    public void removeFromDiscountCourseClasses(DiscountCourseClass obj) {
        removeToManyTarget("discountCourseClasses", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DiscountCourseClass> getDiscountCourseClasses() {
        return (List<DiscountCourseClass>)readProperty("discountCourseClasses");
    }


    public void addToDiscussions(Discussion obj) {
        addToManyTarget("discussions", obj, true);
    }
    public void removeFromDiscussions(Discussion obj) {
        removeToManyTarget("discussions", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Discussion> getDiscussions() {
        return (List<Discussion>)readProperty("discussions");
    }


    public void addToEnrolments(Enrolment obj) {
        addToManyTarget("enrolments", obj, true);
    }
    public void removeFromEnrolments(Enrolment obj) {
        removeToManyTarget("enrolments", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Enrolment> getEnrolments() {
        return (List<Enrolment>)readProperty("enrolments");
    }


    public void addToInvoiceLines(InvoiceLine obj) {
        addToManyTarget("invoiceLines", obj, true);
    }
    public void removeFromInvoiceLines(InvoiceLine obj) {
        removeToManyTarget("invoiceLines", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InvoiceLine> getInvoiceLines() {
        return (List<InvoiceLine>)readProperty("invoiceLines");
    }


    public void addToPaymentPlanLines(CourseClassPaymentPlanLine obj) {
        addToManyTarget("paymentPlanLines", obj, true);
    }
    public void removeFromPaymentPlanLines(CourseClassPaymentPlanLine obj) {
        removeToManyTarget("paymentPlanLines", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CourseClassPaymentPlanLine> getPaymentPlanLines() {
        return (List<CourseClassPaymentPlanLine>)readProperty("paymentPlanLines");
    }


    public void setRoom(Room room) {
        setToOneTarget("room", room, true);
    }

    public Room getRoom() {
        return (Room)readProperty("room");
    }


    public void addToSessions(Session obj) {
        addToManyTarget("sessions", obj, true);
    }
    public void removeFromSessions(Session obj) {
        removeToManyTarget("sessions", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Session> getSessions() {
        return (List<Session>)readProperty("sessions");
    }


    public void addToTutorRoles(TutorRole obj) {
        addToManyTarget("tutorRoles", obj, true);
    }
    public void removeFromTutorRoles(TutorRole obj) {
        removeToManyTarget("tutorRoles", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TutorRole> getTutorRoles() {
        return (List<TutorRole>)readProperty("tutorRoles");
    }


}
