package ish.oncourse.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import ish.math.Money;
import ish.oncourse.model.College;
import ish.oncourse.model.CourseClass;

/**
 * Class _CourseClassPaymentPlanLine was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CourseClassPaymentPlanLine extends CayenneDataObject {

    public static final String AMOUNT_PROPERTY = "amount";
    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String DAY_OFFSET_PROPERTY = "dayOffset";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String COURSE_CLASS_PROPERTY = "courseClass";

    public static final String ID_PK_COLUMN = "id";

    public void setAmount(Money amount) {
        writeProperty(AMOUNT_PROPERTY, amount);
    }
    public Money getAmount() {
        return (Money)readProperty(AMOUNT_PROPERTY);
    }

    public void setAngelId(Long angelId) {
        writeProperty(ANGEL_ID_PROPERTY, angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty(ANGEL_ID_PROPERTY);
    }

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setDayOffset(Integer dayOffset) {
        writeProperty(DAY_OFFSET_PROPERTY, dayOffset);
    }
    public Integer getDayOffset() {
        return (Integer)readProperty(DAY_OFFSET_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setCollege(College college) {
        setToOneTarget(COLLEGE_PROPERTY, college, true);
    }

    public College getCollege() {
        return (College)readProperty(COLLEGE_PROPERTY);
    }


    public void setCourseClass(CourseClass courseClass) {
        setToOneTarget(COURSE_CLASS_PROPERTY, courseClass, true);
    }

    public CourseClass getCourseClass() {
        return (CourseClass)readProperty(COURSE_CLASS_PROPERTY);
    }


}
