package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.College;
import ish.oncourse.model.Discount;
import ish.oncourse.model.DiscountMembershipRelationType;
import ish.oncourse.model.Product;

/**
 * Class _DiscountMembership was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DiscountMembership extends CayenneDataObject {

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String APPLY_TO_MEMBER_ONLY_PROPERTY = "applyToMemberOnly";
    public static final String CREATED_PROPERTY = "created";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String DISCOUNT_PROPERTY = "discount";
    public static final String DISCOUNT_MEMBERSHIP_RELATION_TYPES_PROPERTY = "discountMembershipRelationTypes";
    public static final String MEMBERSHIP_PRODUCT_PROPERTY = "membershipProduct";

    public static final String ID_PK_COLUMN = "id";

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setApplyToMemberOnly(Boolean applyToMemberOnly) {
        writeProperty("applyToMemberOnly", applyToMemberOnly);
    }
    public Boolean getApplyToMemberOnly() {
        return (Boolean)readProperty("applyToMemberOnly");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void setDiscount(Discount discount) {
        setToOneTarget("discount", discount, true);
    }

    public Discount getDiscount() {
        return (Discount)readProperty("discount");
    }


    public void addToDiscountMembershipRelationTypes(DiscountMembershipRelationType obj) {
        addToManyTarget("discountMembershipRelationTypes", obj, true);
    }
    public void removeFromDiscountMembershipRelationTypes(DiscountMembershipRelationType obj) {
        removeToManyTarget("discountMembershipRelationTypes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DiscountMembershipRelationType> getDiscountMembershipRelationTypes() {
        return (List<DiscountMembershipRelationType>)readProperty("discountMembershipRelationTypes");
    }


    public void setMembershipProduct(Product membershipProduct) {
        setToOneTarget("membershipProduct", membershipProduct, true);
    }

    public Product getMembershipProduct() {
        return (Product)readProperty("membershipProduct");
    }


}
