package ish.oncourse.model.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.common.types.DiscountType;
import ish.math.Money;
import ish.math.MoneyRounding;
import ish.oncourse.model.College;
import ish.oncourse.model.DiscountConcessionType;
import ish.oncourse.model.DiscountCourseClass;
import ish.oncourse.model.DiscountMembership;
import ish.oncourse.model.InvoiceLineDiscount;

/**
 * Class _Discount was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Discount extends CayenneDataObject {

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CODE_PROPERTY = "code";
    public static final String COMBINATION_TYPE_PROPERTY = "combinationType";
    public static final String CREATED_PROPERTY = "created";
    public static final String DETAIL_PROPERTY = "detail";
    public static final String DISCOUNT_AMOUNT_PROPERTY = "discountAmount";
    public static final String DISCOUNT_RATE_PROPERTY = "discountRate";
    public static final String DISCOUNT_TYPE_PROPERTY = "discountType";
    public static final String HIDE_ON_WEB_PROPERTY = "hideOnWeb";
    public static final String IS_AVAILABLE_ON_WEB_PROPERTY = "isAvailableOnWeb";
    public static final String MAXIMUM_DISCOUNT_PROPERTY = "maximumDiscount";
    public static final String MINIMUM_DISCOUNT_PROPERTY = "minimumDiscount";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String ROUNDING_MODE_PROPERTY = "roundingMode";
    public static final String STUDENT_AGE_PROPERTY = "studentAge";
    public static final String STUDENT_AGE_OPERATOR_PROPERTY = "studentAgeOperator";
    public static final String STUDENT_ENROLLED_WITHIN_DAYS_PROPERTY = "studentEnrolledWithinDays";
    public static final String STUDENT_POSTCODES_PROPERTY = "studentPostcodes";
    public static final String STUDENTS_QUALIFIER_PROPERTY = "studentsQualifier";
    public static final String TIME_ZONE_PROPERTY = "timeZone";
    public static final String VALID_FROM_PROPERTY = "validFrom";
    public static final String VALID_TO_PROPERTY = "validTo";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String DISCOUNT_CONCESSION_TYPES_PROPERTY = "discountConcessionTypes";
    public static final String DISCOUNT_COURSE_CLASSES_PROPERTY = "discountCourseClasses";
    public static final String DISCOUNT_MEMBERSHIP_PRODUCTS_PROPERTY = "discountMembershipProducts";
    public static final String INVOICE_LINE_DISCOUNTS_PROPERTY = "invoiceLineDiscounts";

    public static final String ID_PK_COLUMN = "id";

    public void setAngelId(Long angelId) {
        writeProperty(ANGEL_ID_PROPERTY, angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty(ANGEL_ID_PROPERTY);
    }

    public void setCode(String code) {
        writeProperty(CODE_PROPERTY, code);
    }
    public String getCode() {
        return (String)readProperty(CODE_PROPERTY);
    }

    public void setCombinationType(Boolean combinationType) {
        writeProperty(COMBINATION_TYPE_PROPERTY, combinationType);
    }
    public Boolean getCombinationType() {
        return (Boolean)readProperty(COMBINATION_TYPE_PROPERTY);
    }

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setDetail(String detail) {
        writeProperty(DETAIL_PROPERTY, detail);
    }
    public String getDetail() {
        return (String)readProperty(DETAIL_PROPERTY);
    }

    public void setDiscountAmount(Money discountAmount) {
        writeProperty(DISCOUNT_AMOUNT_PROPERTY, discountAmount);
    }
    public Money getDiscountAmount() {
        return (Money)readProperty(DISCOUNT_AMOUNT_PROPERTY);
    }

    public void setDiscountRate(BigDecimal discountRate) {
        writeProperty(DISCOUNT_RATE_PROPERTY, discountRate);
    }
    public BigDecimal getDiscountRate() {
        return (BigDecimal)readProperty(DISCOUNT_RATE_PROPERTY);
    }

    public void setDiscountType(DiscountType discountType) {
        writeProperty(DISCOUNT_TYPE_PROPERTY, discountType);
    }
    public DiscountType getDiscountType() {
        return (DiscountType)readProperty(DISCOUNT_TYPE_PROPERTY);
    }

    public void setHideOnWeb(Boolean hideOnWeb) {
        writeProperty(HIDE_ON_WEB_PROPERTY, hideOnWeb);
    }
    public Boolean getHideOnWeb() {
        return (Boolean)readProperty(HIDE_ON_WEB_PROPERTY);
    }

    public void setIsAvailableOnWeb(Boolean isAvailableOnWeb) {
        writeProperty(IS_AVAILABLE_ON_WEB_PROPERTY, isAvailableOnWeb);
    }
    public Boolean getIsAvailableOnWeb() {
        return (Boolean)readProperty(IS_AVAILABLE_ON_WEB_PROPERTY);
    }

    public void setMaximumDiscount(Money maximumDiscount) {
        writeProperty(MAXIMUM_DISCOUNT_PROPERTY, maximumDiscount);
    }
    public Money getMaximumDiscount() {
        return (Money)readProperty(MAXIMUM_DISCOUNT_PROPERTY);
    }

    public void setMinimumDiscount(Money minimumDiscount) {
        writeProperty(MINIMUM_DISCOUNT_PROPERTY, minimumDiscount);
    }
    public Money getMinimumDiscount() {
        return (Money)readProperty(MINIMUM_DISCOUNT_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setRoundingMode(MoneyRounding roundingMode) {
        writeProperty(ROUNDING_MODE_PROPERTY, roundingMode);
    }
    public MoneyRounding getRoundingMode() {
        return (MoneyRounding)readProperty(ROUNDING_MODE_PROPERTY);
    }

    public void setStudentAge(Integer studentAge) {
        writeProperty(STUDENT_AGE_PROPERTY, studentAge);
    }
    public Integer getStudentAge() {
        return (Integer)readProperty(STUDENT_AGE_PROPERTY);
    }

    public void setStudentAgeOperator(String studentAgeOperator) {
        writeProperty(STUDENT_AGE_OPERATOR_PROPERTY, studentAgeOperator);
    }
    public String getStudentAgeOperator() {
        return (String)readProperty(STUDENT_AGE_OPERATOR_PROPERTY);
    }

    public void setStudentEnrolledWithinDays(Integer studentEnrolledWithinDays) {
        writeProperty(STUDENT_ENROLLED_WITHIN_DAYS_PROPERTY, studentEnrolledWithinDays);
    }
    public Integer getStudentEnrolledWithinDays() {
        return (Integer)readProperty(STUDENT_ENROLLED_WITHIN_DAYS_PROPERTY);
    }

    public void setStudentPostcodes(String studentPostcodes) {
        writeProperty(STUDENT_POSTCODES_PROPERTY, studentPostcodes);
    }
    public String getStudentPostcodes() {
        return (String)readProperty(STUDENT_POSTCODES_PROPERTY);
    }

    public void setStudentsQualifier(byte[] studentsQualifier) {
        writeProperty(STUDENTS_QUALIFIER_PROPERTY, studentsQualifier);
    }
    public byte[] getStudentsQualifier() {
        return (byte[])readProperty(STUDENTS_QUALIFIER_PROPERTY);
    }

    public void setTimeZone(String timeZone) {
        writeProperty(TIME_ZONE_PROPERTY, timeZone);
    }
    public String getTimeZone() {
        return (String)readProperty(TIME_ZONE_PROPERTY);
    }

    public void setValidFrom(Date validFrom) {
        writeProperty(VALID_FROM_PROPERTY, validFrom);
    }
    public Date getValidFrom() {
        return (Date)readProperty(VALID_FROM_PROPERTY);
    }

    public void setValidTo(Date validTo) {
        writeProperty(VALID_TO_PROPERTY, validTo);
    }
    public Date getValidTo() {
        return (Date)readProperty(VALID_TO_PROPERTY);
    }

    public void setCollege(College college) {
        setToOneTarget(COLLEGE_PROPERTY, college, true);
    }

    public College getCollege() {
        return (College)readProperty(COLLEGE_PROPERTY);
    }


    public void addToDiscountConcessionTypes(DiscountConcessionType obj) {
        addToManyTarget(DISCOUNT_CONCESSION_TYPES_PROPERTY, obj, true);
    }
    public void removeFromDiscountConcessionTypes(DiscountConcessionType obj) {
        removeToManyTarget(DISCOUNT_CONCESSION_TYPES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DiscountConcessionType> getDiscountConcessionTypes() {
        return (List<DiscountConcessionType>)readProperty(DISCOUNT_CONCESSION_TYPES_PROPERTY);
    }


    public void addToDiscountCourseClasses(DiscountCourseClass obj) {
        addToManyTarget(DISCOUNT_COURSE_CLASSES_PROPERTY, obj, true);
    }
    public void removeFromDiscountCourseClasses(DiscountCourseClass obj) {
        removeToManyTarget(DISCOUNT_COURSE_CLASSES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DiscountCourseClass> getDiscountCourseClasses() {
        return (List<DiscountCourseClass>)readProperty(DISCOUNT_COURSE_CLASSES_PROPERTY);
    }


    public void addToDiscountMembershipProducts(DiscountMembership obj) {
        addToManyTarget(DISCOUNT_MEMBERSHIP_PRODUCTS_PROPERTY, obj, true);
    }
    public void removeFromDiscountMembershipProducts(DiscountMembership obj) {
        removeToManyTarget(DISCOUNT_MEMBERSHIP_PRODUCTS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DiscountMembership> getDiscountMembershipProducts() {
        return (List<DiscountMembership>)readProperty(DISCOUNT_MEMBERSHIP_PRODUCTS_PROPERTY);
    }


    public void addToInvoiceLineDiscounts(InvoiceLineDiscount obj) {
        addToManyTarget(INVOICE_LINE_DISCOUNTS_PROPERTY, obj, true);
    }
    public void removeFromInvoiceLineDiscounts(InvoiceLineDiscount obj) {
        removeToManyTarget(INVOICE_LINE_DISCOUNTS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InvoiceLineDiscount> getInvoiceLineDiscounts() {
        return (List<InvoiceLineDiscount>)readProperty(INVOICE_LINE_DISCOUNTS_PROPERTY);
    }


}
