package ish.oncourse.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import ish.oncourse.model.College;

/**
 * Class _EmailTemplate was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EmailTemplate extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String ANGEL_ID_PROPERTY = "angelId";
    @Deprecated
    public static final String BODY_HTML_PROPERTY = "bodyHtml";
    @Deprecated
    public static final String BODY_PLAIN_PROPERTY = "bodyPlain";
    @Deprecated
    public static final String CREATED_PROPERTY = "created";
    @Deprecated
    public static final String ENTITY_PROPERTY = "entity";
    @Deprecated
    public static final String MODIFIED_PROPERTY = "modified";
    @Deprecated
    public static final String NAME_PROPERTY = "name";
    @Deprecated
    public static final String SUBJECT_PROPERTY = "subject";
    @Deprecated
    public static final String COLLEGE_PROPERTY = "college";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = new Property<Long>("angelId");
    public static final Property<String> BODY_HTML = new Property<String>("bodyHtml");
    public static final Property<String> BODY_PLAIN = new Property<String>("bodyPlain");
    public static final Property<Date> CREATED = new Property<Date>("created");
    public static final Property<String> ENTITY = new Property<String>("entity");
    public static final Property<Date> MODIFIED = new Property<Date>("modified");
    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<String> SUBJECT = new Property<String>("subject");
    public static final Property<College> COLLEGE = new Property<College>("college");

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setBodyHtml(String bodyHtml) {
        writeProperty("bodyHtml", bodyHtml);
    }
    public String getBodyHtml() {
        return (String)readProperty("bodyHtml");
    }

    public void setBodyPlain(String bodyPlain) {
        writeProperty("bodyPlain", bodyPlain);
    }
    public String getBodyPlain() {
        return (String)readProperty("bodyPlain");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setEntity(String entity) {
        writeProperty("entity", entity);
    }
    public String getEntity() {
        return (String)readProperty("entity");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setSubject(String subject) {
        writeProperty("subject", subject);
    }
    public String getSubject() {
        return (String)readProperty("subject");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


}
