package ish.oncourse.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.College;

/**
 * Class _EmailTemplate was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EmailTemplate extends CayenneDataObject {

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String BODY_HTML_PROPERTY = "bodyHtml";
    public static final String BODY_PLAIN_PROPERTY = "bodyPlain";
    public static final String CREATED_PROPERTY = "created";
    public static final String ENTITY_PROPERTY = "entity";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String SUBJECT_PROPERTY = "subject";
    public static final String COLLEGE_PROPERTY = "college";

    public static final String ID_PK_COLUMN = "id";

    public void setAngelId(Long angelId) {
        writeProperty(ANGEL_ID_PROPERTY, angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty(ANGEL_ID_PROPERTY);
    }

    public void setBodyHtml(String bodyHtml) {
        writeProperty(BODY_HTML_PROPERTY, bodyHtml);
    }
    public String getBodyHtml() {
        return (String)readProperty(BODY_HTML_PROPERTY);
    }

    public void setBodyPlain(String bodyPlain) {
        writeProperty(BODY_PLAIN_PROPERTY, bodyPlain);
    }
    public String getBodyPlain() {
        return (String)readProperty(BODY_PLAIN_PROPERTY);
    }

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setEntity(String entity) {
        writeProperty(ENTITY_PROPERTY, entity);
    }
    public String getEntity() {
        return (String)readProperty(ENTITY_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setSubject(String subject) {
        writeProperty(SUBJECT_PROPERTY, subject);
    }
    public String getSubject() {
        return (String)readProperty(SUBJECT_PROPERTY);
    }

    public void setCollege(College college) {
        setToOneTarget(COLLEGE_PROPERTY, college, true);
    }

    public College getCollege() {
        return (College)readProperty(COLLEGE_PROPERTY);
    }


}
