package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.common.types.ConfirmationStatus;
import ish.common.types.PaymentSource;
import ish.math.Money;
import ish.oncourse.model.College;
import ish.oncourse.model.Contact;
import ish.oncourse.model.CorporatePass;
import ish.oncourse.model.InvoiceLine;
import ish.oncourse.model.PaymentInLine;
import ish.oncourse.model.WebSite;

/**
 * Class _Invoice was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Invoice extends CayenneDataObject {

    public static final String AMOUNT_OWING_PROPERTY = "amountOwing";
    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String BILL_TO_ADDRESS_PROPERTY = "billToAddress";
    public static final String CONFIRMATION_STATUS_PROPERTY = "confirmationStatus";
    public static final String CREATED_PROPERTY = "created";
    public static final String CUSTOMER_REFERENCE_PROPERTY = "customerReference";
    public static final String DATE_DUE_PROPERTY = "dateDue";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String INVOICE_DATE_PROPERTY = "invoiceDate";
    public static final String INVOICE_NUMBER_PROPERTY = "invoiceNumber";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String PUBLIC_NOTES_PROPERTY = "publicNotes";
    public static final String SHIPPING_ADDRESS_PROPERTY = "shippingAddress";
    public static final String SOURCE_PROPERTY = "source";
    public static final String TOTAL_EX_GST_PROPERTY = "totalExGst";
    public static final String TOTAL_GST_PROPERTY = "totalGst";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String CONTACT_PROPERTY = "contact";
    public static final String CORPORATE_PASS_USED_PROPERTY = "corporatePassUsed";
    public static final String INVOICE_LINES_PROPERTY = "invoiceLines";
    public static final String PAYMENT_IN_LINES_PROPERTY = "paymentInLines";
    public static final String WEB_SITE_PROPERTY = "webSite";

    public static final String ID_PK_COLUMN = "id";

    public void setAmountOwing(Money amountOwing) {
        writeProperty("amountOwing", amountOwing);
    }
    public Money getAmountOwing() {
        return (Money)readProperty("amountOwing");
    }

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setBillToAddress(String billToAddress) {
        writeProperty("billToAddress", billToAddress);
    }
    public String getBillToAddress() {
        return (String)readProperty("billToAddress");
    }

    public void setConfirmationStatus(ConfirmationStatus confirmationStatus) {
        writeProperty(CONFIRMATION_STATUS_PROPERTY, confirmationStatus);
    }
    public ConfirmationStatus getConfirmationStatus() {
        return (ConfirmationStatus)readProperty(CONFIRMATION_STATUS_PROPERTY);
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setCustomerReference(String customerReference) {
        writeProperty("customerReference", customerReference);
    }
    public String getCustomerReference() {
        return (String)readProperty("customerReference");
    }

    public void setDateDue(Date dateDue) {
        writeProperty("dateDue", dateDue);
    }
    public Date getDateDue() {
        return (Date)readProperty("dateDue");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setInvoiceDate(Date invoiceDate) {
        writeProperty("invoiceDate", invoiceDate);
    }
    public Date getInvoiceDate() {
        return (Date)readProperty("invoiceDate");
    }

    public void setInvoiceNumber(Long invoiceNumber) {
        writeProperty("invoiceNumber", invoiceNumber);
    }
    public Long getInvoiceNumber() {
        return (Long)readProperty("invoiceNumber");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setPublicNotes(String publicNotes) {
        writeProperty("publicNotes", publicNotes);
    }
    public String getPublicNotes() {
        return (String)readProperty("publicNotes");
    }

    public void setShippingAddress(String shippingAddress) {
        writeProperty("shippingAddress", shippingAddress);
    }
    public String getShippingAddress() {
        return (String)readProperty("shippingAddress");
    }

    public void setSource(PaymentSource source) {
        writeProperty("source", source);
    }
    public PaymentSource getSource() {
        return (PaymentSource)readProperty("source");
    }

    public void setTotalExGst(Money totalExGst) {
        writeProperty("totalExGst", totalExGst);
    }
    public Money getTotalExGst() {
        return (Money)readProperty("totalExGst");
    }

    public void setTotalGst(Money totalGst) {
        writeProperty("totalGst", totalGst);
    }
    public Money getTotalGst() {
        return (Money)readProperty("totalGst");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void setContact(Contact contact) {
        setToOneTarget("contact", contact, true);
    }

    public Contact getContact() {
        return (Contact)readProperty("contact");
    }


    public void setCorporatePassUsed(CorporatePass corporatePassUsed) {
        setToOneTarget("corporatePassUsed", corporatePassUsed, true);
    }

    public CorporatePass getCorporatePassUsed() {
        return (CorporatePass)readProperty("corporatePassUsed");
    }


    public void addToInvoiceLines(InvoiceLine obj) {
        addToManyTarget("invoiceLines", obj, true);
    }
    public void removeFromInvoiceLines(InvoiceLine obj) {
        removeToManyTarget("invoiceLines", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InvoiceLine> getInvoiceLines() {
        return (List<InvoiceLine>)readProperty("invoiceLines");
    }


    public void addToPaymentInLines(PaymentInLine obj) {
        addToManyTarget("paymentInLines", obj, true);
    }
    public void removeFromPaymentInLines(PaymentInLine obj) {
        removeToManyTarget("paymentInLines", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PaymentInLine> getPaymentInLines() {
        return (List<PaymentInLine>)readProperty("paymentInLines");
    }


    public void setWebSite(WebSite webSite) {
        setToOneTarget("webSite", webSite, true);
    }

    public WebSite getWebSite() {
        return (WebSite)readProperty("webSite");
    }


    protected abstract void onPostAdd();

    protected abstract void onPreUpdate();

    protected abstract void onPrePersist();

}
