package ish.oncourse.model.auto;

import ish.common.types.ConfirmationStatus;
import ish.common.types.PaymentSource;
import ish.math.Money;
import ish.oncourse.model.*;
import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import java.util.Date;
import java.util.List;

/**
 * Class _Invoice was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Invoice extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String AMOUNT_OWING_PROPERTY = "amountOwing";
    @Deprecated
    public static final String ANGEL_ID_PROPERTY = "angelId";
    @Deprecated
    public static final String BILL_TO_ADDRESS_PROPERTY = "billToAddress";
    @Deprecated
    public static final String CONFIRMATION_STATUS_PROPERTY = "confirmationStatus";
    @Deprecated
    public static final String CREATED_PROPERTY = "created";
    @Deprecated
    public static final String CUSTOMER_REFERENCE_PROPERTY = "customerReference";
    @Deprecated
    public static final String DATE_DUE_PROPERTY = "dateDue";
    @Deprecated
    public static final String DESCRIPTION_PROPERTY = "description";
    @Deprecated
    public static final String INVOICE_DATE_PROPERTY = "invoiceDate";
    @Deprecated
    public static final String INVOICE_NUMBER_PROPERTY = "invoiceNumber";
    @Deprecated
    public static final String MODIFIED_PROPERTY = "modified";
    @Deprecated
    public static final String PUBLIC_NOTES_PROPERTY = "publicNotes";
    @Deprecated
    public static final String SHIPPING_ADDRESS_PROPERTY = "shippingAddress";
    @Deprecated
    public static final String SOURCE_PROPERTY = "source";
    @Deprecated
    public static final String TOTAL_EX_GST_PROPERTY = "totalExGst";
    @Deprecated
    public static final String TOTAL_GST_PROPERTY = "totalGst";
    @Deprecated
    public static final String COLLEGE_PROPERTY = "college";
    @Deprecated
    public static final String CONTACT_PROPERTY = "contact";
    @Deprecated
    public static final String CORPORATE_PASS_USED_PROPERTY = "corporatePassUsed";
    @Deprecated
    public static final String INVOICE_DUE_DATES_PROPERTY = "invoiceDueDates";
    @Deprecated
    public static final String INVOICE_LINES_PROPERTY = "invoiceLines";
    @Deprecated
    public static final String PAYMENT_IN_LINES_PROPERTY = "paymentInLines";
    @Deprecated
    public static final String WEB_SITE_PROPERTY = "webSite";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Money> AMOUNT_OWING = new Property<Money>("amountOwing");
    public static final Property<Long> ANGEL_ID = new Property<Long>("angelId");
    public static final Property<String> BILL_TO_ADDRESS = new Property<String>("billToAddress");
    public static final Property<ConfirmationStatus> CONFIRMATION_STATUS = new Property<ConfirmationStatus>("confirmationStatus");
    public static final Property<Date> CREATED = new Property<Date>("created");
    public static final Property<String> CUSTOMER_REFERENCE = new Property<String>("customerReference");
    public static final Property<Date> DATE_DUE = new Property<Date>("dateDue");
    public static final Property<String> DESCRIPTION = new Property<String>("description");
    public static final Property<Date> INVOICE_DATE = new Property<Date>("invoiceDate");
    public static final Property<Long> INVOICE_NUMBER = new Property<Long>("invoiceNumber");
    public static final Property<Date> MODIFIED = new Property<Date>("modified");
    public static final Property<String> PUBLIC_NOTES = new Property<String>("publicNotes");
    public static final Property<String> SHIPPING_ADDRESS = new Property<String>("shippingAddress");
    public static final Property<PaymentSource> SOURCE = new Property<PaymentSource>("source");
    public static final Property<Money> TOTAL_EX_GST = new Property<Money>("totalExGst");
    public static final Property<Money> TOTAL_GST = new Property<Money>("totalGst");
    public static final Property<College> COLLEGE = new Property<College>("college");
    public static final Property<Contact> CONTACT = new Property<Contact>("contact");
    public static final Property<CorporatePass> CORPORATE_PASS_USED = new Property<CorporatePass>("corporatePassUsed");
    public static final Property<List<InvoiceDueDate>> INVOICE_DUE_DATES = new Property<List<InvoiceDueDate>>("invoiceDueDates");
    public static final Property<List<InvoiceLine>> INVOICE_LINES = new Property<List<InvoiceLine>>("invoiceLines");
    public static final Property<List<PaymentInLine>> PAYMENT_IN_LINES = new Property<List<PaymentInLine>>("paymentInLines");
    public static final Property<WebSite> WEB_SITE = new Property<WebSite>("webSite");

    public void setAmountOwing(Money amountOwing) {
        writeProperty("amountOwing", amountOwing);
    }
    public Money getAmountOwing() {
        return (Money)readProperty("amountOwing");
    }

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setBillToAddress(String billToAddress) {
        writeProperty("billToAddress", billToAddress);
    }
    public String getBillToAddress() {
        return (String)readProperty("billToAddress");
    }

    public void setConfirmationStatus(ConfirmationStatus confirmationStatus) {
        writeProperty("confirmationStatus", confirmationStatus);
    }
    public ConfirmationStatus getConfirmationStatus() {
        return (ConfirmationStatus)readProperty("confirmationStatus");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setCustomerReference(String customerReference) {
        writeProperty("customerReference", customerReference);
    }
    public String getCustomerReference() {
        return (String)readProperty("customerReference");
    }

    public void setDateDue(Date dateDue) {
        writeProperty("dateDue", dateDue);
    }
    public Date getDateDue() {
        return (Date)readProperty("dateDue");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setInvoiceDate(Date invoiceDate) {
        writeProperty("invoiceDate", invoiceDate);
    }
    public Date getInvoiceDate() {
        return (Date)readProperty("invoiceDate");
    }

    public void setInvoiceNumber(Long invoiceNumber) {
        writeProperty("invoiceNumber", invoiceNumber);
    }
    public Long getInvoiceNumber() {
        return (Long)readProperty("invoiceNumber");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setPublicNotes(String publicNotes) {
        writeProperty("publicNotes", publicNotes);
    }
    public String getPublicNotes() {
        return (String)readProperty("publicNotes");
    }

    public void setShippingAddress(String shippingAddress) {
        writeProperty("shippingAddress", shippingAddress);
    }
    public String getShippingAddress() {
        return (String)readProperty("shippingAddress");
    }

    public void setSource(PaymentSource source) {
        writeProperty("source", source);
    }
    public PaymentSource getSource() {
        return (PaymentSource)readProperty("source");
    }

    public void setTotalExGst(Money totalExGst) {
        writeProperty("totalExGst", totalExGst);
    }
    public Money getTotalExGst() {
        return (Money)readProperty("totalExGst");
    }

    public void setTotalGst(Money totalGst) {
        writeProperty("totalGst", totalGst);
    }
    public Money getTotalGst() {
        return (Money)readProperty("totalGst");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void setContact(Contact contact) {
        setToOneTarget("contact", contact, true);
    }

    public Contact getContact() {
        return (Contact)readProperty("contact");
    }


    public void setCorporatePassUsed(CorporatePass corporatePassUsed) {
        setToOneTarget("corporatePassUsed", corporatePassUsed, true);
    }

    public CorporatePass getCorporatePassUsed() {
        return (CorporatePass)readProperty("corporatePassUsed");
    }


    public void addToInvoiceDueDates(InvoiceDueDate obj) {
        addToManyTarget("invoiceDueDates", obj, true);
    }
    public void removeFromInvoiceDueDates(InvoiceDueDate obj) {
        removeToManyTarget("invoiceDueDates", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InvoiceDueDate> getInvoiceDueDates() {
        return (List<InvoiceDueDate>)readProperty("invoiceDueDates");
    }


    public void addToInvoiceLines(InvoiceLine obj) {
        addToManyTarget("invoiceLines", obj, true);
    }
    public void removeFromInvoiceLines(InvoiceLine obj) {
        removeToManyTarget("invoiceLines", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InvoiceLine> getInvoiceLines() {
        return (List<InvoiceLine>)readProperty("invoiceLines");
    }


    public void addToPaymentInLines(PaymentInLine obj) {
        addToManyTarget("paymentInLines", obj, true);
    }
    public void removeFromPaymentInLines(PaymentInLine obj) {
        removeToManyTarget("paymentInLines", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PaymentInLine> getPaymentInLines() {
        return (List<PaymentInLine>)readProperty("paymentInLines");
    }


    public void setWebSite(WebSite webSite) {
        setToOneTarget("webSite", webSite, true);
    }

    public WebSite getWebSite() {
        return (WebSite)readProperty("webSite");
    }


    protected abstract void onPostAdd();

    protected abstract void onPreUpdate();

    protected abstract void onPrePersist();

}
