package ish.oncourse.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Language was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Language extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String ABS_CODE_PROPERTY = "absCode";
    @Deprecated
    public static final String CREATED_PROPERTY = "created";
    @Deprecated
    public static final String IS_ACTIVE_PROPERTY = "isActive";
    @Deprecated
    public static final String ISH_VERSION_PROPERTY = "ishVersion";
    @Deprecated
    public static final String MODIFIED_PROPERTY = "modified";
    @Deprecated
    public static final String NAME_PROPERTY = "name";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> ABS_CODE = new Property<String>("absCode");
    public static final Property<Date> CREATED = new Property<Date>("created");
    public static final Property<Byte> IS_ACTIVE = new Property<Byte>("isActive");
    public static final Property<Long> ISH_VERSION = new Property<Long>("ishVersion");
    public static final Property<Date> MODIFIED = new Property<Date>("modified");
    public static final Property<String> NAME = new Property<String>("name");

    public void setAbsCode(String absCode) {
        writeProperty("absCode", absCode);
    }
    public String getAbsCode() {
        return (String)readProperty("absCode");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setIsActive(Byte isActive) {
        writeProperty("isActive", isActive);
    }
    public Byte getIsActive() {
        return (Byte)readProperty("isActive");
    }

    public void setIshVersion(Long ishVersion) {
        writeProperty("ishVersion", ishVersion);
    }
    public Long getIshVersion() {
        return (Long)readProperty("ishVersion");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

}
