package ish.oncourse.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.College;
import ish.oncourse.model.WillowUser;

/**
 * Class _Log was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Log extends CayenneDataObject {

    public static final String ACTION_PROPERTY = "action";
    public static final String CREATED_PROPERTY = "created";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String PAGE_PROPERTY = "page";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String USER_PROPERTY = "user";

    public static final String ID_PK_COLUMN = "id";

    public void setAction(String action) {
        writeProperty(ACTION_PROPERTY, action);
    }
    public String getAction() {
        return (String)readProperty(ACTION_PROPERTY);
    }

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setPage(String page) {
        writeProperty(PAGE_PROPERTY, page);
    }
    public String getPage() {
        return (String)readProperty(PAGE_PROPERTY);
    }

    public void setCollege(College college) {
        setToOneTarget(COLLEGE_PROPERTY, college, true);
    }

    public College getCollege() {
        return (College)readProperty(COLLEGE_PROPERTY);
    }


    public void setUser(WillowUser user) {
        setToOneTarget(USER_PROPERTY, user, true);
    }

    public WillowUser getUser() {
        return (WillowUser)readProperty(USER_PROPERTY);
    }


}
