package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.College;
import ish.oncourse.model.MessagePerson;

/**
 * Class _Message was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Message extends CayenneDataObject {

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String EMAIL_BODY_PROPERTY = "emailBody";
    public static final String EMAIL_SUBJECT_PROPERTY = "emailSubject";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String SMS_TEXT_PROPERTY = "smsText";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String MESSAGE_PEOPLE_PROPERTY = "messagePeople";

    public static final String ID_PK_COLUMN = "id";

    public void setAngelId(Long angelId) {
        writeProperty(ANGEL_ID_PROPERTY, angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty(ANGEL_ID_PROPERTY);
    }

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setEmailBody(String emailBody) {
        writeProperty(EMAIL_BODY_PROPERTY, emailBody);
    }
    public String getEmailBody() {
        return (String)readProperty(EMAIL_BODY_PROPERTY);
    }

    public void setEmailSubject(String emailSubject) {
        writeProperty(EMAIL_SUBJECT_PROPERTY, emailSubject);
    }
    public String getEmailSubject() {
        return (String)readProperty(EMAIL_SUBJECT_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setSmsText(String smsText) {
        writeProperty(SMS_TEXT_PROPERTY, smsText);
    }
    public String getSmsText() {
        return (String)readProperty(SMS_TEXT_PROPERTY);
    }

    public void setCollege(College college) {
        setToOneTarget(COLLEGE_PROPERTY, college, true);
    }

    public College getCollege() {
        return (College)readProperty(COLLEGE_PROPERTY);
    }


    public void addToMessagePeople(MessagePerson obj) {
        addToManyTarget(MESSAGE_PEOPLE_PROPERTY, obj, true);
    }
    public void removeFromMessagePeople(MessagePerson obj) {
        removeToManyTarget(MESSAGE_PEOPLE_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MessagePerson> getMessagePeople() {
        return (List<MessagePerson>)readProperty(MESSAGE_PEOPLE_PROPERTY);
    }


}
