package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.CourseModule;
import ish.oncourse.model.SessionModule;

/**
 * Class _Module was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Module extends CayenneDataObject {

    public static final String CREATED_PROPERTY = "created";
    public static final String DISCIPLINE_CODE_PROPERTY = "disciplineCode";
    public static final String FIELD_OF_EDUCATION_PROPERTY = "fieldOfEducation";
    public static final String IS_MODULE_PROPERTY = "isModule";
    public static final String ISH_VERSION_PROPERTY = "ishVersion";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NATIONAL_CODE_PROPERTY = "nationalCode";
    public static final String TITLE_PROPERTY = "title";
    public static final String TRAINING_PACKAGE_ID_PROPERTY = "trainingPackageId";
    public static final String MODULE_COURSES_PROPERTY = "moduleCourses";
    public static final String SESSION_MODULES_PROPERTY = "sessionModules";

    public static final String ID_PK_COLUMN = "id";

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setDisciplineCode(String disciplineCode) {
        writeProperty("disciplineCode", disciplineCode);
    }
    public String getDisciplineCode() {
        return (String)readProperty("disciplineCode");
    }

    public void setFieldOfEducation(String fieldOfEducation) {
        writeProperty("fieldOfEducation", fieldOfEducation);
    }
    public String getFieldOfEducation() {
        return (String)readProperty("fieldOfEducation");
    }

    public void setIsModule(Byte isModule) {
        writeProperty("isModule", isModule);
    }
    public Byte getIsModule() {
        return (Byte)readProperty("isModule");
    }

    public void setIshVersion(Long ishVersion) {
        writeProperty("ishVersion", ishVersion);
    }
    public Long getIshVersion() {
        return (Long)readProperty("ishVersion");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setNationalCode(String nationalCode) {
        writeProperty("nationalCode", nationalCode);
    }
    public String getNationalCode() {
        return (String)readProperty("nationalCode");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

    public void setTrainingPackageId(Long trainingPackageId) {
        writeProperty("trainingPackageId", trainingPackageId);
    }
    public Long getTrainingPackageId() {
        return (Long)readProperty("trainingPackageId");
    }

    public void addToModuleCourses(CourseModule obj) {
        addToManyTarget("moduleCourses", obj, true);
    }
    public void removeFromModuleCourses(CourseModule obj) {
        removeToManyTarget("moduleCourses", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CourseModule> getModuleCourses() {
        return (List<CourseModule>)readProperty("moduleCourses");
    }


    public void addToSessionModules(SessionModule obj) {
        addToManyTarget("sessionModules", obj, true);
    }
    public void removeFromSessionModules(SessionModule obj) {
        removeToManyTarget("sessionModules", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SessionModule> getSessionModules() {
        return (List<SessionModule>)readProperty("sessionModules");
    }


    protected abstract void onPreUpdate();

    protected abstract void onPrePersist();

}
