package ish.oncourse.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.College;

/**
 * Class _NotificationTemplate was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NotificationTemplate extends CayenneDataObject {

    public static final String ALLOW_WEBOBJECTS_TAGS_PROPERTY = "allowWebobjectsTags";
    public static final String ALLOWED_IN_TEXTILE_TAGS_PROPERTY = "allowedInTextileTags";
    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String MESSAGE_PROPERTY = "message";
    public static final String MIME_TYPE_PROPERTY = "mimeType";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String SUBJECT_PROPERTY = "subject";
    public static final String COLLEGE_PROPERTY = "college";

    public static final String ID_PK_COLUMN = "id";

    public void setAllowWebobjectsTags(Boolean allowWebobjectsTags) {
        writeProperty(ALLOW_WEBOBJECTS_TAGS_PROPERTY, allowWebobjectsTags);
    }
    public Boolean getAllowWebobjectsTags() {
        return (Boolean)readProperty(ALLOW_WEBOBJECTS_TAGS_PROPERTY);
    }

    public void setAllowedInTextileTags(Boolean allowedInTextileTags) {
        writeProperty(ALLOWED_IN_TEXTILE_TAGS_PROPERTY, allowedInTextileTags);
    }
    public Boolean getAllowedInTextileTags() {
        return (Boolean)readProperty(ALLOWED_IN_TEXTILE_TAGS_PROPERTY);
    }

    public void setAngelId(Long angelId) {
        writeProperty(ANGEL_ID_PROPERTY, angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty(ANGEL_ID_PROPERTY);
    }

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setMessage(String message) {
        writeProperty(MESSAGE_PROPERTY, message);
    }
    public String getMessage() {
        return (String)readProperty(MESSAGE_PROPERTY);
    }

    public void setMimeType(String mimeType) {
        writeProperty(MIME_TYPE_PROPERTY, mimeType);
    }
    public String getMimeType() {
        return (String)readProperty(MIME_TYPE_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setSubject(String subject) {
        writeProperty(SUBJECT_PROPERTY, subject);
    }
    public String getSubject() {
        return (String)readProperty(SUBJECT_PROPERTY);
    }

    public void setCollege(College college) {
        setToOneTarget(COLLEGE_PROPERTY, college, true);
    }

    public College getCollege() {
        return (College)readProperty(COLLEGE_PROPERTY);
    }


}
