package ish.oncourse.model.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.common.types.CreditCardType;
import ish.common.types.PaymentSource;
import ish.common.types.PaymentStatus;
import ish.oncourse.model.College;
import ish.oncourse.model.Contact;
import ish.oncourse.model.PaymentOutTransaction;

/**
 * Class _PaymentOut was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PaymentOut extends CayenneDataObject {

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String CREDIT_CARD_CVV_PROPERTY = "creditCardCVV";
    public static final String CREDIT_CARD_TYPE_PROPERTY = "creditCardType";
    public static final String DATE_BANKED_PROPERTY = "dateBanked";
    public static final String DATE_PAID_PROPERTY = "datePaid";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String PAYMENT_IN_TXN_REFERENCE_PROPERTY = "paymentInTxnReference";
    public static final String SOURCE_PROPERTY = "source";
    public static final String STATUS_PROPERTY = "status";
    public static final String STATUS_NOTES_PROPERTY = "statusNotes";
    public static final String TOTAL_AMOUNT_PROPERTY = "totalAmount";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String CONTACT_PROPERTY = "contact";
    public static final String PAYMENT_OUT_TRANSACTIONS_PROPERTY = "paymentOutTransactions";

    public static final String ID_PK_COLUMN = "id";

    public void setAngelId(Long angelId) {
        writeProperty(ANGEL_ID_PROPERTY, angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty(ANGEL_ID_PROPERTY);
    }

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setCreditCardCVV(String creditCardCVV) {
        writeProperty(CREDIT_CARD_CVV_PROPERTY, creditCardCVV);
    }
    public String getCreditCardCVV() {
        return (String)readProperty(CREDIT_CARD_CVV_PROPERTY);
    }

    public void setCreditCardType(CreditCardType creditCardType) {
        writeProperty(CREDIT_CARD_TYPE_PROPERTY, creditCardType);
    }
    public CreditCardType getCreditCardType() {
        return (CreditCardType)readProperty(CREDIT_CARD_TYPE_PROPERTY);
    }

    public void setDateBanked(Date dateBanked) {
        writeProperty(DATE_BANKED_PROPERTY, dateBanked);
    }
    public Date getDateBanked() {
        return (Date)readProperty(DATE_BANKED_PROPERTY);
    }

    public void setDatePaid(Date datePaid) {
        writeProperty(DATE_PAID_PROPERTY, datePaid);
    }
    public Date getDatePaid() {
        return (Date)readProperty(DATE_PAID_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setPaymentInTxnReference(String paymentInTxnReference) {
        writeProperty(PAYMENT_IN_TXN_REFERENCE_PROPERTY, paymentInTxnReference);
    }
    public String getPaymentInTxnReference() {
        return (String)readProperty(PAYMENT_IN_TXN_REFERENCE_PROPERTY);
    }

    public void setSource(PaymentSource source) {
        writeProperty(SOURCE_PROPERTY, source);
    }
    public PaymentSource getSource() {
        return (PaymentSource)readProperty(SOURCE_PROPERTY);
    }

    public void setStatus(PaymentStatus status) {
        writeProperty(STATUS_PROPERTY, status);
    }
    public PaymentStatus getStatus() {
        return (PaymentStatus)readProperty(STATUS_PROPERTY);
    }

    public void setStatusNotes(String statusNotes) {
        writeProperty(STATUS_NOTES_PROPERTY, statusNotes);
    }
    public String getStatusNotes() {
        return (String)readProperty(STATUS_NOTES_PROPERTY);
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        writeProperty(TOTAL_AMOUNT_PROPERTY, totalAmount);
    }
    public BigDecimal getTotalAmount() {
        return (BigDecimal)readProperty(TOTAL_AMOUNT_PROPERTY);
    }

    public void setCollege(College college) {
        setToOneTarget(COLLEGE_PROPERTY, college, true);
    }

    public College getCollege() {
        return (College)readProperty(COLLEGE_PROPERTY);
    }


    public void setContact(Contact contact) {
        setToOneTarget(CONTACT_PROPERTY, contact, true);
    }

    public Contact getContact() {
        return (Contact)readProperty(CONTACT_PROPERTY);
    }


    public void addToPaymentOutTransactions(PaymentOutTransaction obj) {
        addToManyTarget(PAYMENT_OUT_TRANSACTIONS_PROPERTY, obj, true);
    }
    public void removeFromPaymentOutTransactions(PaymentOutTransaction obj) {
        removeToManyTarget(PAYMENT_OUT_TRANSACTIONS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PaymentOutTransaction> getPaymentOutTransactions() {
        return (List<PaymentOutTransaction>)readProperty(PAYMENT_OUT_TRANSACTIONS_PROPERTY);
    }


    protected abstract void onPrePersist();

}
