package ish.oncourse.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import ish.common.types.ConfirmationStatus;
import ish.common.types.ProductStatus;
import ish.oncourse.model.College;
import ish.oncourse.model.Contact;
import ish.oncourse.model.InvoiceLine;
import ish.oncourse.model.Product;

/**
 * Class _ProductItem was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ProductItem extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String ANGEL_ID_PROPERTY = "angelId";
    @Deprecated
    public static final String CONFIRMATION_STATUS_PROPERTY = "confirmationStatus";
    @Deprecated
    public static final String CREATED_PROPERTY = "created";
    @Deprecated
    public static final String EXPIRY_DATE_PROPERTY = "expiryDate";
    @Deprecated
    public static final String MODIFIED_PROPERTY = "modified";
    @Deprecated
    public static final String STATUS_PROPERTY = "status";
    @Deprecated
    public static final String TYPE_PROPERTY = "type";
    @Deprecated
    public static final String COLLEGE_PROPERTY = "college";
    @Deprecated
    public static final String CONTACT_PROPERTY = "contact";
    @Deprecated
    public static final String INVOICE_LINE_PROPERTY = "invoiceLine";
    @Deprecated
    public static final String PRODUCT_PROPERTY = "product";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = new Property<Long>("angelId");
    public static final Property<ConfirmationStatus> CONFIRMATION_STATUS = new Property<ConfirmationStatus>("confirmationStatus");
    public static final Property<Date> CREATED = new Property<Date>("created");
    public static final Property<Date> EXPIRY_DATE = new Property<Date>("expiryDate");
    public static final Property<Date> MODIFIED = new Property<Date>("modified");
    public static final Property<ProductStatus> STATUS = new Property<ProductStatus>("status");
    public static final Property<Integer> TYPE = new Property<Integer>("type");
    public static final Property<College> COLLEGE = new Property<College>("college");
    public static final Property<Contact> CONTACT = new Property<Contact>("contact");
    public static final Property<InvoiceLine> INVOICE_LINE = new Property<InvoiceLine>("invoiceLine");
    public static final Property<Product> PRODUCT = new Property<Product>("product");

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setConfirmationStatus(ConfirmationStatus confirmationStatus) {
        writeProperty("confirmationStatus", confirmationStatus);
    }
    public ConfirmationStatus getConfirmationStatus() {
        return (ConfirmationStatus)readProperty("confirmationStatus");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setExpiryDate(Date expiryDate) {
        writeProperty("expiryDate", expiryDate);
    }
    public Date getExpiryDate() {
        return (Date)readProperty("expiryDate");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setStatus(ProductStatus status) {
        writeProperty("status", status);
    }
    public ProductStatus getStatus() {
        return (ProductStatus)readProperty("status");
    }

    public void setType(Integer type) {
        writeProperty("type", type);
    }
    public Integer getType() {
        return (Integer)readProperty("type");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void setContact(Contact contact) {
        setToOneTarget("contact", contact, true);
    }

    public Contact getContact() {
        return (Contact)readProperty("contact");
    }


    public void setInvoiceLine(InvoiceLine invoiceLine) {
        setToOneTarget("invoiceLine", invoiceLine, true);
    }

    public InvoiceLine getInvoiceLine() {
        return (InvoiceLine)readProperty("invoiceLine");
    }


    public void setProduct(Product product) {
        setToOneTarget("product", product, true);
    }

    public Product getProduct() {
        return (Product)readProperty("product");
    }


    protected abstract void onPostAdd();

}
