package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import ish.oncourse.model.Attendance;
import ish.oncourse.model.College;
import ish.oncourse.model.CourseClass;
import ish.oncourse.model.Room;
import ish.oncourse.model.SessionModule;
import ish.oncourse.model.SessionTutor;
import ish.oncourse.model.Tutor;

/**
 * Class _Session was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Session extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String ANGEL_ID_PROPERTY = "angelId";
    @Deprecated
    public static final String CREATED_PROPERTY = "created";
    @Deprecated
    public static final String END_DATE_PROPERTY = "endDate";
    @Deprecated
    public static final String MODIFIED_PROPERTY = "modified";
    @Deprecated
    public static final String PRIVATE_NOTES_PROPERTY = "privateNotes";
    @Deprecated
    public static final String PUBLIC_NOTES_PROPERTY = "publicNotes";
    @Deprecated
    public static final String START_DATE_PROPERTY = "startDate";
    @Deprecated
    public static final String TIME_ZONE_PROPERTY = "timeZone";
    @Deprecated
    public static final String ATTENDANCES_PROPERTY = "attendances";
    @Deprecated
    public static final String COLLEGE_PROPERTY = "college";
    @Deprecated
    public static final String COURSE_CLASS_PROPERTY = "courseClass";
    @Deprecated
    public static final String MARKER_PROPERTY = "marker";
    @Deprecated
    public static final String ROOM_PROPERTY = "room";
    @Deprecated
    public static final String SESSION_MODULES_PROPERTY = "sessionModules";
    @Deprecated
    public static final String SESSION_TUTORS_PROPERTY = "sessionTutors";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = new Property<Long>("angelId");
    public static final Property<Date> CREATED = new Property<Date>("created");
    public static final Property<Date> END_DATE = new Property<Date>("endDate");
    public static final Property<Date> MODIFIED = new Property<Date>("modified");
    public static final Property<String> PRIVATE_NOTES = new Property<String>("privateNotes");
    public static final Property<String> PUBLIC_NOTES = new Property<String>("publicNotes");
    public static final Property<Date> START_DATE = new Property<Date>("startDate");
    public static final Property<String> TIME_ZONE = new Property<String>("timeZone");
    public static final Property<List<Attendance>> ATTENDANCES = new Property<List<Attendance>>("attendances");
    public static final Property<College> COLLEGE = new Property<College>("college");
    public static final Property<CourseClass> COURSE_CLASS = new Property<CourseClass>("courseClass");
    public static final Property<Tutor> MARKER = new Property<Tutor>("marker");
    public static final Property<Room> ROOM = new Property<Room>("room");
    public static final Property<List<SessionModule>> SESSION_MODULES = new Property<List<SessionModule>>("sessionModules");
    public static final Property<List<SessionTutor>> SESSION_TUTORS = new Property<List<SessionTutor>>("sessionTutors");

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setEndDate(Date endDate) {
        writeProperty("endDate", endDate);
    }
    public Date getEndDate() {
        return (Date)readProperty("endDate");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setPrivateNotes(String privateNotes) {
        writeProperty("privateNotes", privateNotes);
    }
    public String getPrivateNotes() {
        return (String)readProperty("privateNotes");
    }

    public void setPublicNotes(String publicNotes) {
        writeProperty("publicNotes", publicNotes);
    }
    public String getPublicNotes() {
        return (String)readProperty("publicNotes");
    }

    public void setStartDate(Date startDate) {
        writeProperty("startDate", startDate);
    }
    public Date getStartDate() {
        return (Date)readProperty("startDate");
    }

    public void setTimeZone(String timeZone) {
        writeProperty("timeZone", timeZone);
    }
    public String getTimeZone() {
        return (String)readProperty("timeZone");
    }

    public void addToAttendances(Attendance obj) {
        addToManyTarget("attendances", obj, true);
    }
    public void removeFromAttendances(Attendance obj) {
        removeToManyTarget("attendances", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Attendance> getAttendances() {
        return (List<Attendance>)readProperty("attendances");
    }


    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void setCourseClass(CourseClass courseClass) {
        setToOneTarget("courseClass", courseClass, true);
    }

    public CourseClass getCourseClass() {
        return (CourseClass)readProperty("courseClass");
    }


    public void setMarker(Tutor marker) {
        setToOneTarget("marker", marker, true);
    }

    public Tutor getMarker() {
        return (Tutor)readProperty("marker");
    }


    public void setRoom(Room room) {
        setToOneTarget("room", room, true);
    }

    public Room getRoom() {
        return (Room)readProperty("room");
    }


    public void addToSessionModules(SessionModule obj) {
        addToManyTarget("sessionModules", obj, true);
    }
    public void removeFromSessionModules(SessionModule obj) {
        removeToManyTarget("sessionModules", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SessionModule> getSessionModules() {
        return (List<SessionModule>)readProperty("sessionModules");
    }


    public void addToSessionTutors(SessionTutor obj) {
        addToManyTarget("sessionTutors", obj, true);
    }
    public void removeFromSessionTutors(SessionTutor obj) {
        removeToManyTarget("sessionTutors", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SessionTutor> getSessionTutors() {
        return (List<SessionTutor>)readProperty("sessionTutors");
    }


}
