package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.common.types.AvetmissStudentDisabilityType;
import ish.common.types.AvetmissStudentEnglishProficiency;
import ish.common.types.AvetmissStudentIndigenousStatus;
import ish.common.types.AvetmissStudentPriorEducation;
import ish.common.types.AvetmissStudentSchoolLevel;
import ish.common.types.StudentCitizenship;
import ish.common.types.UsiStatus;
import ish.oncourse.model.Application;
import ish.oncourse.model.Attendance;
import ish.oncourse.model.Certificate;
import ish.oncourse.model.College;
import ish.oncourse.model.Contact;
import ish.oncourse.model.Country;
import ish.oncourse.model.Enrolment;
import ish.oncourse.model.Language;
import ish.oncourse.model.MessagePerson;
import ish.oncourse.model.PaymentIn;
import ish.oncourse.model.StudentConcession;
import ish.oncourse.model.WaitingList;

/**
 * Class _Student was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Student extends CayenneDataObject {

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CHESSN_PROPERTY = "chessn";
    public static final String CITIZENSHIP_PROPERTY = "citizenship";
    public static final String CONCESSION_TYPE_PROPERTY = "concessionType";
    public static final String CREATED_PROPERTY = "created";
    public static final String DISABILITY_TYPE_PROPERTY = "disabilityType";
    public static final String ENGLISH_PROFICIENCY_PROPERTY = "englishProficiency";
    public static final String FEE_HELP_ELIGIBLE_PROPERTY = "feeHelpEligible";
    public static final String HIGHEST_SCHOOL_LEVEL_PROPERTY = "highestSchoolLevel";
    public static final String INDIGENOUS_STATUS_PROPERTY = "indigenousStatus";
    public static final String IS_OVERSEAS_CLIENT_PROPERTY = "isOverseasClient";
    public static final String IS_STILL_AT_SCHOOL_PROPERTY = "isStillAtSchool";
    public static final String LABOUR_FORCE_TYPE_PROPERTY = "labourForceType";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String PRIOR_EDUCATION_CODE_PROPERTY = "priorEducationCode";
    public static final String SPECIAL_NEEDS_PROPERTY = "specialNeeds";
    public static final String SPECIAL_NEEDS_ASSISTANCE_PROPERTY = "specialNeedsAssistance";
    public static final String TOWN_OF_BIRTH_PROPERTY = "townOfBirth";
    public static final String USI_PROPERTY = "usi";
    public static final String USI_STATUS_PROPERTY = "usiStatus";
    public static final String YEAR_SCHOOL_COMPLETED_PROPERTY = "yearSchoolCompleted";
    public static final String APPLICATIONS_PROPERTY = "applications";
    public static final String ATTENDANCES_PROPERTY = "attendances";
    public static final String CERTIFICATES_PROPERTY = "certificates";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String CONTACT_PROPERTY = "contact";
    public static final String COUNTRY_OF_BIRTH_PROPERTY = "countryOfBirth";
    public static final String ENROLMENTS_PROPERTY = "enrolments";
    public static final String LANGUAGE_PROPERTY = "language";
    public static final String LANGUAGE_HOME_PROPERTY = "languageHome";
    public static final String MESSAGE_PEOPLE_PROPERTY = "messagePeople";
    public static final String PAYMENTS_IN_PROPERTY = "paymentsIn";
    public static final String STUDENT_CONCESSIONS_PROPERTY = "studentConcessions";
    public static final String WAITING_LISTS_PROPERTY = "waitingLists";

    public static final String ID_PK_COLUMN = "id";

    public void setAngelId(Long angelId) {
        writeProperty(ANGEL_ID_PROPERTY, angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty(ANGEL_ID_PROPERTY);
    }

    public void setChessn(String chessn) {
        writeProperty(CHESSN_PROPERTY, chessn);
    }
    public String getChessn() {
        return (String)readProperty(CHESSN_PROPERTY);
    }

    public void setCitizenship(StudentCitizenship citizenship) {
        writeProperty(CITIZENSHIP_PROPERTY, citizenship);
    }
    public StudentCitizenship getCitizenship() {
        return (StudentCitizenship)readProperty(CITIZENSHIP_PROPERTY);
    }

    public void setConcessionType(Integer concessionType) {
        writeProperty(CONCESSION_TYPE_PROPERTY, concessionType);
    }
    public Integer getConcessionType() {
        return (Integer)readProperty(CONCESSION_TYPE_PROPERTY);
    }

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setDisabilityType(AvetmissStudentDisabilityType disabilityType) {
        writeProperty(DISABILITY_TYPE_PROPERTY, disabilityType);
    }
    public AvetmissStudentDisabilityType getDisabilityType() {
        return (AvetmissStudentDisabilityType)readProperty(DISABILITY_TYPE_PROPERTY);
    }

    public void setEnglishProficiency(AvetmissStudentEnglishProficiency englishProficiency) {
        writeProperty(ENGLISH_PROFICIENCY_PROPERTY, englishProficiency);
    }
    public AvetmissStudentEnglishProficiency getEnglishProficiency() {
        return (AvetmissStudentEnglishProficiency)readProperty(ENGLISH_PROFICIENCY_PROPERTY);
    }

    public void setFeeHelpEligible(Boolean feeHelpEligible) {
        writeProperty(FEE_HELP_ELIGIBLE_PROPERTY, feeHelpEligible);
    }
    public Boolean getFeeHelpEligible() {
        return (Boolean)readProperty(FEE_HELP_ELIGIBLE_PROPERTY);
    }

    public void setHighestSchoolLevel(AvetmissStudentSchoolLevel highestSchoolLevel) {
        writeProperty(HIGHEST_SCHOOL_LEVEL_PROPERTY, highestSchoolLevel);
    }
    public AvetmissStudentSchoolLevel getHighestSchoolLevel() {
        return (AvetmissStudentSchoolLevel)readProperty(HIGHEST_SCHOOL_LEVEL_PROPERTY);
    }

    public void setIndigenousStatus(AvetmissStudentIndigenousStatus indigenousStatus) {
        writeProperty(INDIGENOUS_STATUS_PROPERTY, indigenousStatus);
    }
    public AvetmissStudentIndigenousStatus getIndigenousStatus() {
        return (AvetmissStudentIndigenousStatus)readProperty(INDIGENOUS_STATUS_PROPERTY);
    }

    public void setIsOverseasClient(Boolean isOverseasClient) {
        writeProperty(IS_OVERSEAS_CLIENT_PROPERTY, isOverseasClient);
    }
    public Boolean getIsOverseasClient() {
        return (Boolean)readProperty(IS_OVERSEAS_CLIENT_PROPERTY);
    }

    public void setIsStillAtSchool(Boolean isStillAtSchool) {
        writeProperty(IS_STILL_AT_SCHOOL_PROPERTY, isStillAtSchool);
    }
    public Boolean getIsStillAtSchool() {
        return (Boolean)readProperty(IS_STILL_AT_SCHOOL_PROPERTY);
    }

    public void setLabourForceType(Integer labourForceType) {
        writeProperty(LABOUR_FORCE_TYPE_PROPERTY, labourForceType);
    }
    public Integer getLabourForceType() {
        return (Integer)readProperty(LABOUR_FORCE_TYPE_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setPriorEducationCode(AvetmissStudentPriorEducation priorEducationCode) {
        writeProperty(PRIOR_EDUCATION_CODE_PROPERTY, priorEducationCode);
    }
    public AvetmissStudentPriorEducation getPriorEducationCode() {
        return (AvetmissStudentPriorEducation)readProperty(PRIOR_EDUCATION_CODE_PROPERTY);
    }

    public void setSpecialNeeds(String specialNeeds) {
        writeProperty(SPECIAL_NEEDS_PROPERTY, specialNeeds);
    }
    public String getSpecialNeeds() {
        return (String)readProperty(SPECIAL_NEEDS_PROPERTY);
    }

    public void setSpecialNeedsAssistance(Boolean specialNeedsAssistance) {
        writeProperty(SPECIAL_NEEDS_ASSISTANCE_PROPERTY, specialNeedsAssistance);
    }
    public Boolean getSpecialNeedsAssistance() {
        return (Boolean)readProperty(SPECIAL_NEEDS_ASSISTANCE_PROPERTY);
    }

    public void setTownOfBirth(String townOfBirth) {
        writeProperty(TOWN_OF_BIRTH_PROPERTY, townOfBirth);
    }
    public String getTownOfBirth() {
        return (String)readProperty(TOWN_OF_BIRTH_PROPERTY);
    }

    public void setUsi(String usi) {
        writeProperty(USI_PROPERTY, usi);
    }
    public String getUsi() {
        return (String)readProperty(USI_PROPERTY);
    }

    public void setUsiStatus(UsiStatus usiStatus) {
        writeProperty(USI_STATUS_PROPERTY, usiStatus);
    }
    public UsiStatus getUsiStatus() {
        return (UsiStatus)readProperty(USI_STATUS_PROPERTY);
    }

    public void setYearSchoolCompleted(Integer yearSchoolCompleted) {
        writeProperty(YEAR_SCHOOL_COMPLETED_PROPERTY, yearSchoolCompleted);
    }
    public Integer getYearSchoolCompleted() {
        return (Integer)readProperty(YEAR_SCHOOL_COMPLETED_PROPERTY);
    }

    public void addToApplications(Application obj) {
        addToManyTarget(APPLICATIONS_PROPERTY, obj, true);
    }
    public void removeFromApplications(Application obj) {
        removeToManyTarget(APPLICATIONS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Application> getApplications() {
        return (List<Application>)readProperty(APPLICATIONS_PROPERTY);
    }


    public void addToAttendances(Attendance obj) {
        addToManyTarget(ATTENDANCES_PROPERTY, obj, true);
    }
    public void removeFromAttendances(Attendance obj) {
        removeToManyTarget(ATTENDANCES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Attendance> getAttendances() {
        return (List<Attendance>)readProperty(ATTENDANCES_PROPERTY);
    }


    public void addToCertificates(Certificate obj) {
        addToManyTarget(CERTIFICATES_PROPERTY, obj, true);
    }
    public void removeFromCertificates(Certificate obj) {
        removeToManyTarget(CERTIFICATES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Certificate> getCertificates() {
        return (List<Certificate>)readProperty(CERTIFICATES_PROPERTY);
    }


    public void setCollege(College college) {
        setToOneTarget(COLLEGE_PROPERTY, college, true);
    }

    public College getCollege() {
        return (College)readProperty(COLLEGE_PROPERTY);
    }


    public void setContact(Contact contact) {
        setToOneTarget(CONTACT_PROPERTY, contact, true);
    }

    public Contact getContact() {
        return (Contact)readProperty(CONTACT_PROPERTY);
    }


    public void setCountryOfBirth(Country countryOfBirth) {
        setToOneTarget(COUNTRY_OF_BIRTH_PROPERTY, countryOfBirth, true);
    }

    public Country getCountryOfBirth() {
        return (Country)readProperty(COUNTRY_OF_BIRTH_PROPERTY);
    }


    public void addToEnrolments(Enrolment obj) {
        addToManyTarget(ENROLMENTS_PROPERTY, obj, true);
    }
    public void removeFromEnrolments(Enrolment obj) {
        removeToManyTarget(ENROLMENTS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Enrolment> getEnrolments() {
        return (List<Enrolment>)readProperty(ENROLMENTS_PROPERTY);
    }


    public void setLanguage(Language language) {
        setToOneTarget(LANGUAGE_PROPERTY, language, true);
    }

    public Language getLanguage() {
        return (Language)readProperty(LANGUAGE_PROPERTY);
    }


    public void setLanguageHome(Language languageHome) {
        setToOneTarget(LANGUAGE_HOME_PROPERTY, languageHome, true);
    }

    public Language getLanguageHome() {
        return (Language)readProperty(LANGUAGE_HOME_PROPERTY);
    }


    public void addToMessagePeople(MessagePerson obj) {
        addToManyTarget(MESSAGE_PEOPLE_PROPERTY, obj, true);
    }
    public void removeFromMessagePeople(MessagePerson obj) {
        removeToManyTarget(MESSAGE_PEOPLE_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MessagePerson> getMessagePeople() {
        return (List<MessagePerson>)readProperty(MESSAGE_PEOPLE_PROPERTY);
    }


    public void addToPaymentsIn(PaymentIn obj) {
        addToManyTarget(PAYMENTS_IN_PROPERTY, obj, true);
    }
    public void removeFromPaymentsIn(PaymentIn obj) {
        removeToManyTarget(PAYMENTS_IN_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PaymentIn> getPaymentsIn() {
        return (List<PaymentIn>)readProperty(PAYMENTS_IN_PROPERTY);
    }


    public void addToStudentConcessions(StudentConcession obj) {
        addToManyTarget(STUDENT_CONCESSIONS_PROPERTY, obj, true);
    }
    public void removeFromStudentConcessions(StudentConcession obj) {
        removeToManyTarget(STUDENT_CONCESSIONS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<StudentConcession> getStudentConcessions() {
        return (List<StudentConcession>)readProperty(STUDENT_CONCESSIONS_PROPERTY);
    }


    public void addToWaitingLists(WaitingList obj) {
        addToManyTarget(WAITING_LISTS_PROPERTY, obj, true);
    }
    public void removeFromWaitingLists(WaitingList obj) {
        removeToManyTarget(WAITING_LISTS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WaitingList> getWaitingLists() {
        return (List<WaitingList>)readProperty(WAITING_LISTS_PROPERTY);
    }


    protected abstract void onPostAdd();

}
