package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.College;
import ish.oncourse.model.DocumentVersion;
import ish.oncourse.model.Site;
import ish.oncourse.model.WebSiteVersion;

/**
 * Class _SystemUser was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SystemUser extends CayenneDataObject {

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String EDIT_CMS_PROPERTY = "editCMS";
    public static final String EDIT_TARA_PROPERTY = "editTara";
    public static final String EMAIL_PROPERTY = "email";
    public static final String FIRST_NAME_PROPERTY = "firstName";
    public static final String IS_ACTIVE_PROPERTY = "isActive";
    public static final String IS_ADMIN_PROPERTY = "isAdmin";
    public static final String LAST_LOGIN_IP_PROPERTY = "lastLoginIP";
    public static final String LAST_LOGIN_ON_PROPERTY = "lastLoginOn";
    public static final String LOGIN_PROPERTY = "login";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String PASSWORD_PROPERTY = "password";
    public static final String SURNAME_PROPERTY = "surname";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String DEFAULT_ADMINISTRATION_CENTRE_PROPERTY = "defaultAdministrationCentre";
    public static final String DOCUMENT_VERSIONS_PROPERTY = "documentVersions";
    public static final String SITES_DEPLOYED_PROPERTY = "sitesDeployed";

    public static final String ID_PK_COLUMN = "id";

    public void setAngelId(Long angelId) {
        writeProperty(ANGEL_ID_PROPERTY, angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty(ANGEL_ID_PROPERTY);
    }

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setEditCMS(Boolean editCMS) {
        writeProperty(EDIT_CMS_PROPERTY, editCMS);
    }
    public Boolean getEditCMS() {
        return (Boolean)readProperty(EDIT_CMS_PROPERTY);
    }

    public void setEditTara(Boolean editTara) {
        writeProperty(EDIT_TARA_PROPERTY, editTara);
    }
    public Boolean getEditTara() {
        return (Boolean)readProperty(EDIT_TARA_PROPERTY);
    }

    public void setEmail(String email) {
        writeProperty(EMAIL_PROPERTY, email);
    }
    public String getEmail() {
        return (String)readProperty(EMAIL_PROPERTY);
    }

    public void setFirstName(String firstName) {
        writeProperty(FIRST_NAME_PROPERTY, firstName);
    }
    public String getFirstName() {
        return (String)readProperty(FIRST_NAME_PROPERTY);
    }

    public void setIsActive(Boolean isActive) {
        writeProperty(IS_ACTIVE_PROPERTY, isActive);
    }
    public Boolean getIsActive() {
        return (Boolean)readProperty(IS_ACTIVE_PROPERTY);
    }

    public void setIsAdmin(Boolean isAdmin) {
        writeProperty(IS_ADMIN_PROPERTY, isAdmin);
    }
    public Boolean getIsAdmin() {
        return (Boolean)readProperty(IS_ADMIN_PROPERTY);
    }

    public void setLastLoginIP(String lastLoginIP) {
        writeProperty(LAST_LOGIN_IP_PROPERTY, lastLoginIP);
    }
    public String getLastLoginIP() {
        return (String)readProperty(LAST_LOGIN_IP_PROPERTY);
    }

    public void setLastLoginOn(Date lastLoginOn) {
        writeProperty(LAST_LOGIN_ON_PROPERTY, lastLoginOn);
    }
    public Date getLastLoginOn() {
        return (Date)readProperty(LAST_LOGIN_ON_PROPERTY);
    }

    public void setLogin(String login) {
        writeProperty(LOGIN_PROPERTY, login);
    }
    public String getLogin() {
        return (String)readProperty(LOGIN_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setPassword(String password) {
        writeProperty(PASSWORD_PROPERTY, password);
    }
    public String getPassword() {
        return (String)readProperty(PASSWORD_PROPERTY);
    }

    public void setSurname(String surname) {
        writeProperty(SURNAME_PROPERTY, surname);
    }
    public String getSurname() {
        return (String)readProperty(SURNAME_PROPERTY);
    }

    public void setCollege(College college) {
        setToOneTarget(COLLEGE_PROPERTY, college, true);
    }

    public College getCollege() {
        return (College)readProperty(COLLEGE_PROPERTY);
    }


    public void setDefaultAdministrationCentre(Site defaultAdministrationCentre) {
        setToOneTarget(DEFAULT_ADMINISTRATION_CENTRE_PROPERTY, defaultAdministrationCentre, true);
    }

    public Site getDefaultAdministrationCentre() {
        return (Site)readProperty(DEFAULT_ADMINISTRATION_CENTRE_PROPERTY);
    }


    public void addToDocumentVersions(DocumentVersion obj) {
        addToManyTarget(DOCUMENT_VERSIONS_PROPERTY, obj, true);
    }
    public void removeFromDocumentVersions(DocumentVersion obj) {
        removeToManyTarget(DOCUMENT_VERSIONS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DocumentVersion> getDocumentVersions() {
        return (List<DocumentVersion>)readProperty(DOCUMENT_VERSIONS_PROPERTY);
    }


    public void addToSitesDeployed(WebSiteVersion obj) {
        addToManyTarget(SITES_DEPLOYED_PROPERTY, obj, true);
    }
    public void removeFromSitesDeployed(WebSiteVersion obj) {
        removeToManyTarget(SITES_DEPLOYED_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebSiteVersion> getSitesDeployed() {
        return (List<WebSiteVersion>)readProperty(SITES_DEPLOYED_PROPERTY);
    }


}
