package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import ish.oncourse.model.College;
import ish.oncourse.model.TaggableTag;

/**
 * Class _Taggable was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Taggable extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String ANGEL_ID_PROPERTY = "angelId";
    @Deprecated
    public static final String CREATED_PROPERTY = "created";
    @Deprecated
    public static final String ENTITY_ANGEL_ID_PROPERTY = "entityAngelId";
    @Deprecated
    public static final String ENTITY_IDENTIFIER_PROPERTY = "entityIdentifier";
    @Deprecated
    public static final String ENTITY_WILLOW_ID_PROPERTY = "entityWillowId";
    @Deprecated
    public static final String MODIFIED_PROPERTY = "modified";
    @Deprecated
    public static final String COLLEGE_PROPERTY = "college";
    @Deprecated
    public static final String TAGGABLE_TAGS_PROPERTY = "taggableTags";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = new Property<Long>("angelId");
    public static final Property<Date> CREATED = new Property<Date>("created");
    public static final Property<Long> ENTITY_ANGEL_ID = new Property<Long>("entityAngelId");
    public static final Property<String> ENTITY_IDENTIFIER = new Property<String>("entityIdentifier");
    public static final Property<Long> ENTITY_WILLOW_ID = new Property<Long>("entityWillowId");
    public static final Property<Date> MODIFIED = new Property<Date>("modified");
    public static final Property<College> COLLEGE = new Property<College>("college");
    public static final Property<List<TaggableTag>> TAGGABLE_TAGS = new Property<List<TaggableTag>>("taggableTags");

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setEntityAngelId(Long entityAngelId) {
        writeProperty("entityAngelId", entityAngelId);
    }
    public Long getEntityAngelId() {
        return (Long)readProperty("entityAngelId");
    }

    public void setEntityIdentifier(String entityIdentifier) {
        writeProperty("entityIdentifier", entityIdentifier);
    }
    public String getEntityIdentifier() {
        return (String)readProperty("entityIdentifier");
    }

    public void setEntityWillowId(Long entityWillowId) {
        writeProperty("entityWillowId", entityWillowId);
    }
    public Long getEntityWillowId() {
        return (Long)readProperty("entityWillowId");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void addToTaggableTags(TaggableTag obj) {
        addToManyTarget("taggableTags", obj, true);
    }
    public void removeFromTaggableTags(TaggableTag obj) {
        removeToManyTarget("taggableTags", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TaggableTag> getTaggableTags() {
        return (List<TaggableTag>)readProperty("taggableTags");
    }


}
