package ish.oncourse.model.auto;

import ish.oncourse.model.College;
import ish.oncourse.model.Tag;
import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import java.util.Date;

/**
 * Class _TagGroupRequirement was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TagGroupRequirement extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String ALLOWS_MULTIPLE_TAGS_PROPERTY = "allowsMultipleTags";
    @Deprecated
    public static final String ANGEL_ID_PROPERTY = "angelId";
    @Deprecated
    public static final String CREATED_PROPERTY = "created";
    @Deprecated
    public static final String ENTITY_IDENTIFIER_PROPERTY = "entityIdentifier";
    @Deprecated
    public static final String IS_REQUIRED_PROPERTY = "isRequired";
    @Deprecated
    public static final String MODIFIED_PROPERTY = "modified";
    @Deprecated
    public static final String COLLEGE_PROPERTY = "college";
    @Deprecated
    public static final String TAG_PROPERTY = "tag";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Boolean> ALLOWS_MULTIPLE_TAGS = new Property<Boolean>("allowsMultipleTags");
    public static final Property<Long> ANGEL_ID = new Property<Long>("angelId");
    public static final Property<Date> CREATED = new Property<Date>("created");
    public static final Property<String> ENTITY_IDENTIFIER = new Property<String>("entityIdentifier");
    public static final Property<Boolean> IS_REQUIRED = new Property<Boolean>("isRequired");
    public static final Property<Date> MODIFIED = new Property<Date>("modified");
    public static final Property<College> COLLEGE = new Property<College>("college");
    public static final Property<Tag> TAG = new Property<Tag>("tag");

    public void setAllowsMultipleTags(Boolean allowsMultipleTags) {
        writeProperty("allowsMultipleTags", allowsMultipleTags);
    }
    public Boolean getAllowsMultipleTags() {
        return (Boolean)readProperty("allowsMultipleTags");
    }

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setEntityIdentifier(String entityIdentifier) {
        writeProperty("entityIdentifier", entityIdentifier);
    }
    public String getEntityIdentifier() {
        return (String)readProperty("entityIdentifier");
    }

    public void setIsRequired(Boolean isRequired) {
        writeProperty("isRequired", isRequired);
    }
    public Boolean getIsRequired() {
        return (Boolean)readProperty("isRequired");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void setTag(Tag tag) {
        setToOneTarget("tag", tag, true);
    }

    public Tag getTag() {
        return (Tag)readProperty("tag");
    }


}
