package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.common.types.NodeSpecialType;
import ish.oncourse.model.College;
import ish.oncourse.model.Tag;
import ish.oncourse.model.TagGroupRequirement;
import ish.oncourse.model.TaggableTag;

/**
 * Class _Tag was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Tag extends CayenneDataObject {

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String DETAIL_PROPERTY = "detail";
    public static final String DETAIL_TEXTILE_PROPERTY = "detailTextile";
    public static final String IS_TAG_GROUP_PROPERTY = "isTagGroup";
    public static final String IS_WEB_VISIBLE_PROPERTY = "isWebVisible";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String NODE_TYPE_PROPERTY = "nodeType";
    public static final String SHORT_NAME_PROPERTY = "shortName";
    public static final String SPECIAL_TYPE_PROPERTY = "specialType";
    public static final String WEIGHTING_PROPERTY = "weighting";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String PARENT_PROPERTY = "parent";
    public static final String TAG_GROUP_REQUIREMENTS_PROPERTY = "tagGroupRequirements";
    public static final String TAGGABLE_TAGS_PROPERTY = "taggableTags";
    public static final String TAGS_PROPERTY = "tags";

    public static final String ID_PK_COLUMN = "id";

    public void setAngelId(Long angelId) {
        writeProperty(ANGEL_ID_PROPERTY, angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty(ANGEL_ID_PROPERTY);
    }

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setDetail(String detail) {
        writeProperty(DETAIL_PROPERTY, detail);
    }
    public String getDetail() {
        return (String)readProperty(DETAIL_PROPERTY);
    }

    public void setDetailTextile(String detailTextile) {
        writeProperty(DETAIL_TEXTILE_PROPERTY, detailTextile);
    }
    public String getDetailTextile() {
        return (String)readProperty(DETAIL_TEXTILE_PROPERTY);
    }

    public void setIsTagGroup(Boolean isTagGroup) {
        writeProperty(IS_TAG_GROUP_PROPERTY, isTagGroup);
    }
    public Boolean getIsTagGroup() {
        return (Boolean)readProperty(IS_TAG_GROUP_PROPERTY);
    }

    public void setIsWebVisible(Boolean isWebVisible) {
        writeProperty(IS_WEB_VISIBLE_PROPERTY, isWebVisible);
    }
    public Boolean getIsWebVisible() {
        return (Boolean)readProperty(IS_WEB_VISIBLE_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setNodeType(Integer nodeType) {
        writeProperty(NODE_TYPE_PROPERTY, nodeType);
    }
    public Integer getNodeType() {
        return (Integer)readProperty(NODE_TYPE_PROPERTY);
    }

    public void setShortName(String shortName) {
        writeProperty(SHORT_NAME_PROPERTY, shortName);
    }
    public String getShortName() {
        return (String)readProperty(SHORT_NAME_PROPERTY);
    }

    public void setSpecialType(NodeSpecialType specialType) {
        writeProperty(SPECIAL_TYPE_PROPERTY, specialType);
    }
    public NodeSpecialType getSpecialType() {
        return (NodeSpecialType)readProperty(SPECIAL_TYPE_PROPERTY);
    }

    public void setWeighting(Integer weighting) {
        writeProperty(WEIGHTING_PROPERTY, weighting);
    }
    public Integer getWeighting() {
        return (Integer)readProperty(WEIGHTING_PROPERTY);
    }

    public void setCollege(College college) {
        setToOneTarget(COLLEGE_PROPERTY, college, true);
    }

    public College getCollege() {
        return (College)readProperty(COLLEGE_PROPERTY);
    }


    public void setParent(Tag parent) {
        setToOneTarget(PARENT_PROPERTY, parent, true);
    }

    public Tag getParent() {
        return (Tag)readProperty(PARENT_PROPERTY);
    }


    public void addToTagGroupRequirements(TagGroupRequirement obj) {
        addToManyTarget(TAG_GROUP_REQUIREMENTS_PROPERTY, obj, true);
    }
    public void removeFromTagGroupRequirements(TagGroupRequirement obj) {
        removeToManyTarget(TAG_GROUP_REQUIREMENTS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TagGroupRequirement> getTagGroupRequirements() {
        return (List<TagGroupRequirement>)readProperty(TAG_GROUP_REQUIREMENTS_PROPERTY);
    }


    public void addToTaggableTags(TaggableTag obj) {
        addToManyTarget(TAGGABLE_TAGS_PROPERTY, obj, true);
    }
    public void removeFromTaggableTags(TaggableTag obj) {
        removeToManyTarget(TAGGABLE_TAGS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TaggableTag> getTaggableTags() {
        return (List<TaggableTag>)readProperty(TAGGABLE_TAGS_PROPERTY);
    }


    public void addToTags(Tag obj) {
        addToManyTarget(TAGS_PROPERTY, obj, true);
    }
    public void removeFromTags(Tag obj) {
        removeToManyTarget(TAGS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Tag> getTags() {
        return (List<Tag>)readProperty(TAGS_PROPERTY);
    }


}
