package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.Attendance;
import ish.oncourse.model.College;
import ish.oncourse.model.Contact;
import ish.oncourse.model.MessagePerson;
import ish.oncourse.model.Session;
import ish.oncourse.model.SessionTutor;
import ish.oncourse.model.TutorRole;

/**
 * Class _Tutor was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Tutor extends CayenneDataObject {

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String FINISH_DATE_PROPERTY = "finishDate";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String RESUME_PROPERTY = "resume";
    public static final String RESUME_TEXTILE_PROPERTY = "resumeTextile";
    public static final String START_DATE_PROPERTY = "startDate";
    public static final String ATTENDANCES_PROPERTY = "attendances";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String CONTACT_PROPERTY = "contact";
    public static final String MESSAGE_PEOPLE_PROPERTY = "messagePeople";
    public static final String SESSION_TUTORS_PROPERTY = "sessionTutors";
    public static final String SESSIONS_PROPERTY = "sessions";
    public static final String TUTOR_ROLES_PROPERTY = "tutorRoles";

    public static final String ID_PK_COLUMN = "id";

    public void setAngelId(Long angelId) {
        writeProperty(ANGEL_ID_PROPERTY, angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty(ANGEL_ID_PROPERTY);
    }

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setFinishDate(Date finishDate) {
        writeProperty(FINISH_DATE_PROPERTY, finishDate);
    }
    public Date getFinishDate() {
        return (Date)readProperty(FINISH_DATE_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setResume(String resume) {
        writeProperty(RESUME_PROPERTY, resume);
    }
    public String getResume() {
        return (String)readProperty(RESUME_PROPERTY);
    }

    public void setResumeTextile(String resumeTextile) {
        writeProperty(RESUME_TEXTILE_PROPERTY, resumeTextile);
    }
    public String getResumeTextile() {
        return (String)readProperty(RESUME_TEXTILE_PROPERTY);
    }

    public void setStartDate(Date startDate) {
        writeProperty(START_DATE_PROPERTY, startDate);
    }
    public Date getStartDate() {
        return (Date)readProperty(START_DATE_PROPERTY);
    }

    public void addToAttendances(Attendance obj) {
        addToManyTarget(ATTENDANCES_PROPERTY, obj, true);
    }
    public void removeFromAttendances(Attendance obj) {
        removeToManyTarget(ATTENDANCES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Attendance> getAttendances() {
        return (List<Attendance>)readProperty(ATTENDANCES_PROPERTY);
    }


    public void setCollege(College college) {
        setToOneTarget(COLLEGE_PROPERTY, college, true);
    }

    public College getCollege() {
        return (College)readProperty(COLLEGE_PROPERTY);
    }


    public void setContact(Contact contact) {
        setToOneTarget(CONTACT_PROPERTY, contact, true);
    }

    public Contact getContact() {
        return (Contact)readProperty(CONTACT_PROPERTY);
    }


    public void addToMessagePeople(MessagePerson obj) {
        addToManyTarget(MESSAGE_PEOPLE_PROPERTY, obj, true);
    }
    public void removeFromMessagePeople(MessagePerson obj) {
        removeToManyTarget(MESSAGE_PEOPLE_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MessagePerson> getMessagePeople() {
        return (List<MessagePerson>)readProperty(MESSAGE_PEOPLE_PROPERTY);
    }


    public void addToSessionTutors(SessionTutor obj) {
        addToManyTarget(SESSION_TUTORS_PROPERTY, obj, true);
    }
    public void removeFromSessionTutors(SessionTutor obj) {
        removeToManyTarget(SESSION_TUTORS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SessionTutor> getSessionTutors() {
        return (List<SessionTutor>)readProperty(SESSION_TUTORS_PROPERTY);
    }


    public void addToSessions(Session obj) {
        addToManyTarget(SESSIONS_PROPERTY, obj, true);
    }
    public void removeFromSessions(Session obj) {
        removeToManyTarget(SESSIONS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Session> getSessions() {
        return (List<Session>)readProperty(SESSIONS_PROPERTY);
    }


    public void addToTutorRoles(TutorRole obj) {
        addToManyTarget(TUTOR_ROLES_PROPERTY, obj, true);
    }
    public void removeFromTutorRoles(TutorRole obj) {
        removeToManyTarget(TUTOR_ROLES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TutorRole> getTutorRoles() {
        return (List<TutorRole>)readProperty(TUTOR_ROLES_PROPERTY);
    }


}
