package ish.oncourse.model.auto;

import ish.common.types.VoucherPaymentStatus;
import ish.oncourse.model.College;
import ish.oncourse.model.InvoiceLine;
import ish.oncourse.model.PaymentIn;
import ish.oncourse.model.Voucher;
import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import java.util.Date;

/**
 * Class _VoucherPaymentIn was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _VoucherPaymentIn extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String ANGEL_ID_PROPERTY = "angelId";
    @Deprecated
    public static final String CREATED_PROPERTY = "created";
    @Deprecated
    public static final String ENROLMENTS_COUNT_PROPERTY = "enrolmentsCount";
    @Deprecated
    public static final String MODIFIED_PROPERTY = "modified";
    @Deprecated
    public static final String STATUS_PROPERTY = "status";
    @Deprecated
    public static final String COLLEGE_PROPERTY = "college";
    @Deprecated
    public static final String INVOICE_LINE_PROPERTY = "invoiceLine";
    @Deprecated
    public static final String PAYMENT_PROPERTY = "payment";
    @Deprecated
    public static final String VOUCHER_PROPERTY = "voucher";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = new Property<Long>("angelId");
    public static final Property<Date> CREATED = new Property<Date>("created");
    public static final Property<Integer> ENROLMENTS_COUNT = new Property<Integer>("enrolmentsCount");
    public static final Property<Date> MODIFIED = new Property<Date>("modified");
    public static final Property<VoucherPaymentStatus> STATUS = new Property<VoucherPaymentStatus>("status");
    public static final Property<College> COLLEGE = new Property<College>("college");
    public static final Property<InvoiceLine> INVOICE_LINE = new Property<InvoiceLine>("invoiceLine");
    public static final Property<PaymentIn> PAYMENT = new Property<PaymentIn>("payment");
    public static final Property<Voucher> VOUCHER = new Property<Voucher>("voucher");

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setEnrolmentsCount(Integer enrolmentsCount) {
        writeProperty("enrolmentsCount", enrolmentsCount);
    }
    public Integer getEnrolmentsCount() {
        return (Integer)readProperty("enrolmentsCount");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setStatus(VoucherPaymentStatus status) {
        writeProperty("status", status);
    }
    public VoucherPaymentStatus getStatus() {
        return (VoucherPaymentStatus)readProperty("status");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void setInvoiceLine(InvoiceLine invoiceLine) {
        setToOneTarget("invoiceLine", invoiceLine, true);
    }

    public InvoiceLine getInvoiceLine() {
        return (InvoiceLine)readProperty("invoiceLine");
    }


    public void setPayment(PaymentIn payment) {
        setToOneTarget("payment", payment, true);
    }

    public PaymentIn getPayment() {
        return (PaymentIn)readProperty("payment");
    }


    public void setVoucher(Voucher voucher) {
        setToOneTarget("voucher", voucher, true);
    }

    public Voucher getVoucher() {
        return (Voucher)readProperty("voucher");
    }


    protected abstract void onPostAdd();

}
