package ish.oncourse.model.auto;

import java.util.List;

import org.apache.cayenne.exp.Property;

import ish.math.Money;
import ish.oncourse.model.Course;
import ish.oncourse.model.Product;

/**
 * Class _VoucherProduct was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _VoucherProduct extends Product {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String MAX_COURSES_REDEMPTION_PROPERTY = "maxCoursesRedemption";
    @Deprecated
    public static final String VALUE_PROPERTY = "value";
    @Deprecated
    public static final String REDEMPTION_COURSES_PROPERTY = "redemptionCourses";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Integer> MAX_COURSES_REDEMPTION = new Property<Integer>("maxCoursesRedemption");
    public static final Property<Money> VALUE = new Property<Money>("value");
    public static final Property<List<Course>> REDEMPTION_COURSES = new Property<List<Course>>("redemptionCourses");

    public void setMaxCoursesRedemption(Integer maxCoursesRedemption) {
        writeProperty("maxCoursesRedemption", maxCoursesRedemption);
    }
    public Integer getMaxCoursesRedemption() {
        return (Integer)readProperty("maxCoursesRedemption");
    }

    public void setValue(Money value) {
        writeProperty("value", value);
    }
    public Money getValue() {
        return (Money)readProperty("value");
    }

    public void addToRedemptionCourses(Course obj) {
        addToManyTarget("redemptionCourses", obj, true);
    }
    public void removeFromRedemptionCourses(Course obj) {
        removeToManyTarget("redemptionCourses", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Course> getRedemptionCourses() {
        return (List<Course>)readProperty("redemptionCourses");
    }


}
