package ish.oncourse.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import ish.common.types.VoucherPaymentStatus;
import ish.oncourse.model.College;
import ish.oncourse.model.InvoiceLine;
import ish.oncourse.model.PaymentIn;
import ish.oncourse.model.Voucher;

/**
 * Class _VoucherPaymentIn was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _VoucherPaymentIn extends CayenneDataObject {

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String ENROLMENTS_COUNT_PROPERTY = "enrolmentsCount";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String STATUS_PROPERTY = "status";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String INVOICE_LINE_PROPERTY = "invoiceLine";
    public static final String PAYMENT_PROPERTY = "payment";
    public static final String VOUCHER_PROPERTY = "voucher";

    public static final String ID_PK_COLUMN = "id";

    public void setAngelId(Long angelId) {
        writeProperty(ANGEL_ID_PROPERTY, angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty(ANGEL_ID_PROPERTY);
    }

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setEnrolmentsCount(Integer enrolmentsCount) {
        writeProperty(ENROLMENTS_COUNT_PROPERTY, enrolmentsCount);
    }
    public Integer getEnrolmentsCount() {
        return (Integer)readProperty(ENROLMENTS_COUNT_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setStatus(VoucherPaymentStatus status) {
        writeProperty(STATUS_PROPERTY, status);
    }
    public VoucherPaymentStatus getStatus() {
        return (VoucherPaymentStatus)readProperty(STATUS_PROPERTY);
    }

    public void setCollege(College college) {
        setToOneTarget(COLLEGE_PROPERTY, college, true);
    }

    public College getCollege() {
        return (College)readProperty(COLLEGE_PROPERTY);
    }


    public void setInvoiceLine(InvoiceLine invoiceLine) {
        setToOneTarget(INVOICE_LINE_PROPERTY, invoiceLine, true);
    }

    public InvoiceLine getInvoiceLine() {
        return (InvoiceLine)readProperty(INVOICE_LINE_PROPERTY);
    }


    public void setPayment(PaymentIn payment) {
        setToOneTarget(PAYMENT_PROPERTY, payment, true);
    }

    public PaymentIn getPayment() {
        return (PaymentIn)readProperty(PAYMENT_PROPERTY);
    }


    public void setVoucher(Voucher voucher) {
        setToOneTarget(VOUCHER_PROPERTY, voucher, true);
    }

    public Voucher getVoucher() {
        return (Voucher)readProperty(VOUCHER_PROPERTY);
    }


}
