package ish.oncourse.model.auto;

import ish.common.types.ExpiryType;
import ish.math.Money;
import ish.oncourse.model.Product;

/**
 * Class _VoucherProduct was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _VoucherProduct extends Product {

    public static final String EXPIRY_DAYS_PROPERTY = "expiryDays";
    public static final String EXPIRY_TYPE_PROPERTY = "expiryType";
    public static final String MAX_COURSES_REDEMPTION_PROPERTY = "maxCoursesRedemption";
    public static final String VALUE_PROPERTY = "value";

    public static final String ID_PK_COLUMN = "id";

    public void setExpiryDays(Integer expiryDays) {
        writeProperty("expiryDays", expiryDays);
    }
    public Integer getExpiryDays() {
        return (Integer)readProperty("expiryDays");
    }

    public void setExpiryType(ExpiryType expiryType) {
        writeProperty("expiryType", expiryType);
    }
    public ExpiryType getExpiryType() {
        return (ExpiryType)readProperty("expiryType");
    }

    public void setMaxCoursesRedemption(Integer maxCoursesRedemption) {
        writeProperty("maxCoursesRedemption", maxCoursesRedemption);
    }
    public Integer getMaxCoursesRedemption() {
        return (Integer)readProperty("maxCoursesRedemption");
    }

    public void setValue(Money value) {
        writeProperty("value", value);
    }
    public Money getValue() {
        return (Money)readProperty("value");
    }

}
