package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.College;
import ish.oncourse.model.Course;
import ish.oncourse.model.Student;
import ish.oncourse.model.WaitingListSite;

/**
 * Class _WaitingList was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WaitingList extends CayenneDataObject {

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String DETAIL_PROPERTY = "detail";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String POTENTIAL_STUDENTS_PROPERTY = "potentialStudents";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String COURSE_PROPERTY = "course";
    public static final String STUDENT_PROPERTY = "student";
    public static final String WAITING_LIST_SITES_PROPERTY = "waitingListSites";

    public static final String ID_PK_COLUMN = "id";

    public void setAngelId(Long angelId) {
        writeProperty(ANGEL_ID_PROPERTY, angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty(ANGEL_ID_PROPERTY);
    }

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setDetail(String detail) {
        writeProperty(DETAIL_PROPERTY, detail);
    }
    public String getDetail() {
        return (String)readProperty(DETAIL_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setPotentialStudents(Integer potentialStudents) {
        writeProperty(POTENTIAL_STUDENTS_PROPERTY, potentialStudents);
    }
    public Integer getPotentialStudents() {
        return (Integer)readProperty(POTENTIAL_STUDENTS_PROPERTY);
    }

    public void setCollege(College college) {
        setToOneTarget(COLLEGE_PROPERTY, college, true);
    }

    public College getCollege() {
        return (College)readProperty(COLLEGE_PROPERTY);
    }


    public void setCourse(Course course) {
        setToOneTarget(COURSE_PROPERTY, course, true);
    }

    public Course getCourse() {
        return (Course)readProperty(COURSE_PROPERTY);
    }


    public void setStudent(Student student) {
        setToOneTarget(STUDENT_PROPERTY, student, true);
    }

    public Student getStudent() {
        return (Student)readProperty(STUDENT_PROPERTY);
    }


    public void addToWaitingListSites(WaitingListSite obj) {
        addToManyTarget(WAITING_LIST_SITES_PROPERTY, obj, true);
    }
    public void removeFromWaitingListSites(WaitingListSite obj) {
        removeToManyTarget(WAITING_LIST_SITES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WaitingListSite> getWaitingListSites() {
        return (List<WaitingListSite>)readProperty(WAITING_LIST_SITES_PROPERTY);
    }


}
