package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.WebContentVisibility;
import ish.oncourse.model.WebMenu;
import ish.oncourse.model.WebNodeType;
import ish.oncourse.model.WebSite;
import ish.oncourse.model.WebSiteVersion;
import ish.oncourse.model.WebUrlAlias;

/**
 * Class _WebNode was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WebNode extends CayenneDataObject {

    public static final String CREATED_PROPERTY = "created";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String NODE_NUMBER_PROPERTY = "nodeNumber";
    public static final String PUBLISHED_PROPERTY = "published";
    public static final String WEB_CONTENT_VISIBILITY_PROPERTY = "webContentVisibility";
    public static final String WEB_MENUS_PROPERTY = "webMenus";
    public static final String WEB_NODE_TYPE_PROPERTY = "webNodeType";
    public static final String WEB_SITE_PROPERTY = "webSite";
    public static final String WEB_SITE_VERSION_PROPERTY = "webSiteVersion";
    public static final String WEB_URL_ALIASES_PROPERTY = "webUrlAliases";

    public static final String ID_PK_COLUMN = "id";

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setNodeNumber(Integer nodeNumber) {
        writeProperty(NODE_NUMBER_PROPERTY, nodeNumber);
    }
    public Integer getNodeNumber() {
        return (Integer)readProperty(NODE_NUMBER_PROPERTY);
    }

    public void setPublished(boolean published) {
        writeProperty(PUBLISHED_PROPERTY, published);
    }
	public boolean isPublished() {
        Boolean value = (Boolean)readProperty(PUBLISHED_PROPERTY);
        return (value != null) ? value.booleanValue() : false;
    }

    public void addToWebContentVisibility(WebContentVisibility obj) {
        addToManyTarget(WEB_CONTENT_VISIBILITY_PROPERTY, obj, true);
    }
    public void removeFromWebContentVisibility(WebContentVisibility obj) {
        removeToManyTarget(WEB_CONTENT_VISIBILITY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebContentVisibility> getWebContentVisibility() {
        return (List<WebContentVisibility>)readProperty(WEB_CONTENT_VISIBILITY_PROPERTY);
    }


    public void addToWebMenus(WebMenu obj) {
        addToManyTarget(WEB_MENUS_PROPERTY, obj, true);
    }
    public void removeFromWebMenus(WebMenu obj) {
        removeToManyTarget(WEB_MENUS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebMenu> getWebMenus() {
        return (List<WebMenu>)readProperty(WEB_MENUS_PROPERTY);
    }


    public void setWebNodeType(WebNodeType webNodeType) {
        setToOneTarget(WEB_NODE_TYPE_PROPERTY, webNodeType, true);
    }

    public WebNodeType getWebNodeType() {
        return (WebNodeType)readProperty(WEB_NODE_TYPE_PROPERTY);
    }


    public void setWebSite(WebSite webSite) {
        setToOneTarget(WEB_SITE_PROPERTY, webSite, true);
    }

    public WebSite getWebSite() {
        return (WebSite)readProperty(WEB_SITE_PROPERTY);
    }


    public void setWebSiteVersion(WebSiteVersion webSiteVersion) {
        setToOneTarget(WEB_SITE_VERSION_PROPERTY, webSiteVersion, true);
    }

    public WebSiteVersion getWebSiteVersion() {
        return (WebSiteVersion)readProperty(WEB_SITE_VERSION_PROPERTY);
    }


    public void addToWebUrlAliases(WebUrlAlias obj) {
        addToManyTarget(WEB_URL_ALIASES_PROPERTY, obj, true);
    }
    public void removeFromWebUrlAliases(WebUrlAlias obj) {
        removeToManyTarget(WEB_URL_ALIASES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebUrlAlias> getWebUrlAliases() {
        return (List<WebUrlAlias>)readProperty(WEB_URL_ALIASES_PROPERTY);
    }


    protected abstract void onPostAdd();

    protected abstract void onPreUpdate();

}
