package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.WebMenu;
import ish.oncourse.model.WebNode;
import ish.oncourse.model.WebSite;
import ish.oncourse.model.WebSiteVersion;

/**
 * Class _WebMenu was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WebMenu extends CayenneDataObject {

    public static final String CREATED_PROPERTY = "created";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String URL_PROPERTY = "url";
    public static final String WEIGHT_PROPERTY = "weight";
    public static final String CHILDREN_MENUS_PROPERTY = "childrenMenus";
    public static final String PARENT_WEB_MENU_PROPERTY = "parentWebMenu";
    public static final String WEB_NODE_PROPERTY = "webNode";
    public static final String WEB_SITE_PROPERTY = "webSite";
    public static final String WEB_SITE_VERSION_PROPERTY = "webSiteVersion";

    public static final String ID_PK_COLUMN = "id";

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setUrl(String url) {
        writeProperty(URL_PROPERTY, url);
    }
    public String getUrl() {
        return (String)readProperty(URL_PROPERTY);
    }

    public void setWeight(Integer weight) {
        writeProperty(WEIGHT_PROPERTY, weight);
    }
    public Integer getWeight() {
        return (Integer)readProperty(WEIGHT_PROPERTY);
    }

    public void addToChildrenMenus(WebMenu obj) {
        addToManyTarget(CHILDREN_MENUS_PROPERTY, obj, true);
    }
    public void removeFromChildrenMenus(WebMenu obj) {
        removeToManyTarget(CHILDREN_MENUS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebMenu> getChildrenMenus() {
        return (List<WebMenu>)readProperty(CHILDREN_MENUS_PROPERTY);
    }


    public void setParentWebMenu(WebMenu parentWebMenu) {
        setToOneTarget(PARENT_WEB_MENU_PROPERTY, parentWebMenu, true);
    }

    public WebMenu getParentWebMenu() {
        return (WebMenu)readProperty(PARENT_WEB_MENU_PROPERTY);
    }


    public void setWebNode(WebNode webNode) {
        setToOneTarget(WEB_NODE_PROPERTY, webNode, true);
    }

    public WebNode getWebNode() {
        return (WebNode)readProperty(WEB_NODE_PROPERTY);
    }


    public void setWebSite(WebSite webSite) {
        setToOneTarget(WEB_SITE_PROPERTY, webSite, true);
    }

    public WebSite getWebSite() {
        return (WebSite)readProperty(WEB_SITE_PROPERTY);
    }


    public void setWebSiteVersion(WebSiteVersion webSiteVersion) {
        setToOneTarget(WEB_SITE_VERSION_PROPERTY, webSiteVersion, true);
    }

    public WebSiteVersion getWebSiteVersion() {
        return (WebSiteVersion)readProperty(WEB_SITE_VERSION_PROPERTY);
    }


    protected abstract void onPostAdd();

}
