package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.College;
import ish.oncourse.model.Invoice;
import ish.oncourse.model.LicenseFee;
import ish.oncourse.model.WebContent;
import ish.oncourse.model.WebHostName;
import ish.oncourse.model.WebMenu;
import ish.oncourse.model.WebNode;
import ish.oncourse.model.WebNodeType;
import ish.oncourse.model.WebUrlAlias;

/**
 * Class _WebSite was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WebSite extends CayenneDataObject {

    public static final String COURSES_ROOT_TAG_NAME_PROPERTY = "coursesRootTagName";
    public static final String CREATED_PROPERTY = "created";
    public static final String GOOGLE_ANALYTICS_ACCOUNT_PROPERTY = "googleAnalyticsAccount";
    public static final String GOOGLE_DIRECTIONS_FROM_PROPERTY = "googleDirectionsFrom";
    public static final String GOOGLE_TAGMANAGER_ACCOUNT_PROPERTY = "googleTagmanagerAccount";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String SITE_KEY_PROPERTY = "siteKey";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String COLLEGE_DOMAINS_PROPERTY = "collegeDomains";
    public static final String CONTENTS_PROPERTY = "contents";
    public static final String INVOICES_PROPERTY = "invoices";
    public static final String LICENSE_FEES_PROPERTY = "licenseFees";
    public static final String TO_WEB_HOST_NAME_PROPERTY = "toWebHostName";
    public static final String WEB_MENUS_PROPERTY = "webMenus";
    public static final String WEB_NODE_TYPES_PROPERTY = "webNodeTypes";
    public static final String WEB_NODES_PROPERTY = "webNodes";
    public static final String WEB_URL_ALIASES_PROPERTY = "webUrlAliases";

    public static final String ID_PK_COLUMN = "id";

    public void setCoursesRootTagName(String coursesRootTagName) {
        writeProperty("coursesRootTagName", coursesRootTagName);
    }
    public String getCoursesRootTagName() {
        return (String)readProperty("coursesRootTagName");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setGoogleAnalyticsAccount(String googleAnalyticsAccount) {
        writeProperty("googleAnalyticsAccount", googleAnalyticsAccount);
    }
    public String getGoogleAnalyticsAccount() {
        return (String)readProperty("googleAnalyticsAccount");
    }

    public void setGoogleDirectionsFrom(String googleDirectionsFrom) {
        writeProperty("googleDirectionsFrom", googleDirectionsFrom);
    }
    public String getGoogleDirectionsFrom() {
        return (String)readProperty("googleDirectionsFrom");
    }

    public void setGoogleTagmanagerAccount(String googleTagmanagerAccount) {
        writeProperty("googleTagmanagerAccount", googleTagmanagerAccount);
    }
    public String getGoogleTagmanagerAccount() {
        return (String)readProperty("googleTagmanagerAccount");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setSiteKey(String siteKey) {
        writeProperty("siteKey", siteKey);
    }
    public String getSiteKey() {
        return (String)readProperty("siteKey");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void addToCollegeDomains(WebHostName obj) {
        addToManyTarget("collegeDomains", obj, true);
    }
    public void removeFromCollegeDomains(WebHostName obj) {
        removeToManyTarget("collegeDomains", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebHostName> getCollegeDomains() {
        return (List<WebHostName>)readProperty("collegeDomains");
    }


    public void addToContents(WebContent obj) {
        addToManyTarget("contents", obj, true);
    }
    public void removeFromContents(WebContent obj) {
        removeToManyTarget("contents", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebContent> getContents() {
        return (List<WebContent>)readProperty("contents");
    }


    public void addToInvoices(Invoice obj) {
        addToManyTarget("invoices", obj, true);
    }
    public void removeFromInvoices(Invoice obj) {
        removeToManyTarget("invoices", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Invoice> getInvoices() {
        return (List<Invoice>)readProperty("invoices");
    }


    public void addToLicenseFees(LicenseFee obj) {
        addToManyTarget("licenseFees", obj, true);
    }
    public void removeFromLicenseFees(LicenseFee obj) {
        removeToManyTarget("licenseFees", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<LicenseFee> getLicenseFees() {
        return (List<LicenseFee>)readProperty("licenseFees");
    }


    public void setToWebHostName(WebHostName toWebHostName) {
        setToOneTarget("toWebHostName", toWebHostName, true);
    }

    public WebHostName getToWebHostName() {
        return (WebHostName)readProperty("toWebHostName");
    }


    public void addToWebMenus(WebMenu obj) {
        addToManyTarget("webMenus", obj, true);
    }
    public void removeFromWebMenus(WebMenu obj) {
        removeToManyTarget("webMenus", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebMenu> getWebMenus() {
        return (List<WebMenu>)readProperty("webMenus");
    }


    public void addToWebNodeTypes(WebNodeType obj) {
        addToManyTarget("webNodeTypes", obj, true);
    }
    public void removeFromWebNodeTypes(WebNodeType obj) {
        removeToManyTarget("webNodeTypes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebNodeType> getWebNodeTypes() {
        return (List<WebNodeType>)readProperty("webNodeTypes");
    }


    public void addToWebNodes(WebNode obj) {
        addToManyTarget("webNodes", obj, true);
    }
    public void removeFromWebNodes(WebNode obj) {
        removeToManyTarget("webNodes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebNode> getWebNodes() {
        return (List<WebNode>)readProperty("webNodes");
    }


    public void addToWebUrlAliases(WebUrlAlias obj) {
        addToManyTarget("webUrlAliases", obj, true);
    }
    public void removeFromWebUrlAliases(WebUrlAlias obj) {
        removeToManyTarget("webUrlAliases", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebUrlAlias> getWebUrlAliases() {
        return (List<WebUrlAlias>)readProperty("webUrlAliases");
    }


}
