package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.WebContentVisibility;
import ish.oncourse.model.WebNode;
import ish.oncourse.model.WebSite;
import ish.oncourse.model.WebSiteVersion;

/**
 * Class _WebNodeType was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WebNodeType extends CayenneDataObject {

    public static final String CREATED_PROPERTY = "created";
    public static final String LAYOUT_KEY_PROPERTY = "layoutKey";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String WEB_CONTENT_VISIBILITIES_PROPERTY = "webContentVisibilities";
    public static final String WEB_NODES_PROPERTY = "webNodes";
    public static final String WEB_SITE_PROPERTY = "webSite";
    public static final String WEB_SITE_VERSION_PROPERTY = "webSiteVersion";

    public static final String ID_PK_COLUMN = "id";

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setLayoutKey(String layoutKey) {
        writeProperty(LAYOUT_KEY_PROPERTY, layoutKey);
    }
    public String getLayoutKey() {
        return (String)readProperty(LAYOUT_KEY_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToWebContentVisibilities(WebContentVisibility obj) {
        addToManyTarget(WEB_CONTENT_VISIBILITIES_PROPERTY, obj, true);
    }
    public void removeFromWebContentVisibilities(WebContentVisibility obj) {
        removeToManyTarget(WEB_CONTENT_VISIBILITIES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebContentVisibility> getWebContentVisibilities() {
        return (List<WebContentVisibility>)readProperty(WEB_CONTENT_VISIBILITIES_PROPERTY);
    }


    public void addToWebNodes(WebNode obj) {
        addToManyTarget(WEB_NODES_PROPERTY, obj, true);
    }
    public void removeFromWebNodes(WebNode obj) {
        removeToManyTarget(WEB_NODES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebNode> getWebNodes() {
        return (List<WebNode>)readProperty(WEB_NODES_PROPERTY);
    }


    public void setWebSite(WebSite webSite) {
        setToOneTarget(WEB_SITE_PROPERTY, webSite, true);
    }

    public WebSite getWebSite() {
        return (WebSite)readProperty(WEB_SITE_PROPERTY);
    }


    public void setWebSiteVersion(WebSiteVersion webSiteVersion) {
        setToOneTarget(WEB_SITE_VERSION_PROPERTY, webSiteVersion, true);
    }

    public WebSiteVersion getWebSiteVersion() {
        return (WebSiteVersion)readProperty(WEB_SITE_VERSION_PROPERTY);
    }


    protected abstract void onPostAdd();

}
