cd ../../common/trunk/
mvn versions:update-parent
cd ../../asset/trunk/
mvn versions:update-parent
cd ../../search/trunk/
mvn versions:update-parent
cd ../../web/trunk/
mvn versions:update-parent
cd ../../cms/trunk/
mvn versions:update-parent
cd ../../enrol/trunk/
mvn versions:update-parent
cd ../../portal/trunk/
mvn versions:update-parent
cd ../../services/trunk/
mvn versions:update-parent