package ish.oncourse.model.auto;

import ish.oncourse.model.Product;

/**
 * Class _ArticleProduct was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ArticleProduct extends Product {

    private static final long serialVersionUID = 1L; 


    public static final String ID_PK_COLUMN = "id";


}
