package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.exp.Property;

import ish.oncourse.model.Assessment;
import ish.oncourse.model.AssessmentClassModule;
import ish.oncourse.model.AssessmentClassTutor;
import ish.oncourse.model.AssessmentSubmission;
import ish.oncourse.model.College;
import ish.oncourse.model.CourseClass;

/**
 * Class _AssessmentClass was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AssessmentClass extends WillowCayenneObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String DUE_DATE_PROPERTY = "dueDate";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String RELEASE_DATE_PROPERTY = "releaseDate";
    public static final String ASSESSMENT_PROPERTY = "assessment";
    public static final String ASSESSMENT_CLASS_MODULES_PROPERTY = "assessmentClassModules";
    public static final String ASSESSMENT_CLASS_TUTORS_PROPERTY = "assessmentClassTutors";
    public static final String ASSESSMENT_SUBMISSIONS_PROPERTY = "assessmentSubmissions";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String COURSE_CLASS_PROPERTY = "courseClass";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = Property.create("angelId", Long.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<Date> DUE_DATE = Property.create("dueDate", Date.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<Date> RELEASE_DATE = Property.create("releaseDate", Date.class);
    public static final Property<Assessment> ASSESSMENT = Property.create("assessment", Assessment.class);
    public static final Property<List<AssessmentClassModule>> ASSESSMENT_CLASS_MODULES = Property.create("assessmentClassModules", List.class);
    public static final Property<List<AssessmentClassTutor>> ASSESSMENT_CLASS_TUTORS = Property.create("assessmentClassTutors", List.class);
    public static final Property<List<AssessmentSubmission>> ASSESSMENT_SUBMISSIONS = Property.create("assessmentSubmissions", List.class);
    public static final Property<College> COLLEGE = Property.create("college", College.class);
    public static final Property<CourseClass> COURSE_CLASS = Property.create("courseClass", CourseClass.class);

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setDueDate(Date dueDate) {
        writeProperty("dueDate", dueDate);
    }
    public Date getDueDate() {
        return (Date)readProperty("dueDate");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setReleaseDate(Date releaseDate) {
        writeProperty("releaseDate", releaseDate);
    }
    public Date getReleaseDate() {
        return (Date)readProperty("releaseDate");
    }

    public void setAssessment(Assessment assessment) {
        setToOneTarget("assessment", assessment, true);
    }

    public Assessment getAssessment() {
        return (Assessment)readProperty("assessment");
    }


    public void addToAssessmentClassModules(AssessmentClassModule obj) {
        addToManyTarget("assessmentClassModules", obj, true);
    }
    public void removeFromAssessmentClassModules(AssessmentClassModule obj) {
        removeToManyTarget("assessmentClassModules", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AssessmentClassModule> getAssessmentClassModules() {
        return (List<AssessmentClassModule>)readProperty("assessmentClassModules");
    }


    public void addToAssessmentClassTutors(AssessmentClassTutor obj) {
        addToManyTarget("assessmentClassTutors", obj, true);
    }
    public void removeFromAssessmentClassTutors(AssessmentClassTutor obj) {
        removeToManyTarget("assessmentClassTutors", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AssessmentClassTutor> getAssessmentClassTutors() {
        return (List<AssessmentClassTutor>)readProperty("assessmentClassTutors");
    }


    public void addToAssessmentSubmissions(AssessmentSubmission obj) {
        addToManyTarget("assessmentSubmissions", obj, true);
    }
    public void removeFromAssessmentSubmissions(AssessmentSubmission obj) {
        removeToManyTarget("assessmentSubmissions", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AssessmentSubmission> getAssessmentSubmissions() {
        return (List<AssessmentSubmission>)readProperty("assessmentSubmissions");
    }


    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void setCourseClass(CourseClass courseClass) {
        setToOneTarget("courseClass", courseClass, true);
    }

    public CourseClass getCourseClass() {
        return (CourseClass)readProperty("courseClass");
    }


}
