package ish.oncourse.model.auto;

import java.util.Date;

import org.apache.cayenne.exp.Property;

import ish.common.types.AttachmentSpecialType;
import ish.oncourse.model.BinaryInfo;
import ish.oncourse.model.College;
import ish.oncourse.model.Document;
import ish.oncourse.model.DocumentVersion;

/**
 * Class _BinaryInfoRelation was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BinaryInfoRelation extends WillowCayenneObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String ENTITY_ANGEL_ID_PROPERTY = "entityAngelId";
    public static final String ENTITY_IDENTIFIER_PROPERTY = "entityIdentifier";
    public static final String ENTITY_WILLOW_ID_PROPERTY = "entityWillowId";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String SPECIAL_TYPE_PROPERTY = "specialType";
    public static final String BINARY_INFO_PROPERTY = "binaryInfo";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String DOCUMENT_PROPERTY = "document";
    public static final String DOCUMENT_VERSION_PROPERTY = "documentVersion";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = Property.create("angelId", Long.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<Long> ENTITY_ANGEL_ID = Property.create("entityAngelId", Long.class);
    public static final Property<String> ENTITY_IDENTIFIER = Property.create("entityIdentifier", String.class);
    public static final Property<Long> ENTITY_WILLOW_ID = Property.create("entityWillowId", Long.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<AttachmentSpecialType> SPECIAL_TYPE = Property.create("specialType", AttachmentSpecialType.class);
    public static final Property<BinaryInfo> BINARY_INFO = Property.create("binaryInfo", BinaryInfo.class);
    public static final Property<College> COLLEGE = Property.create("college", College.class);
    public static final Property<Document> DOCUMENT = Property.create("document", Document.class);
    public static final Property<DocumentVersion> DOCUMENT_VERSION = Property.create("documentVersion", DocumentVersion.class);

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setEntityAngelId(Long entityAngelId) {
        writeProperty("entityAngelId", entityAngelId);
    }
    public Long getEntityAngelId() {
        return (Long)readProperty("entityAngelId");
    }

    public void setEntityIdentifier(String entityIdentifier) {
        writeProperty("entityIdentifier", entityIdentifier);
    }
    public String getEntityIdentifier() {
        return (String)readProperty("entityIdentifier");
    }

    public void setEntityWillowId(Long entityWillowId) {
        writeProperty("entityWillowId", entityWillowId);
    }
    public Long getEntityWillowId() {
        return (Long)readProperty("entityWillowId");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setSpecialType(AttachmentSpecialType specialType) {
        writeProperty("specialType", specialType);
    }
    public AttachmentSpecialType getSpecialType() {
        return (AttachmentSpecialType)readProperty("specialType");
    }

    public void setBinaryInfo(BinaryInfo binaryInfo) {
        setToOneTarget("binaryInfo", binaryInfo, true);
    }

    public BinaryInfo getBinaryInfo() {
        return (BinaryInfo)readProperty("binaryInfo");
    }


    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void setDocument(Document document) {
        setToOneTarget("document", document, true);
    }

    public Document getDocument() {
        return (Document)readProperty("document");
    }


    public void setDocumentVersion(DocumentVersion documentVersion) {
        setToOneTarget("documentVersion", documentVersion, true);
    }

    public DocumentVersion getDocumentVersion() {
        return (DocumentVersion)readProperty("documentVersion");
    }


}
