package ish.oncourse.model.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Date;

import org.apache.cayenne.exp.Property;

import ish.oncourse.model.College;
import ish.oncourse.model.Contact;
import ish.oncourse.model.ContactRelationType;

/**
 * Class _ContactRelation was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ContactRelation extends WillowCayenneObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String FROM_CONTACT_PROPERTY = "fromContact";
    public static final String RELATION_TYPE_PROPERTY = "relationType";
    public static final String TO_CONTACT_PROPERTY = "toContact";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = Property.create("angelId", Long.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<College> COLLEGE = Property.create("college", College.class);
    public static final Property<Contact> FROM_CONTACT = Property.create("fromContact", Contact.class);
    public static final Property<ContactRelationType> RELATION_TYPE = Property.create("relationType", ContactRelationType.class);
    public static final Property<Contact> TO_CONTACT = Property.create("toContact", Contact.class);

    protected Long angelId;
    protected Date created;
    protected Date modified;

    protected Object college;
    protected Object fromContact;
    protected Object relationType;
    protected Object toContact;

    public void setAngelId(Long angelId) {
        beforePropertyWrite("angelId", this.angelId, angelId);
        this.angelId = angelId;
    }

    public Long getAngelId() {
        beforePropertyRead("angelId");
        return this.angelId;
    }

    public void setCreated(Date created) {
        beforePropertyWrite("created", this.created, created);
        this.created = created;
    }

    public Date getCreated() {
        beforePropertyRead("created");
        return this.created;
    }

    public void setModified(Date modified) {
        beforePropertyWrite("modified", this.modified, modified);
        this.modified = modified;
    }

    public Date getModified() {
        beforePropertyRead("modified");
        return this.modified;
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }

    public void setFromContact(Contact fromContact) {
        setToOneTarget("fromContact", fromContact, true);
    }

    public Contact getFromContact() {
        return (Contact)readProperty("fromContact");
    }

    public void setRelationType(ContactRelationType relationType) {
        setToOneTarget("relationType", relationType, true);
    }

    public ContactRelationType getRelationType() {
        return (ContactRelationType)readProperty("relationType");
    }

    public void setToContact(Contact toContact) {
        setToOneTarget("toContact", toContact, true);
    }

    public Contact getToContact() {
        return (Contact)readProperty("toContact");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "angelId":
                return this.angelId;
            case "created":
                return this.created;
            case "modified":
                return this.modified;
            case "college":
                return this.college;
            case "fromContact":
                return this.fromContact;
            case "relationType":
                return this.relationType;
            case "toContact":
                return this.toContact;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "angelId":
                this.angelId = (Long)val;
                break;
            case "created":
                this.created = (Date)val;
                break;
            case "modified":
                this.modified = (Date)val;
                break;
            case "college":
                this.college = val;
                break;
            case "fromContact":
                this.fromContact = val;
                break;
            case "relationType":
                this.relationType = val;
                break;
            case "toContact":
                this.toContact = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.angelId);
        out.writeObject(this.created);
        out.writeObject(this.modified);
        out.writeObject(this.college);
        out.writeObject(this.fromContact);
        out.writeObject(this.relationType);
        out.writeObject(this.toContact);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.angelId = (Long)in.readObject();
        this.created = (Date)in.readObject();
        this.modified = (Date)in.readObject();
        this.college = in.readObject();
        this.fromContact = in.readObject();
        this.relationType = in.readObject();
        this.toContact = in.readObject();
    }

}
