package ish.oncourse.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import ish.common.types.ContactDuplicateStatus;
import ish.oncourse.model.College;
import ish.oncourse.model.Contact;
import ish.oncourse.model.SystemUser;

/**
 * Class _ContactDuplicate was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ContactDuplicate extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CONTACT_TO_DELETE_ANGEL_ID_PROPERTY = "contactToDeleteAngelId";
    public static final String CONTACT_TO_DELETE_ID_PROPERTY = "contactToDeleteId";
    public static final String CREATED_PROPERTY = "created";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String STATUS_PROPERTY = "status";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String CONTACT_TO_UPDATE_PROPERTY = "contactToUpdate";
    public static final String CREATED_BY_USER_PROPERTY = "createdByUser";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = Property.create("angelId", Long.class);
    public static final Property<Long> CONTACT_TO_DELETE_ANGEL_ID = Property.create("contactToDeleteAngelId", Long.class);
    public static final Property<Long> CONTACT_TO_DELETE_ID = Property.create("contactToDeleteId", Long.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<String> DESCRIPTION = Property.create("description", String.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<ContactDuplicateStatus> STATUS = Property.create("status", ContactDuplicateStatus.class);
    public static final Property<College> COLLEGE = Property.create("college", College.class);
    public static final Property<Contact> CONTACT_TO_UPDATE = Property.create("contactToUpdate", Contact.class);
    public static final Property<SystemUser> CREATED_BY_USER = Property.create("createdByUser", SystemUser.class);

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setContactToDeleteAngelId(Long contactToDeleteAngelId) {
        writeProperty("contactToDeleteAngelId", contactToDeleteAngelId);
    }
    public Long getContactToDeleteAngelId() {
        return (Long)readProperty("contactToDeleteAngelId");
    }

    public void setContactToDeleteId(Long contactToDeleteId) {
        writeProperty("contactToDeleteId", contactToDeleteId);
    }
    public Long getContactToDeleteId() {
        return (Long)readProperty("contactToDeleteId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setStatus(ContactDuplicateStatus status) {
        writeProperty("status", status);
    }
    public ContactDuplicateStatus getStatus() {
        return (ContactDuplicateStatus)readProperty("status");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void setContactToUpdate(Contact contactToUpdate) {
        setToOneTarget("contactToUpdate", contactToUpdate, true);
    }

    public Contact getContactToUpdate() {
        return (Contact)readProperty("contactToUpdate");
    }


    public void setCreatedByUser(SystemUser createdByUser) {
        setToOneTarget("createdByUser", createdByUser, true);
    }

    public SystemUser getCreatedByUser() {
        return (SystemUser)readProperty("createdByUser");
    }


}
