package ish.oncourse.model.auto;

import java.util.Date;

import org.apache.cayenne.exp.Property;

/**
 * Class _Country was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Country extends WillowCayenneObject {

    private static final long serialVersionUID = 1L; 

    public static final String ASCCSS_CODE_PROPERTY = "asccssCode";
    public static final String CREATED_PROPERTY = "created";
    public static final String ISH_VERSION_PROPERTY = "ishVersion";
    public static final String ISO_CODE_ALPHA2_PROPERTY = "isoCodeAlpha2";
    public static final String ISO_CODE_ALPHA3_PROPERTY = "isoCodeAlpha3";
    public static final String ISO_CODE_NUMERIC_PROPERTY = "isoCodeNumeric";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String SACC_CODE_PROPERTY = "saccCode";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> ASCCSS_CODE = Property.create("asccssCode", String.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<Long> ISH_VERSION = Property.create("ishVersion", Long.class);
    public static final Property<String> ISO_CODE_ALPHA2 = Property.create("isoCodeAlpha2", String.class);
    public static final Property<String> ISO_CODE_ALPHA3 = Property.create("isoCodeAlpha3", String.class);
    public static final Property<Integer> ISO_CODE_NUMERIC = Property.create("isoCodeNumeric", Integer.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<Integer> SACC_CODE = Property.create("saccCode", Integer.class);

    public void setAsccssCode(String asccssCode) {
        writeProperty("asccssCode", asccssCode);
    }
    public String getAsccssCode() {
        return (String)readProperty("asccssCode");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setIshVersion(Long ishVersion) {
        writeProperty("ishVersion", ishVersion);
    }
    public Long getIshVersion() {
        return (Long)readProperty("ishVersion");
    }

    public void setIsoCodeAlpha2(String isoCodeAlpha2) {
        writeProperty("isoCodeAlpha2", isoCodeAlpha2);
    }
    public String getIsoCodeAlpha2() {
        return (String)readProperty("isoCodeAlpha2");
    }

    public void setIsoCodeAlpha3(String isoCodeAlpha3) {
        writeProperty("isoCodeAlpha3", isoCodeAlpha3);
    }
    public String getIsoCodeAlpha3() {
        return (String)readProperty("isoCodeAlpha3");
    }

    public void setIsoCodeNumeric(Integer isoCodeNumeric) {
        writeProperty("isoCodeNumeric", isoCodeNumeric);
    }
    public Integer getIsoCodeNumeric() {
        return (Integer)readProperty("isoCodeNumeric");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setSaccCode(Integer saccCode) {
        writeProperty("saccCode", saccCode);
    }
    public Integer getSaccCode() {
        return (Integer)readProperty("saccCode");
    }

}
