package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import ish.common.types.AttachmentInfoVisibility;
import ish.oncourse.model.BinaryInfoRelation;
import ish.oncourse.model.College;
import ish.oncourse.model.DocumentVersion;

/**
 * Class _Document was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Document extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String FILE_UUID_PROPERTY = "fileUUID";
    public static final String IS_REMOVED_PROPERTY = "isRemoved";
    public static final String IS_SHARED_PROPERTY = "isShared";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String WEB_VISIBILITY_PROPERTY = "webVisibility";
    public static final String BINARY_INFO_RELATIONS_PROPERTY = "binaryInfoRelations";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String VERSIONS_PROPERTY = "versions";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = Property.create("angelId", Long.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<String> DESCRIPTION = Property.create("description", String.class);
    public static final Property<String> FILE_UUID = Property.create("fileUUID", String.class);
    public static final Property<Boolean> IS_REMOVED = Property.create("isRemoved", Boolean.class);
    public static final Property<Boolean> IS_SHARED = Property.create("isShared", Boolean.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<AttachmentInfoVisibility> WEB_VISIBILITY = Property.create("webVisibility", AttachmentInfoVisibility.class);
    public static final Property<List<BinaryInfoRelation>> BINARY_INFO_RELATIONS = Property.create("binaryInfoRelations", List.class);
    public static final Property<College> COLLEGE = Property.create("college", College.class);
    public static final Property<List<DocumentVersion>> VERSIONS = Property.create("versions", List.class);

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setFileUUID(String fileUUID) {
        writeProperty("fileUUID", fileUUID);
    }
    public String getFileUUID() {
        return (String)readProperty("fileUUID");
    }

    public void setIsRemoved(Boolean isRemoved) {
        writeProperty("isRemoved", isRemoved);
    }
    public Boolean getIsRemoved() {
        return (Boolean)readProperty("isRemoved");
    }

    public void setIsShared(Boolean isShared) {
        writeProperty("isShared", isShared);
    }
    public Boolean getIsShared() {
        return (Boolean)readProperty("isShared");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setWebVisibility(AttachmentInfoVisibility webVisibility) {
        writeProperty("webVisibility", webVisibility);
    }
    public AttachmentInfoVisibility getWebVisibility() {
        return (AttachmentInfoVisibility)readProperty("webVisibility");
    }

    public void addToBinaryInfoRelations(BinaryInfoRelation obj) {
        addToManyTarget("binaryInfoRelations", obj, true);
    }
    public void removeFromBinaryInfoRelations(BinaryInfoRelation obj) {
        removeToManyTarget("binaryInfoRelations", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<BinaryInfoRelation> getBinaryInfoRelations() {
        return (List<BinaryInfoRelation>)readProperty("binaryInfoRelations");
    }


    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void addToVersions(DocumentVersion obj) {
        addToManyTarget("versions", obj, true);
    }
    public void removeFromVersions(DocumentVersion obj) {
        removeToManyTarget("versions", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DocumentVersion> getVersions() {
        return (List<DocumentVersion>)readProperty("versions");
    }


}
