package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.exp.Property;

import ish.oncourse.model.BinaryInfoRelation;
import ish.oncourse.model.College;
import ish.oncourse.model.Document;
import ish.oncourse.model.SystemUser;

/**
 * Class _DocumentVersion was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DocumentVersion extends WillowCayenneObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String BYTE_SIZE_PROPERTY = "byteSize";
    public static final String CREATED_PROPERTY = "created";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String FILE_NAME_PROPERTY = "fileName";
    public static final String FILE_PATH_PROPERTY = "filePath";
    public static final String MIME_TYPE_PROPERTY = "mimeType";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String PIXEL_HEIGHT_PROPERTY = "pixelHeight";
    public static final String PIXEL_WIDTH_PROPERTY = "pixelWidth";
    public static final String THUMBNAIL_PROPERTY = "thumbnail";
    public static final String TIMESTAMP_PROPERTY = "timestamp";
    public static final String VERSION_ID_PROPERTY = "versionId";
    public static final String BINARY_INFO_RELATIONS_PROPERTY = "binaryInfoRelations";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String CREATED_BY_USER_PROPERTY = "createdByUser";
    public static final String DOCUMENT_PROPERTY = "document";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = Property.create("angelId", Long.class);
    public static final Property<Long> BYTE_SIZE = Property.create("byteSize", Long.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<String> DESCRIPTION = Property.create("description", String.class);
    public static final Property<String> FILE_NAME = Property.create("fileName", String.class);
    public static final Property<String> FILE_PATH = Property.create("filePath", String.class);
    public static final Property<String> MIME_TYPE = Property.create("mimeType", String.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<Integer> PIXEL_HEIGHT = Property.create("pixelHeight", Integer.class);
    public static final Property<Integer> PIXEL_WIDTH = Property.create("pixelWidth", Integer.class);
    public static final Property<byte[]> THUMBNAIL = Property.create("thumbnail", byte[].class);
    public static final Property<Date> TIMESTAMP = Property.create("timestamp", Date.class);
    public static final Property<String> VERSION_ID = Property.create("versionId", String.class);
    public static final Property<List<BinaryInfoRelation>> BINARY_INFO_RELATIONS = Property.create("binaryInfoRelations", List.class);
    public static final Property<College> COLLEGE = Property.create("college", College.class);
    public static final Property<SystemUser> CREATED_BY_USER = Property.create("createdByUser", SystemUser.class);
    public static final Property<Document> DOCUMENT = Property.create("document", Document.class);

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setByteSize(Long byteSize) {
        writeProperty("byteSize", byteSize);
    }
    public Long getByteSize() {
        return (Long)readProperty("byteSize");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setFileName(String fileName) {
        writeProperty("fileName", fileName);
    }
    public String getFileName() {
        return (String)readProperty("fileName");
    }

    public void setFilePath(String filePath) {
        writeProperty("filePath", filePath);
    }
    public String getFilePath() {
        return (String)readProperty("filePath");
    }

    public void setMimeType(String mimeType) {
        writeProperty("mimeType", mimeType);
    }
    public String getMimeType() {
        return (String)readProperty("mimeType");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setPixelHeight(Integer pixelHeight) {
        writeProperty("pixelHeight", pixelHeight);
    }
    public Integer getPixelHeight() {
        return (Integer)readProperty("pixelHeight");
    }

    public void setPixelWidth(Integer pixelWidth) {
        writeProperty("pixelWidth", pixelWidth);
    }
    public Integer getPixelWidth() {
        return (Integer)readProperty("pixelWidth");
    }

    public void setThumbnail(byte[] thumbnail) {
        writeProperty("thumbnail", thumbnail);
    }
    public byte[] getThumbnail() {
        return (byte[])readProperty("thumbnail");
    }

    public void setTimestamp(Date timestamp) {
        writeProperty("timestamp", timestamp);
    }
    public Date getTimestamp() {
        return (Date)readProperty("timestamp");
    }

    public void setVersionId(String versionId) {
        writeProperty("versionId", versionId);
    }
    public String getVersionId() {
        return (String)readProperty("versionId");
    }

    public void addToBinaryInfoRelations(BinaryInfoRelation obj) {
        addToManyTarget("binaryInfoRelations", obj, true);
    }
    public void removeFromBinaryInfoRelations(BinaryInfoRelation obj) {
        removeToManyTarget("binaryInfoRelations", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<BinaryInfoRelation> getBinaryInfoRelations() {
        return (List<BinaryInfoRelation>)readProperty("binaryInfoRelations");
    }


    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void setCreatedByUser(SystemUser createdByUser) {
        setToOneTarget("createdByUser", createdByUser, true);
    }

    public SystemUser getCreatedByUser() {
        return (SystemUser)readProperty("createdByUser");
    }


    public void setDocument(Document document) {
        setToOneTarget("document", document, true);
    }

    public Document getDocument() {
        return (Document)readProperty("document");
    }


}
