package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.exp.Property;

import ish.oncourse.model.College;
import ish.oncourse.model.Field;
import ish.oncourse.model.FieldConfigurationLink;
import ish.oncourse.model.FieldConfigurationScheme;
import ish.oncourse.model.FieldHeading;

/**
 * Class _FieldConfiguration was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FieldConfiguration extends WillowCayenneObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String INT_TYPE_PROPERTY = "intType";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String APPLICATION_FIELD_CONFIGURATION_SCHEMES_PROPERTY = "applicationFieldConfigurationSchemes";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String ENROL_FIELD_CONFIGURATION_SCHEMES_PROPERTY = "enrolFieldConfigurationSchemes";
    public static final String FIELD_CONFIGURATION_LINKS_PROPERTY = "fieldConfigurationLinks";
    public static final String FIELD_HEADINGS_PROPERTY = "fieldHeadings";
    public static final String FIELDS_PROPERTY = "fields";
    public static final String WAITING_LIST_FIELD_CONFIGURATION_SCHEMES_PROPERTY = "waitingListFieldConfigurationSchemes";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = Property.create("angelId", Long.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<Integer> INT_TYPE = Property.create("intType", Integer.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<List<FieldConfigurationScheme>> APPLICATION_FIELD_CONFIGURATION_SCHEMES = Property.create("applicationFieldConfigurationSchemes", List.class);
    public static final Property<College> COLLEGE = Property.create("college", College.class);
    public static final Property<List<FieldConfigurationScheme>> ENROL_FIELD_CONFIGURATION_SCHEMES = Property.create("enrolFieldConfigurationSchemes", List.class);
    public static final Property<List<FieldConfigurationLink>> FIELD_CONFIGURATION_LINKS = Property.create("fieldConfigurationLinks", List.class);
    public static final Property<List<FieldHeading>> FIELD_HEADINGS = Property.create("fieldHeadings", List.class);
    public static final Property<List<Field>> FIELDS = Property.create("fields", List.class);
    public static final Property<List<FieldConfigurationScheme>> WAITING_LIST_FIELD_CONFIGURATION_SCHEMES = Property.create("waitingListFieldConfigurationSchemes", List.class);

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setIntType(Integer intType) {
        writeProperty("intType", intType);
    }
    public Integer getIntType() {
        return (Integer)readProperty("intType");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToApplicationFieldConfigurationSchemes(FieldConfigurationScheme obj) {
        addToManyTarget("applicationFieldConfigurationSchemes", obj, true);
    }
    public void removeFromApplicationFieldConfigurationSchemes(FieldConfigurationScheme obj) {
        removeToManyTarget("applicationFieldConfigurationSchemes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<FieldConfigurationScheme> getApplicationFieldConfigurationSchemes() {
        return (List<FieldConfigurationScheme>)readProperty("applicationFieldConfigurationSchemes");
    }


    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void addToEnrolFieldConfigurationSchemes(FieldConfigurationScheme obj) {
        addToManyTarget("enrolFieldConfigurationSchemes", obj, true);
    }
    public void removeFromEnrolFieldConfigurationSchemes(FieldConfigurationScheme obj) {
        removeToManyTarget("enrolFieldConfigurationSchemes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<FieldConfigurationScheme> getEnrolFieldConfigurationSchemes() {
        return (List<FieldConfigurationScheme>)readProperty("enrolFieldConfigurationSchemes");
    }


    public void addToFieldConfigurationLinks(FieldConfigurationLink obj) {
        addToManyTarget("fieldConfigurationLinks", obj, true);
    }
    public void removeFromFieldConfigurationLinks(FieldConfigurationLink obj) {
        removeToManyTarget("fieldConfigurationLinks", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<FieldConfigurationLink> getFieldConfigurationLinks() {
        return (List<FieldConfigurationLink>)readProperty("fieldConfigurationLinks");
    }


    public void addToFieldHeadings(FieldHeading obj) {
        addToManyTarget("fieldHeadings", obj, true);
    }
    public void removeFromFieldHeadings(FieldHeading obj) {
        removeToManyTarget("fieldHeadings", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<FieldHeading> getFieldHeadings() {
        return (List<FieldHeading>)readProperty("fieldHeadings");
    }


    public void addToFields(Field obj) {
        addToManyTarget("fields", obj, true);
    }
    public void removeFromFields(Field obj) {
        removeToManyTarget("fields", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Field> getFields() {
        return (List<Field>)readProperty("fields");
    }


    public void addToWaitingListFieldConfigurationSchemes(FieldConfigurationScheme obj) {
        addToManyTarget("waitingListFieldConfigurationSchemes", obj, true);
    }
    public void removeFromWaitingListFieldConfigurationSchemes(FieldConfigurationScheme obj) {
        removeToManyTarget("waitingListFieldConfigurationSchemes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<FieldConfigurationScheme> getWaitingListFieldConfigurationSchemes() {
        return (List<FieldConfigurationScheme>)readProperty("waitingListFieldConfigurationSchemes");
    }


}
