package ish.oncourse.model.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.exp.Property;

import ish.oncourse.model.College;
import ish.oncourse.model.Field;
import ish.oncourse.model.FieldConfigurationLink;
import ish.oncourse.model.FieldConfigurationScheme;
import ish.oncourse.model.FieldHeading;
import ish.oncourse.model.SystemUser;

/**
 * Class _FieldConfiguration was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FieldConfiguration extends WillowCayenneObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String INT_TYPE_PROPERTY = "intType";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String APPLICATION_FIELD_CONFIGURATION_SCHEMES_PROPERTY = "applicationFieldConfigurationSchemes";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String CREATED_BY_PROPERTY = "createdBy";
    public static final String ENROL_FIELD_CONFIGURATION_SCHEMES_PROPERTY = "enrolFieldConfigurationSchemes";
    public static final String FIELD_CONFIGURATION_LINKS_PROPERTY = "fieldConfigurationLinks";
    public static final String FIELD_HEADINGS_PROPERTY = "fieldHeadings";
    public static final String FIELDS_PROPERTY = "fields";
    public static final String WAITING_LIST_FIELD_CONFIGURATION_SCHEMES_PROPERTY = "waitingListFieldConfigurationSchemes";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = Property.create("angelId", Long.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<Integer> INT_TYPE = Property.create("intType", Integer.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<List<FieldConfigurationScheme>> APPLICATION_FIELD_CONFIGURATION_SCHEMES = Property.create("applicationFieldConfigurationSchemes", List.class);
    public static final Property<College> COLLEGE = Property.create("college", College.class);
    public static final Property<SystemUser> CREATED_BY = Property.create("createdBy", SystemUser.class);
    public static final Property<List<FieldConfigurationScheme>> ENROL_FIELD_CONFIGURATION_SCHEMES = Property.create("enrolFieldConfigurationSchemes", List.class);
    public static final Property<List<FieldConfigurationLink>> FIELD_CONFIGURATION_LINKS = Property.create("fieldConfigurationLinks", List.class);
    public static final Property<List<FieldHeading>> FIELD_HEADINGS = Property.create("fieldHeadings", List.class);
    public static final Property<List<Field>> FIELDS = Property.create("fields", List.class);
    public static final Property<List<FieldConfigurationScheme>> WAITING_LIST_FIELD_CONFIGURATION_SCHEMES = Property.create("waitingListFieldConfigurationSchemes", List.class);

    protected Long angelId;
    protected Date created;
    protected Integer intType;
    protected Date modified;
    protected String name;

    protected Object applicationFieldConfigurationSchemes;
    protected Object college;
    protected Object createdBy;
    protected Object enrolFieldConfigurationSchemes;
    protected Object fieldConfigurationLinks;
    protected Object fieldHeadings;
    protected Object fields;
    protected Object waitingListFieldConfigurationSchemes;

    public void setAngelId(Long angelId) {
        beforePropertyWrite("angelId", this.angelId, angelId);
        this.angelId = angelId;
    }

    public Long getAngelId() {
        beforePropertyRead("angelId");
        return this.angelId;
    }

    public void setCreated(Date created) {
        beforePropertyWrite("created", this.created, created);
        this.created = created;
    }

    public Date getCreated() {
        beforePropertyRead("created");
        return this.created;
    }

    public void setIntType(Integer intType) {
        beforePropertyWrite("intType", this.intType, intType);
        this.intType = intType;
    }

    public Integer getIntType() {
        beforePropertyRead("intType");
        return this.intType;
    }

    public void setModified(Date modified) {
        beforePropertyWrite("modified", this.modified, modified);
        this.modified = modified;
    }

    public Date getModified() {
        beforePropertyRead("modified");
        return this.modified;
    }

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String getName() {
        beforePropertyRead("name");
        return this.name;
    }

    public void addToApplicationFieldConfigurationSchemes(FieldConfigurationScheme obj) {
        addToManyTarget("applicationFieldConfigurationSchemes", obj, true);
    }

    public void removeFromApplicationFieldConfigurationSchemes(FieldConfigurationScheme obj) {
        removeToManyTarget("applicationFieldConfigurationSchemes", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<FieldConfigurationScheme> getApplicationFieldConfigurationSchemes() {
        return (List<FieldConfigurationScheme>)readProperty("applicationFieldConfigurationSchemes");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }

    public void setCreatedBy(SystemUser createdBy) {
        setToOneTarget("createdBy", createdBy, true);
    }

    public SystemUser getCreatedBy() {
        return (SystemUser)readProperty("createdBy");
    }

    public void addToEnrolFieldConfigurationSchemes(FieldConfigurationScheme obj) {
        addToManyTarget("enrolFieldConfigurationSchemes", obj, true);
    }

    public void removeFromEnrolFieldConfigurationSchemes(FieldConfigurationScheme obj) {
        removeToManyTarget("enrolFieldConfigurationSchemes", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<FieldConfigurationScheme> getEnrolFieldConfigurationSchemes() {
        return (List<FieldConfigurationScheme>)readProperty("enrolFieldConfigurationSchemes");
    }

    public void addToFieldConfigurationLinks(FieldConfigurationLink obj) {
        addToManyTarget("fieldConfigurationLinks", obj, true);
    }

    public void removeFromFieldConfigurationLinks(FieldConfigurationLink obj) {
        removeToManyTarget("fieldConfigurationLinks", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<FieldConfigurationLink> getFieldConfigurationLinks() {
        return (List<FieldConfigurationLink>)readProperty("fieldConfigurationLinks");
    }

    public void addToFieldHeadings(FieldHeading obj) {
        addToManyTarget("fieldHeadings", obj, true);
    }

    public void removeFromFieldHeadings(FieldHeading obj) {
        removeToManyTarget("fieldHeadings", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<FieldHeading> getFieldHeadings() {
        return (List<FieldHeading>)readProperty("fieldHeadings");
    }

    public void addToFields(Field obj) {
        addToManyTarget("fields", obj, true);
    }

    public void removeFromFields(Field obj) {
        removeToManyTarget("fields", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Field> getFields() {
        return (List<Field>)readProperty("fields");
    }

    public void addToWaitingListFieldConfigurationSchemes(FieldConfigurationScheme obj) {
        addToManyTarget("waitingListFieldConfigurationSchemes", obj, true);
    }

    public void removeFromWaitingListFieldConfigurationSchemes(FieldConfigurationScheme obj) {
        removeToManyTarget("waitingListFieldConfigurationSchemes", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<FieldConfigurationScheme> getWaitingListFieldConfigurationSchemes() {
        return (List<FieldConfigurationScheme>)readProperty("waitingListFieldConfigurationSchemes");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "angelId":
                return this.angelId;
            case "created":
                return this.created;
            case "intType":
                return this.intType;
            case "modified":
                return this.modified;
            case "name":
                return this.name;
            case "applicationFieldConfigurationSchemes":
                return this.applicationFieldConfigurationSchemes;
            case "college":
                return this.college;
            case "createdBy":
                return this.createdBy;
            case "enrolFieldConfigurationSchemes":
                return this.enrolFieldConfigurationSchemes;
            case "fieldConfigurationLinks":
                return this.fieldConfigurationLinks;
            case "fieldHeadings":
                return this.fieldHeadings;
            case "fields":
                return this.fields;
            case "waitingListFieldConfigurationSchemes":
                return this.waitingListFieldConfigurationSchemes;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "angelId":
                this.angelId = (Long)val;
                break;
            case "created":
                this.created = (Date)val;
                break;
            case "intType":
                this.intType = (Integer)val;
                break;
            case "modified":
                this.modified = (Date)val;
                break;
            case "name":
                this.name = (String)val;
                break;
            case "applicationFieldConfigurationSchemes":
                this.applicationFieldConfigurationSchemes = val;
                break;
            case "college":
                this.college = val;
                break;
            case "createdBy":
                this.createdBy = val;
                break;
            case "enrolFieldConfigurationSchemes":
                this.enrolFieldConfigurationSchemes = val;
                break;
            case "fieldConfigurationLinks":
                this.fieldConfigurationLinks = val;
                break;
            case "fieldHeadings":
                this.fieldHeadings = val;
                break;
            case "fields":
                this.fields = val;
                break;
            case "waitingListFieldConfigurationSchemes":
                this.waitingListFieldConfigurationSchemes = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.angelId);
        out.writeObject(this.created);
        out.writeObject(this.intType);
        out.writeObject(this.modified);
        out.writeObject(this.name);
        out.writeObject(this.applicationFieldConfigurationSchemes);
        out.writeObject(this.college);
        out.writeObject(this.createdBy);
        out.writeObject(this.enrolFieldConfigurationSchemes);
        out.writeObject(this.fieldConfigurationLinks);
        out.writeObject(this.fieldHeadings);
        out.writeObject(this.fields);
        out.writeObject(this.waitingListFieldConfigurationSchemes);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.angelId = (Long)in.readObject();
        this.created = (Date)in.readObject();
        this.intType = (Integer)in.readObject();
        this.modified = (Date)in.readObject();
        this.name = (String)in.readObject();
        this.applicationFieldConfigurationSchemes = in.readObject();
        this.college = in.readObject();
        this.createdBy = in.readObject();
        this.enrolFieldConfigurationSchemes = in.readObject();
        this.fieldConfigurationLinks = in.readObject();
        this.fieldHeadings = in.readObject();
        this.fields = in.readObject();
        this.waitingListFieldConfigurationSchemes = in.readObject();
    }

}
