package ish.oncourse.model.auto;

import java.util.Date;

import org.apache.cayenne.exp.Property;

import ish.common.types.MessageStatus;
import ish.common.types.MessageType;
import ish.oncourse.model.College;
import ish.oncourse.model.Contact;
import ish.oncourse.model.Message;

/**
 * Class _MessagePerson was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MessagePerson extends WillowCayenneObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String DESTINATION_ADDRESS_PROPERTY = "destinationAddress";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NUMBER_OF_ATTEMPTS_PROPERTY = "numberOfAttempts";
    public static final String RESPONSE_PROPERTY = "response";
    public static final String STATUS_PROPERTY = "status";
    public static final String TIME_OF_DELIVERY_PROPERTY = "timeOfDelivery";
    public static final String TYPE_PROPERTY = "type";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String CONTACT_PROPERTY = "contact";
    public static final String MESSAGE_PROPERTY = "message";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = Property.create("angelId", Long.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<String> DESTINATION_ADDRESS = Property.create("destinationAddress", String.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<Integer> NUMBER_OF_ATTEMPTS = Property.create("numberOfAttempts", Integer.class);
    public static final Property<String> RESPONSE = Property.create("response", String.class);
    public static final Property<MessageStatus> STATUS = Property.create("status", MessageStatus.class);
    public static final Property<Date> TIME_OF_DELIVERY = Property.create("timeOfDelivery", Date.class);
    public static final Property<MessageType> TYPE = Property.create("type", MessageType.class);
    public static final Property<College> COLLEGE = Property.create("college", College.class);
    public static final Property<Contact> CONTACT = Property.create("contact", Contact.class);
    public static final Property<Message> MESSAGE = Property.create("message", Message.class);

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setDestinationAddress(String destinationAddress) {
        writeProperty("destinationAddress", destinationAddress);
    }
    public String getDestinationAddress() {
        return (String)readProperty("destinationAddress");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setNumberOfAttempts(Integer numberOfAttempts) {
        writeProperty("numberOfAttempts", numberOfAttempts);
    }
    public Integer getNumberOfAttempts() {
        return (Integer)readProperty("numberOfAttempts");
    }

    public void setResponse(String response) {
        writeProperty("response", response);
    }
    public String getResponse() {
        return (String)readProperty("response");
    }

    public void setStatus(MessageStatus status) {
        writeProperty("status", status);
    }
    public MessageStatus getStatus() {
        return (MessageStatus)readProperty("status");
    }

    public void setTimeOfDelivery(Date timeOfDelivery) {
        writeProperty("timeOfDelivery", timeOfDelivery);
    }
    public Date getTimeOfDelivery() {
        return (Date)readProperty("timeOfDelivery");
    }

    public void setType(MessageType type) {
        writeProperty("type", type);
    }
    public MessageType getType() {
        return (MessageType)readProperty("type");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void setContact(Contact contact) {
        setToOneTarget("contact", contact, true);
    }

    public Contact getContact() {
        return (Contact)readProperty("contact");
    }


    public void setMessage(Message message) {
        setToOneTarget("message", message, true);
    }

    public Message getMessage() {
        return (Message)readProperty("message");
    }


}
