package ish.oncourse.model.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.exp.Property;

import ish.oncourse.model.AssessmentClassModule;
import ish.oncourse.model.College;
import ish.oncourse.model.CourseModule;
import ish.oncourse.model.SessionModule;

/**
 * Class _Module was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Module extends WillowCayenneObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String CREDIT_POINTS_PROPERTY = "creditPoints";
    public static final String DISCIPLINE_CODE_PROPERTY = "disciplineCode";
    public static final String EXPIRY_DAYS_PROPERTY = "expiryDays";
    public static final String FIELD_OF_EDUCATION_PROPERTY = "fieldOfEducation";
    public static final String IS_MODULE_PROPERTY = "isModule";
    public static final String ISH_VERSION_PROPERTY = "ishVersion";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NATIONAL_CODE_PROPERTY = "nationalCode";
    public static final String SPECIALIZATION_PROPERTY = "specialization";
    public static final String TITLE_PROPERTY = "title";
    public static final String TRAINING_PACKAGE_ID_PROPERTY = "trainingPackageId";
    public static final String ASSESSMENT_CLASS_MODULES_PROPERTY = "assessmentClassModules";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String MODULE_COURSES_PROPERTY = "moduleCourses";
    public static final String SESSION_MODULES_PROPERTY = "sessionModules";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = Property.create("angelId", Long.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<BigDecimal> CREDIT_POINTS = Property.create("creditPoints", BigDecimal.class);
    public static final Property<String> DISCIPLINE_CODE = Property.create("disciplineCode", String.class);
    public static final Property<Integer> EXPIRY_DAYS = Property.create("expiryDays", Integer.class);
    public static final Property<String> FIELD_OF_EDUCATION = Property.create("fieldOfEducation", String.class);
    public static final Property<Byte> IS_MODULE = Property.create("isModule", Byte.class);
    public static final Property<Long> ISH_VERSION = Property.create("ishVersion", Long.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<String> NATIONAL_CODE = Property.create("nationalCode", String.class);
    public static final Property<String> SPECIALIZATION = Property.create("specialization", String.class);
    public static final Property<String> TITLE = Property.create("title", String.class);
    public static final Property<Long> TRAINING_PACKAGE_ID = Property.create("trainingPackageId", Long.class);
    public static final Property<List<AssessmentClassModule>> ASSESSMENT_CLASS_MODULES = Property.create("assessmentClassModules", List.class);
    public static final Property<College> COLLEGE = Property.create("college", College.class);
    public static final Property<List<CourseModule>> MODULE_COURSES = Property.create("moduleCourses", List.class);
    public static final Property<List<SessionModule>> SESSION_MODULES = Property.create("sessionModules", List.class);

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setCreditPoints(BigDecimal creditPoints) {
        writeProperty("creditPoints", creditPoints);
    }
    public BigDecimal getCreditPoints() {
        return (BigDecimal)readProperty("creditPoints");
    }

    public void setDisciplineCode(String disciplineCode) {
        writeProperty("disciplineCode", disciplineCode);
    }
    public String getDisciplineCode() {
        return (String)readProperty("disciplineCode");
    }

    public void setExpiryDays(Integer expiryDays) {
        writeProperty("expiryDays", expiryDays);
    }
    public Integer getExpiryDays() {
        return (Integer)readProperty("expiryDays");
    }

    public void setFieldOfEducation(String fieldOfEducation) {
        writeProperty("fieldOfEducation", fieldOfEducation);
    }
    public String getFieldOfEducation() {
        return (String)readProperty("fieldOfEducation");
    }

    public void setIsModule(Byte isModule) {
        writeProperty("isModule", isModule);
    }
    public Byte getIsModule() {
        return (Byte)readProperty("isModule");
    }

    public void setIshVersion(Long ishVersion) {
        writeProperty("ishVersion", ishVersion);
    }
    public Long getIshVersion() {
        return (Long)readProperty("ishVersion");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setNationalCode(String nationalCode) {
        writeProperty("nationalCode", nationalCode);
    }
    public String getNationalCode() {
        return (String)readProperty("nationalCode");
    }

    public void setSpecialization(String specialization) {
        writeProperty("specialization", specialization);
    }
    public String getSpecialization() {
        return (String)readProperty("specialization");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

    public void setTrainingPackageId(Long trainingPackageId) {
        writeProperty("trainingPackageId", trainingPackageId);
    }
    public Long getTrainingPackageId() {
        return (Long)readProperty("trainingPackageId");
    }

    public void addToAssessmentClassModules(AssessmentClassModule obj) {
        addToManyTarget("assessmentClassModules", obj, true);
    }
    public void removeFromAssessmentClassModules(AssessmentClassModule obj) {
        removeToManyTarget("assessmentClassModules", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AssessmentClassModule> getAssessmentClassModules() {
        return (List<AssessmentClassModule>)readProperty("assessmentClassModules");
    }


    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void addToModuleCourses(CourseModule obj) {
        addToManyTarget("moduleCourses", obj, true);
    }
    public void removeFromModuleCourses(CourseModule obj) {
        removeToManyTarget("moduleCourses", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CourseModule> getModuleCourses() {
        return (List<CourseModule>)readProperty("moduleCourses");
    }


    public void addToSessionModules(SessionModule obj) {
        addToManyTarget("sessionModules", obj, true);
    }
    public void removeFromSessionModules(SessionModule obj) {
        removeToManyTarget("sessionModules", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SessionModule> getSessionModules() {
        return (List<SessionModule>)readProperty("sessionModules");
    }


    protected abstract void onPreUpdate();

    protected abstract void onPrePersist();

}
