package ish.oncourse.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import ish.oncourse.model.College;

/**
 * Class _NotificationTemplate was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NotificationTemplate extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ALLOW_WEBOBJECTS_TAGS_PROPERTY = "allowWebobjectsTags";
    public static final String ALLOWED_IN_TEXTILE_TAGS_PROPERTY = "allowedInTextileTags";
    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String MESSAGE_PROPERTY = "message";
    public static final String MIME_TYPE_PROPERTY = "mimeType";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String SUBJECT_PROPERTY = "subject";
    public static final String COLLEGE_PROPERTY = "college";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Boolean> ALLOW_WEBOBJECTS_TAGS = Property.create("allowWebobjectsTags", Boolean.class);
    public static final Property<Boolean> ALLOWED_IN_TEXTILE_TAGS = Property.create("allowedInTextileTags", Boolean.class);
    public static final Property<Long> ANGEL_ID = Property.create("angelId", Long.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<String> MESSAGE = Property.create("message", String.class);
    public static final Property<String> MIME_TYPE = Property.create("mimeType", String.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<String> SUBJECT = Property.create("subject", String.class);
    public static final Property<College> COLLEGE = Property.create("college", College.class);

    public void setAllowWebobjectsTags(Boolean allowWebobjectsTags) {
        writeProperty("allowWebobjectsTags", allowWebobjectsTags);
    }
    public Boolean getAllowWebobjectsTags() {
        return (Boolean)readProperty("allowWebobjectsTags");
    }

    public void setAllowedInTextileTags(Boolean allowedInTextileTags) {
        writeProperty("allowedInTextileTags", allowedInTextileTags);
    }
    public Boolean getAllowedInTextileTags() {
        return (Boolean)readProperty("allowedInTextileTags");
    }

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setMessage(String message) {
        writeProperty("message", message);
    }
    public String getMessage() {
        return (String)readProperty("message");
    }

    public void setMimeType(String mimeType) {
        writeProperty("mimeType", mimeType);
    }
    public String getMimeType() {
        return (String)readProperty("mimeType");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setSubject(String subject) {
        writeProperty("subject", subject);
    }
    public String getSubject() {
        return (String)readProperty("subject");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


}
