package ish.oncourse.model.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Date;

import org.apache.cayenne.exp.Property;

import ish.oncourse.model.College;

/**
 * Class _NotificationTemplate was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NotificationTemplate extends WillowCayenneObject {

    private static final long serialVersionUID = 1L; 

    public static final String ALLOW_WEBOBJECTS_TAGS_PROPERTY = "allowWebobjectsTags";
    public static final String ALLOWED_IN_TEXTILE_TAGS_PROPERTY = "allowedInTextileTags";
    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String MESSAGE_PROPERTY = "message";
    public static final String MIME_TYPE_PROPERTY = "mimeType";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String SUBJECT_PROPERTY = "subject";
    public static final String COLLEGE_PROPERTY = "college";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Boolean> ALLOW_WEBOBJECTS_TAGS = Property.create("allowWebobjectsTags", Boolean.class);
    public static final Property<Boolean> ALLOWED_IN_TEXTILE_TAGS = Property.create("allowedInTextileTags", Boolean.class);
    public static final Property<Long> ANGEL_ID = Property.create("angelId", Long.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<String> MESSAGE = Property.create("message", String.class);
    public static final Property<String> MIME_TYPE = Property.create("mimeType", String.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<String> SUBJECT = Property.create("subject", String.class);
    public static final Property<College> COLLEGE = Property.create("college", College.class);

    protected Boolean allowWebobjectsTags;
    protected Boolean allowedInTextileTags;
    protected Long angelId;
    protected Date created;
    protected String message;
    protected String mimeType;
    protected Date modified;
    protected String name;
    protected String subject;

    protected Object college;

    public void setAllowWebobjectsTags(Boolean allowWebobjectsTags) {
        beforePropertyWrite("allowWebobjectsTags", this.allowWebobjectsTags, allowWebobjectsTags);
        this.allowWebobjectsTags = allowWebobjectsTags;
    }

    public Boolean getAllowWebobjectsTags() {
        beforePropertyRead("allowWebobjectsTags");
        return this.allowWebobjectsTags;
    }

    public void setAllowedInTextileTags(Boolean allowedInTextileTags) {
        beforePropertyWrite("allowedInTextileTags", this.allowedInTextileTags, allowedInTextileTags);
        this.allowedInTextileTags = allowedInTextileTags;
    }

    public Boolean getAllowedInTextileTags() {
        beforePropertyRead("allowedInTextileTags");
        return this.allowedInTextileTags;
    }

    public void setAngelId(Long angelId) {
        beforePropertyWrite("angelId", this.angelId, angelId);
        this.angelId = angelId;
    }

    public Long getAngelId() {
        beforePropertyRead("angelId");
        return this.angelId;
    }

    public void setCreated(Date created) {
        beforePropertyWrite("created", this.created, created);
        this.created = created;
    }

    public Date getCreated() {
        beforePropertyRead("created");
        return this.created;
    }

    public void setMessage(String message) {
        beforePropertyWrite("message", this.message, message);
        this.message = message;
    }

    public String getMessage() {
        beforePropertyRead("message");
        return this.message;
    }

    public void setMimeType(String mimeType) {
        beforePropertyWrite("mimeType", this.mimeType, mimeType);
        this.mimeType = mimeType;
    }

    public String getMimeType() {
        beforePropertyRead("mimeType");
        return this.mimeType;
    }

    public void setModified(Date modified) {
        beforePropertyWrite("modified", this.modified, modified);
        this.modified = modified;
    }

    public Date getModified() {
        beforePropertyRead("modified");
        return this.modified;
    }

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String getName() {
        beforePropertyRead("name");
        return this.name;
    }

    public void setSubject(String subject) {
        beforePropertyWrite("subject", this.subject, subject);
        this.subject = subject;
    }

    public String getSubject() {
        beforePropertyRead("subject");
        return this.subject;
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "allowWebobjectsTags":
                return this.allowWebobjectsTags;
            case "allowedInTextileTags":
                return this.allowedInTextileTags;
            case "angelId":
                return this.angelId;
            case "created":
                return this.created;
            case "message":
                return this.message;
            case "mimeType":
                return this.mimeType;
            case "modified":
                return this.modified;
            case "name":
                return this.name;
            case "subject":
                return this.subject;
            case "college":
                return this.college;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "allowWebobjectsTags":
                this.allowWebobjectsTags = (Boolean)val;
                break;
            case "allowedInTextileTags":
                this.allowedInTextileTags = (Boolean)val;
                break;
            case "angelId":
                this.angelId = (Long)val;
                break;
            case "created":
                this.created = (Date)val;
                break;
            case "message":
                this.message = (String)val;
                break;
            case "mimeType":
                this.mimeType = (String)val;
                break;
            case "modified":
                this.modified = (Date)val;
                break;
            case "name":
                this.name = (String)val;
                break;
            case "subject":
                this.subject = (String)val;
                break;
            case "college":
                this.college = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.allowWebobjectsTags);
        out.writeObject(this.allowedInTextileTags);
        out.writeObject(this.angelId);
        out.writeObject(this.created);
        out.writeObject(this.message);
        out.writeObject(this.mimeType);
        out.writeObject(this.modified);
        out.writeObject(this.name);
        out.writeObject(this.subject);
        out.writeObject(this.college);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.allowWebobjectsTags = (Boolean)in.readObject();
        this.allowedInTextileTags = (Boolean)in.readObject();
        this.angelId = (Long)in.readObject();
        this.created = (Date)in.readObject();
        this.message = (String)in.readObject();
        this.mimeType = (String)in.readObject();
        this.modified = (Date)in.readObject();
        this.name = (String)in.readObject();
        this.subject = (String)in.readObject();
        this.college = in.readObject();
    }

}
