package ish.oncourse.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import ish.math.Money;
import ish.oncourse.model.College;
import ish.oncourse.model.Invoice;
import ish.oncourse.model.PaymentIn;

/**
 * Class _PaymentInLine was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PaymentInLine extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String AMOUNT_PROPERTY = "amount";
    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String INVOICE_PROPERTY = "invoice";
    public static final String PAYMENT_IN_PROPERTY = "paymentIn";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Money> AMOUNT = Property.create("amount", Money.class);
    public static final Property<Long> ANGEL_ID = Property.create("angelId", Long.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<College> COLLEGE = Property.create("college", College.class);
    public static final Property<Invoice> INVOICE = Property.create("invoice", Invoice.class);
    public static final Property<PaymentIn> PAYMENT_IN = Property.create("paymentIn", PaymentIn.class);

    public void setAmount(Money amount) {
        writeProperty("amount", amount);
    }
    public Money getAmount() {
        return (Money)readProperty("amount");
    }

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void setInvoice(Invoice invoice) {
        setToOneTarget("invoice", invoice, true);
    }

    public Invoice getInvoice() {
        return (Invoice)readProperty("invoice");
    }


    public void setPaymentIn(PaymentIn paymentIn) {
        setToOneTarget("paymentIn", paymentIn, true);
    }

    public PaymentIn getPaymentIn() {
        return (PaymentIn)readProperty("paymentIn");
    }


    protected abstract void onPostAdd();

    protected abstract void onPreUpdate();

    protected abstract void onPrePersist();

}
