package ish.oncourse.model.auto;

import java.util.Date;

import org.apache.cayenne.exp.Property;

import ish.oncourse.model.PaymentIn;

/**
 * Class _PaymentTransaction was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PaymentTransaction extends WillowCayenneObject {

    private static final long serialVersionUID = 1L; 

    public static final String CREATED_PROPERTY = "created";
    public static final String IS_FINALISED_PROPERTY = "isFinalised";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String RESPONSE_PROPERTY = "response";
    public static final String SOAP_RESPONSE_PROPERTY = "soapResponse";
    public static final String TXN_REFERENCE_PROPERTY = "txnReference";
    public static final String PAYMENT_PROPERTY = "payment";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<Boolean> IS_FINALISED = Property.create("isFinalised", Boolean.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<String> RESPONSE = Property.create("response", String.class);
    public static final Property<String> SOAP_RESPONSE = Property.create("soapResponse", String.class);
    public static final Property<String> TXN_REFERENCE = Property.create("txnReference", String.class);
    public static final Property<PaymentIn> PAYMENT = Property.create("payment", PaymentIn.class);

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setIsFinalised(Boolean isFinalised) {
        writeProperty("isFinalised", isFinalised);
    }
    public Boolean getIsFinalised() {
        return (Boolean)readProperty("isFinalised");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setResponse(String response) {
        writeProperty("response", response);
    }
    public String getResponse() {
        return (String)readProperty("response");
    }

    public void setSoapResponse(String soapResponse) {
        writeProperty("soapResponse", soapResponse);
    }
    public String getSoapResponse() {
        return (String)readProperty("soapResponse");
    }

    public void setTxnReference(String txnReference) {
        writeProperty("txnReference", txnReference);
    }
    public String getTxnReference() {
        return (String)readProperty("txnReference");
    }

    public void setPayment(PaymentIn payment) {
        setToOneTarget("payment", payment, true);
    }

    public PaymentIn getPayment() {
        return (PaymentIn)readProperty("payment");
    }


    protected abstract void onPreUpdate();

    protected abstract void onPrePersist();

}
