package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.exp.Property;

import ish.oncourse.model.College;
import ish.oncourse.model.Outcome;
import ish.oncourse.model.Qualification;
import ish.oncourse.model.Student;

/**
 * Class _PriorLearning was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PriorLearning extends WillowCayenneObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String EXTERNAL_REF_PROPERTY = "externalRef";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NOTES_PROPERTY = "notes";
    public static final String OUTCOME_ID_TRAINING_ORG_PROPERTY = "outcomeIdTrainingOrg";
    public static final String TITLE_PROPERTY = "title";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String OUTCOMES_PROPERTY = "outcomes";
    public static final String QUALIFICATION_PROPERTY = "qualification";
    public static final String STUDENT_PROPERTY = "student";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = Property.create("angelId", Long.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<String> EXTERNAL_REF = Property.create("externalRef", String.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<String> NOTES = Property.create("notes", String.class);
    public static final Property<String> OUTCOME_ID_TRAINING_ORG = Property.create("outcomeIdTrainingOrg", String.class);
    public static final Property<String> TITLE = Property.create("title", String.class);
    public static final Property<College> COLLEGE = Property.create("college", College.class);
    public static final Property<List<Outcome>> OUTCOMES = Property.create("outcomes", List.class);
    public static final Property<Qualification> QUALIFICATION = Property.create("qualification", Qualification.class);
    public static final Property<Student> STUDENT = Property.create("student", Student.class);

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setExternalRef(String externalRef) {
        writeProperty("externalRef", externalRef);
    }
    public String getExternalRef() {
        return (String)readProperty("externalRef");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setNotes(String notes) {
        writeProperty("notes", notes);
    }
    public String getNotes() {
        return (String)readProperty("notes");
    }

    public void setOutcomeIdTrainingOrg(String outcomeIdTrainingOrg) {
        writeProperty("outcomeIdTrainingOrg", outcomeIdTrainingOrg);
    }
    public String getOutcomeIdTrainingOrg() {
        return (String)readProperty("outcomeIdTrainingOrg");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void addToOutcomes(Outcome obj) {
        addToManyTarget("outcomes", obj, true);
    }
    public void removeFromOutcomes(Outcome obj) {
        removeToManyTarget("outcomes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Outcome> getOutcomes() {
        return (List<Outcome>)readProperty("outcomes");
    }


    public void setQualification(Qualification qualification) {
        setToOneTarget("qualification", qualification, true);
    }

    public Qualification getQualification() {
        return (Qualification)readProperty("qualification");
    }


    public void setStudent(Student student) {
        setToOneTarget("student", student, true);
    }

    public Student getStudent() {
        return (Student)readProperty("student");
    }


}
