package ish.oncourse.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import ish.common.types.EntityEvent;
import ish.common.types.SystemEventType;
import ish.common.types.TriggerType;
import ish.oncourse.model.College;

/**
 * Class _Script was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Script extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String ENABLED_PROPERTY = "enabled";
    public static final String ENTITY_CLASS_PROPERTY = "entityClass";
    public static final String ENTITY_EVENT_TYPE_PROPERTY = "entityEventType";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String RESULT_PROPERTY = "result";
    public static final String SCHEDULE_PROPERTY = "schedule";
    public static final String SCRIPT_PROPERTY = "script";
    public static final String SYSTEM_EVENT_TYPE_PROPERTY = "systemEventType";
    public static final String TRIGGER_TYPE_PROPERTY = "triggerType";
    public static final String COLLEGE_PROPERTY = "college";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = Property.create("angelId", Long.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<String> DESCRIPTION = Property.create("description", String.class);
    public static final Property<Boolean> ENABLED = Property.create("enabled", Boolean.class);
    public static final Property<String> ENTITY_CLASS = Property.create("entityClass", String.class);
    public static final Property<EntityEvent> ENTITY_EVENT_TYPE = Property.create("entityEventType", EntityEvent.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<String> RESULT = Property.create("result", String.class);
    public static final Property<String> SCHEDULE = Property.create("schedule", String.class);
    public static final Property<String> SCRIPT = Property.create("script", String.class);
    public static final Property<SystemEventType> SYSTEM_EVENT_TYPE = Property.create("systemEventType", SystemEventType.class);
    public static final Property<TriggerType> TRIGGER_TYPE = Property.create("triggerType", TriggerType.class);
    public static final Property<College> COLLEGE = Property.create("college", College.class);

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setEnabled(Boolean enabled) {
        writeProperty("enabled", enabled);
    }
    public Boolean getEnabled() {
        return (Boolean)readProperty("enabled");
    }

    public void setEntityClass(String entityClass) {
        writeProperty("entityClass", entityClass);
    }
    public String getEntityClass() {
        return (String)readProperty("entityClass");
    }

    public void setEntityEventType(EntityEvent entityEventType) {
        writeProperty("entityEventType", entityEventType);
    }
    public EntityEvent getEntityEventType() {
        return (EntityEvent)readProperty("entityEventType");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setResult(String result) {
        writeProperty("result", result);
    }
    public String getResult() {
        return (String)readProperty("result");
    }

    public void setSchedule(String schedule) {
        writeProperty("schedule", schedule);
    }
    public String getSchedule() {
        return (String)readProperty("schedule");
    }

    public void setScript(String script) {
        writeProperty("script", script);
    }
    public String getScript() {
        return (String)readProperty("script");
    }

    public void setSystemEventType(SystemEventType systemEventType) {
        writeProperty("systemEventType", systemEventType);
    }
    public SystemEventType getSystemEventType() {
        return (SystemEventType)readProperty("systemEventType");
    }

    public void setTriggerType(TriggerType triggerType) {
        writeProperty("triggerType", triggerType);
    }
    public TriggerType getTriggerType() {
        return (TriggerType)readProperty("triggerType");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


}
