package ish.oncourse.model.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.exp.Property;

import ish.common.types.DeliverySchedule;
import ish.oncourse.model.FieldConfiguration;

/**
 * Class _SurveyFieldConfiguration was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SurveyFieldConfiguration extends FieldConfiguration {

    private static final long serialVersionUID = 1L; 

    public static final String DELIVERY_SCHEDULE_PROPERTY = "deliverySchedule";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<DeliverySchedule> DELIVERY_SCHEDULE = Property.create("deliverySchedule", DeliverySchedule.class);

    protected DeliverySchedule deliverySchedule;


    public void setDeliverySchedule(DeliverySchedule deliverySchedule) {
        beforePropertyWrite("deliverySchedule", this.deliverySchedule, deliverySchedule);
        this.deliverySchedule = deliverySchedule;
    }

    public DeliverySchedule getDeliverySchedule() {
        beforePropertyRead("deliverySchedule");
        return this.deliverySchedule;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "deliverySchedule":
                return this.deliverySchedule;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "deliverySchedule":
                this.deliverySchedule = (DeliverySchedule)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.deliverySchedule);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.deliverySchedule = (DeliverySchedule)in.readObject();
    }

}
