package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import ish.common.types.DeliverySchedule;
import ish.common.types.SurveyTypeSource;
import ish.oncourse.model.College;
import ish.oncourse.model.Survey;

/**
 * Class _SurveyType was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SurveyType extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String DELIVERY_SCHEDULE_PROPERTY = "deliverySchedule";
    public static final String INSTRUCTION_PROPERTY = "instruction";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String SOURCE_PROPERTY = "source";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String SURVEYS_PROPERTY = "surveys";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = Property.create("angelId", Long.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<DeliverySchedule> DELIVERY_SCHEDULE = Property.create("deliverySchedule", DeliverySchedule.class);
    public static final Property<String> INSTRUCTION = Property.create("instruction", String.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<SurveyTypeSource> SOURCE = Property.create("source", SurveyTypeSource.class);
    public static final Property<College> COLLEGE = Property.create("college", College.class);
    public static final Property<List<Survey>> SURVEYS = Property.create("surveys", List.class);

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setDeliverySchedule(DeliverySchedule deliverySchedule) {
        writeProperty("deliverySchedule", deliverySchedule);
    }
    public DeliverySchedule getDeliverySchedule() {
        return (DeliverySchedule)readProperty("deliverySchedule");
    }

    public void setInstruction(String instruction) {
        writeProperty("instruction", instruction);
    }
    public String getInstruction() {
        return (String)readProperty("instruction");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setSource(SurveyTypeSource source) {
        writeProperty("source", source);
    }
    public SurveyTypeSource getSource() {
        return (SurveyTypeSource)readProperty("source");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void addToSurveys(Survey obj) {
        addToManyTarget("surveys", obj, true);
    }
    public void removeFromSurveys(Survey obj) {
        removeToManyTarget("surveys", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Survey> getSurveys() {
        return (List<Survey>)readProperty("surveys");
    }


}
