package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import ish.oncourse.model.AssessmentClassTutor;
import ish.oncourse.model.Attendance;
import ish.oncourse.model.College;
import ish.oncourse.model.Contact;
import ish.oncourse.model.Session;
import ish.oncourse.model.SessionTutor;
import ish.oncourse.model.TutorRole;

/**
 * Class _Tutor was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Tutor extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String FINISH_DATE_PROPERTY = "finishDate";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String RESUME_PROPERTY = "resume";
    public static final String RESUME_TEXTILE_PROPERTY = "resumeTextile";
    public static final String START_DATE_PROPERTY = "startDate";
    public static final String ASSESSMENT_CLASS_TUTORS_PROPERTY = "assessmentClassTutors";
    public static final String ATTENDANCES_PROPERTY = "attendances";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String CONTACT_PROPERTY = "contact";
    public static final String SESSION_TUTORS_PROPERTY = "sessionTutors";
    public static final String SESSIONS_PROPERTY = "sessions";
    public static final String TUTOR_ROLES_PROPERTY = "tutorRoles";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = Property.create("angelId", Long.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<Date> FINISH_DATE = Property.create("finishDate", Date.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<String> RESUME = Property.create("resume", String.class);
    public static final Property<String> RESUME_TEXTILE = Property.create("resumeTextile", String.class);
    public static final Property<Date> START_DATE = Property.create("startDate", Date.class);
    public static final Property<List<AssessmentClassTutor>> ASSESSMENT_CLASS_TUTORS = Property.create("assessmentClassTutors", List.class);
    public static final Property<List<Attendance>> ATTENDANCES = Property.create("attendances", List.class);
    public static final Property<College> COLLEGE = Property.create("college", College.class);
    public static final Property<Contact> CONTACT = Property.create("contact", Contact.class);
    public static final Property<List<SessionTutor>> SESSION_TUTORS = Property.create("sessionTutors", List.class);
    public static final Property<List<Session>> SESSIONS = Property.create("sessions", List.class);
    public static final Property<List<TutorRole>> TUTOR_ROLES = Property.create("tutorRoles", List.class);

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setFinishDate(Date finishDate) {
        writeProperty("finishDate", finishDate);
    }
    public Date getFinishDate() {
        return (Date)readProperty("finishDate");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setResume(String resume) {
        writeProperty("resume", resume);
    }
    public String getResume() {
        return (String)readProperty("resume");
    }

    public void setResumeTextile(String resumeTextile) {
        writeProperty("resumeTextile", resumeTextile);
    }
    public String getResumeTextile() {
        return (String)readProperty("resumeTextile");
    }

    public void setStartDate(Date startDate) {
        writeProperty("startDate", startDate);
    }
    public Date getStartDate() {
        return (Date)readProperty("startDate");
    }

    public void addToAssessmentClassTutors(AssessmentClassTutor obj) {
        addToManyTarget("assessmentClassTutors", obj, true);
    }
    public void removeFromAssessmentClassTutors(AssessmentClassTutor obj) {
        removeToManyTarget("assessmentClassTutors", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AssessmentClassTutor> getAssessmentClassTutors() {
        return (List<AssessmentClassTutor>)readProperty("assessmentClassTutors");
    }


    public void addToAttendances(Attendance obj) {
        addToManyTarget("attendances", obj, true);
    }
    public void removeFromAttendances(Attendance obj) {
        removeToManyTarget("attendances", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Attendance> getAttendances() {
        return (List<Attendance>)readProperty("attendances");
    }


    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void setContact(Contact contact) {
        setToOneTarget("contact", contact, true);
    }

    public Contact getContact() {
        return (Contact)readProperty("contact");
    }


    public void addToSessionTutors(SessionTutor obj) {
        addToManyTarget("sessionTutors", obj, true);
    }
    public void removeFromSessionTutors(SessionTutor obj) {
        removeToManyTarget("sessionTutors", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SessionTutor> getSessionTutors() {
        return (List<SessionTutor>)readProperty("sessionTutors");
    }


    public void addToSessions(Session obj) {
        addToManyTarget("sessions", obj, true);
    }
    public void removeFromSessions(Session obj) {
        removeToManyTarget("sessions", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Session> getSessions() {
        return (List<Session>)readProperty("sessions");
    }


    public void addToTutorRoles(TutorRole obj) {
        addToManyTarget("tutorRoles", obj, true);
    }
    public void removeFromTutorRoles(TutorRole obj) {
        removeToManyTarget("tutorRoles", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TutorRole> getTutorRoles() {
        return (List<TutorRole>)readProperty("tutorRoles");
    }


}
