package ish.oncourse.model.auto;

import java.util.Date;

import org.apache.cayenne.exp.Property;

import ish.oncourse.model.College;
import ish.oncourse.model.CourseClass;
import ish.oncourse.model.Tutor;

/**
 * Class _TutorRole was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TutorRole extends WillowCayenneObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CONFIRMED_DATE_PROPERTY = "confirmedDate";
    public static final String CREATED_PROPERTY = "created";
    public static final String IN_PUBLICITY_PROPERTY = "inPublicity";
    public static final String IS_CONFIRMED_PROPERTY = "isConfirmed";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String COURSE_CLASS_PROPERTY = "courseClass";
    public static final String TUTOR_PROPERTY = "tutor";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = Property.create("angelId", Long.class);
    public static final Property<Date> CONFIRMED_DATE = Property.create("confirmedDate", Date.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<Boolean> IN_PUBLICITY = Property.create("inPublicity", Boolean.class);
    public static final Property<Boolean> IS_CONFIRMED = Property.create("isConfirmed", Boolean.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<College> COLLEGE = Property.create("college", College.class);
    public static final Property<CourseClass> COURSE_CLASS = Property.create("courseClass", CourseClass.class);
    public static final Property<Tutor> TUTOR = Property.create("tutor", Tutor.class);

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setConfirmedDate(Date confirmedDate) {
        writeProperty("confirmedDate", confirmedDate);
    }
    public Date getConfirmedDate() {
        return (Date)readProperty("confirmedDate");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setInPublicity(Boolean inPublicity) {
        writeProperty("inPublicity", inPublicity);
    }
    public Boolean getInPublicity() {
        return (Boolean)readProperty("inPublicity");
    }

    public void setIsConfirmed(Boolean isConfirmed) {
        writeProperty("isConfirmed", isConfirmed);
    }
    public Boolean getIsConfirmed() {
        return (Boolean)readProperty("isConfirmed");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void setCourseClass(CourseClass courseClass) {
        setToOneTarget("courseClass", courseClass, true);
    }

    public CourseClass getCourseClass() {
        return (CourseClass)readProperty("courseClass");
    }


    public void setTutor(Tutor tutor) {
        setToOneTarget("tutor", tutor, true);
    }

    public Tutor getTutor() {
        return (Tutor)readProperty("tutor");
    }


}
