package ish.oncourse.model.auto;

import java.util.Date;

import org.apache.cayenne.exp.Property;

import ish.common.types.VoucherPaymentStatus;
import ish.oncourse.model.College;
import ish.oncourse.model.InvoiceLine;
import ish.oncourse.model.PaymentIn;
import ish.oncourse.model.Voucher;

/**
 * Class _VoucherPaymentIn was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _VoucherPaymentIn extends WillowCayenneObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String ENROLMENTS_COUNT_PROPERTY = "enrolmentsCount";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String STATUS_PROPERTY = "status";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String INVOICE_LINE_PROPERTY = "invoiceLine";
    public static final String PAYMENT_PROPERTY = "payment";
    public static final String VOUCHER_PROPERTY = "voucher";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = Property.create("angelId", Long.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<Integer> ENROLMENTS_COUNT = Property.create("enrolmentsCount", Integer.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<VoucherPaymentStatus> STATUS = Property.create("status", VoucherPaymentStatus.class);
    public static final Property<College> COLLEGE = Property.create("college", College.class);
    public static final Property<InvoiceLine> INVOICE_LINE = Property.create("invoiceLine", InvoiceLine.class);
    public static final Property<PaymentIn> PAYMENT = Property.create("payment", PaymentIn.class);
    public static final Property<Voucher> VOUCHER = Property.create("voucher", Voucher.class);

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setEnrolmentsCount(Integer enrolmentsCount) {
        writeProperty("enrolmentsCount", enrolmentsCount);
    }
    public Integer getEnrolmentsCount() {
        return (Integer)readProperty("enrolmentsCount");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setStatus(VoucherPaymentStatus status) {
        writeProperty("status", status);
    }
    public VoucherPaymentStatus getStatus() {
        return (VoucherPaymentStatus)readProperty("status");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void setInvoiceLine(InvoiceLine invoiceLine) {
        setToOneTarget("invoiceLine", invoiceLine, true);
    }

    public InvoiceLine getInvoiceLine() {
        return (InvoiceLine)readProperty("invoiceLine");
    }


    public void setPayment(PaymentIn payment) {
        setToOneTarget("payment", payment, true);
    }

    public PaymentIn getPayment() {
        return (PaymentIn)readProperty("payment");
    }


    public void setVoucher(Voucher voucher) {
        setToOneTarget("voucher", voucher, true);
    }

    public Voucher getVoucher() {
        return (Voucher)readProperty("voucher");
    }


    protected abstract void onPostAdd();

}
