package ish.oncourse.model.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.exp.Property;

import ish.oncourse.model.College;
import ish.oncourse.model.Course;
import ish.oncourse.model.ExpandableCayenneDataObject;
import ish.oncourse.model.Student;
import ish.oncourse.model.WaitingListCustomField;
import ish.oncourse.model.WaitingListSite;

/**
 * Class _WaitingList was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WaitingList extends ExpandableCayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String DETAIL_PROPERTY = "detail";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String POTENTIAL_STUDENTS_PROPERTY = "potentialStudents";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String COURSE_PROPERTY = "course";
    public static final String CUSTOM_FIELDS_PROPERTY = "customFields";
    public static final String STUDENT_PROPERTY = "student";
    public static final String WAITING_LIST_SITES_PROPERTY = "waitingListSites";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = Property.create("angelId", Long.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<String> DETAIL = Property.create("detail", String.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<Integer> POTENTIAL_STUDENTS = Property.create("potentialStudents", Integer.class);
    public static final Property<College> COLLEGE = Property.create("college", College.class);
    public static final Property<Course> COURSE = Property.create("course", Course.class);
    public static final Property<List<WaitingListCustomField>> CUSTOM_FIELDS = Property.create("customFields", List.class);
    public static final Property<Student> STUDENT = Property.create("student", Student.class);
    public static final Property<List<WaitingListSite>> WAITING_LIST_SITES = Property.create("waitingListSites", List.class);

    protected Long angelId;
    protected Date created;
    protected String detail;
    protected Date modified;
    protected Integer potentialStudents;

    protected Object college;
    protected Object course;
    protected Object customFields;
    protected Object student;
    protected Object waitingListSites;

    public void setAngelId(Long angelId) {
        beforePropertyWrite("angelId", this.angelId, angelId);
        this.angelId = angelId;
    }

    public Long getAngelId() {
        beforePropertyRead("angelId");
        return this.angelId;
    }

    public void setCreated(Date created) {
        beforePropertyWrite("created", this.created, created);
        this.created = created;
    }

    public Date getCreated() {
        beforePropertyRead("created");
        return this.created;
    }

    public void setDetail(String detail) {
        beforePropertyWrite("detail", this.detail, detail);
        this.detail = detail;
    }

    public String getDetail() {
        beforePropertyRead("detail");
        return this.detail;
    }

    public void setModified(Date modified) {
        beforePropertyWrite("modified", this.modified, modified);
        this.modified = modified;
    }

    public Date getModified() {
        beforePropertyRead("modified");
        return this.modified;
    }

    public void setPotentialStudents(Integer potentialStudents) {
        beforePropertyWrite("potentialStudents", this.potentialStudents, potentialStudents);
        this.potentialStudents = potentialStudents;
    }

    public Integer getPotentialStudents() {
        beforePropertyRead("potentialStudents");
        return this.potentialStudents;
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }

    public void setCourse(Course course) {
        setToOneTarget("course", course, true);
    }

    public Course getCourse() {
        return (Course)readProperty("course");
    }

    public void addToCustomFields(WaitingListCustomField obj) {
        addToManyTarget("customFields", obj, true);
    }

    public void removeFromCustomFields(WaitingListCustomField obj) {
        removeToManyTarget("customFields", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<WaitingListCustomField> getCustomFields() {
        return (List<WaitingListCustomField>)readProperty("customFields");
    }

    public void setStudent(Student student) {
        setToOneTarget("student", student, true);
    }

    public Student getStudent() {
        return (Student)readProperty("student");
    }

    public void addToWaitingListSites(WaitingListSite obj) {
        addToManyTarget("waitingListSites", obj, true);
    }

    public void removeFromWaitingListSites(WaitingListSite obj) {
        removeToManyTarget("waitingListSites", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<WaitingListSite> getWaitingListSites() {
        return (List<WaitingListSite>)readProperty("waitingListSites");
    }

    protected abstract void onPrePersist();

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "angelId":
                return this.angelId;
            case "created":
                return this.created;
            case "detail":
                return this.detail;
            case "modified":
                return this.modified;
            case "potentialStudents":
                return this.potentialStudents;
            case "college":
                return this.college;
            case "course":
                return this.course;
            case "customFields":
                return this.customFields;
            case "student":
                return this.student;
            case "waitingListSites":
                return this.waitingListSites;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "angelId":
                this.angelId = (Long)val;
                break;
            case "created":
                this.created = (Date)val;
                break;
            case "detail":
                this.detail = (String)val;
                break;
            case "modified":
                this.modified = (Date)val;
                break;
            case "potentialStudents":
                this.potentialStudents = (Integer)val;
                break;
            case "college":
                this.college = val;
                break;
            case "course":
                this.course = val;
                break;
            case "customFields":
                this.customFields = val;
                break;
            case "student":
                this.student = val;
                break;
            case "waitingListSites":
                this.waitingListSites = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.angelId);
        out.writeObject(this.created);
        out.writeObject(this.detail);
        out.writeObject(this.modified);
        out.writeObject(this.potentialStudents);
        out.writeObject(this.college);
        out.writeObject(this.course);
        out.writeObject(this.customFields);
        out.writeObject(this.student);
        out.writeObject(this.waitingListSites);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.angelId = (Long)in.readObject();
        this.created = (Date)in.readObject();
        this.detail = (String)in.readObject();
        this.modified = (Date)in.readObject();
        this.potentialStudents = (Integer)in.readObject();
        this.college = in.readObject();
        this.course = in.readObject();
        this.customFields = in.readObject();
        this.student = in.readObject();
        this.waitingListSites = in.readObject();
    }

}
