package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.exp.Property;

import ish.oncourse.model.College;
import ish.oncourse.model.Course;
import ish.oncourse.model.ExpandableCayenneDataObject;
import ish.oncourse.model.Student;
import ish.oncourse.model.WaitingListCustomField;
import ish.oncourse.model.WaitingListSite;

/**
 * Class _WaitingList was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WaitingList extends ExpandableCayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CREATED_PROPERTY = "created";
    public static final String DETAIL_PROPERTY = "detail";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String POTENTIAL_STUDENTS_PROPERTY = "potentialStudents";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String COURSE_PROPERTY = "course";
    public static final String CUSTOM_FIELDS_PROPERTY = "customFields";
    public static final String STUDENT_PROPERTY = "student";
    public static final String WAITING_LIST_SITES_PROPERTY = "waitingListSites";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ANGEL_ID = Property.create("angelId", Long.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<String> DETAIL = Property.create("detail", String.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<Integer> POTENTIAL_STUDENTS = Property.create("potentialStudents", Integer.class);
    public static final Property<College> COLLEGE = Property.create("college", College.class);
    public static final Property<Course> COURSE = Property.create("course", Course.class);
    public static final Property<List<WaitingListCustomField>> CUSTOM_FIELDS = Property.create("customFields", List.class);
    public static final Property<Student> STUDENT = Property.create("student", Student.class);
    public static final Property<List<WaitingListSite>> WAITING_LIST_SITES = Property.create("waitingListSites", List.class);

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setDetail(String detail) {
        writeProperty("detail", detail);
    }
    public String getDetail() {
        return (String)readProperty("detail");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setPotentialStudents(Integer potentialStudents) {
        writeProperty("potentialStudents", potentialStudents);
    }
    public Integer getPotentialStudents() {
        return (Integer)readProperty("potentialStudents");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void setCourse(Course course) {
        setToOneTarget("course", course, true);
    }

    public Course getCourse() {
        return (Course)readProperty("course");
    }


    public void addToCustomFields(WaitingListCustomField obj) {
        addToManyTarget("customFields", obj, true);
    }
    public void removeFromCustomFields(WaitingListCustomField obj) {
        removeToManyTarget("customFields", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WaitingListCustomField> getCustomFields() {
        return (List<WaitingListCustomField>)readProperty("customFields");
    }


    public void setStudent(Student student) {
        setToOneTarget("student", student, true);
    }

    public Student getStudent() {
        return (Student)readProperty("student");
    }


    public void addToWaitingListSites(WaitingListSite obj) {
        addToManyTarget("waitingListSites", obj, true);
    }
    public void removeFromWaitingListSites(WaitingListSite obj) {
        removeToManyTarget("waitingListSites", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WaitingListSite> getWaitingListSites() {
        return (List<WaitingListSite>)readProperty("waitingListSites");
    }


}
