package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.exp.Property;

import ish.oncourse.model.WebMenu;
import ish.oncourse.model.WebNode;
import ish.oncourse.model.WebSiteVersion;

/**
 * Class _WebMenu was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WebMenu extends WillowCayenneObject {

    private static final long serialVersionUID = 1L; 

    public static final String CREATED_PROPERTY = "created";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String URL_PROPERTY = "url";
    public static final String WEIGHT_PROPERTY = "weight";
    public static final String CHILDREN_MENUS_PROPERTY = "childrenMenus";
    public static final String PARENT_WEB_MENU_PROPERTY = "parentWebMenu";
    public static final String WEB_NODE_PROPERTY = "webNode";
    public static final String WEB_SITE_VERSION_PROPERTY = "webSiteVersion";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<String> URL = Property.create("url", String.class);
    public static final Property<Integer> WEIGHT = Property.create("weight", Integer.class);
    public static final Property<List<WebMenu>> CHILDREN_MENUS = Property.create("childrenMenus", List.class);
    public static final Property<WebMenu> PARENT_WEB_MENU = Property.create("parentWebMenu", WebMenu.class);
    public static final Property<WebNode> WEB_NODE = Property.create("webNode", WebNode.class);
    public static final Property<WebSiteVersion> WEB_SITE_VERSION = Property.create("webSiteVersion", WebSiteVersion.class);

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setUrl(String url) {
        writeProperty("url", url);
    }
    public String getUrl() {
        return (String)readProperty("url");
    }

    public void setWeight(Integer weight) {
        writeProperty("weight", weight);
    }
    public Integer getWeight() {
        return (Integer)readProperty("weight");
    }

    public void addToChildrenMenus(WebMenu obj) {
        addToManyTarget("childrenMenus", obj, true);
    }
    public void removeFromChildrenMenus(WebMenu obj) {
        removeToManyTarget("childrenMenus", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebMenu> getChildrenMenus() {
        return (List<WebMenu>)readProperty("childrenMenus");
    }


    public void setParentWebMenu(WebMenu parentWebMenu) {
        setToOneTarget("parentWebMenu", parentWebMenu, true);
    }

    public WebMenu getParentWebMenu() {
        return (WebMenu)readProperty("parentWebMenu");
    }


    public void setWebNode(WebNode webNode) {
        setToOneTarget("webNode", webNode, true);
    }

    public WebNode getWebNode() {
        return (WebNode)readProperty("webNode");
    }


    public void setWebSiteVersion(WebSiteVersion webSiteVersion) {
        setToOneTarget("webSiteVersion", webSiteVersion, true);
    }

    public WebSiteVersion getWebSiteVersion() {
        return (WebSiteVersion)readProperty("webSiteVersion");
    }


    protected abstract void onPostAdd();

}
