package ish.oncourse.model.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import ish.oncourse.model.RegionKey;
import ish.oncourse.model.WebContent;
import ish.oncourse.model.WebNode;
import ish.oncourse.model.WebNodeType;

/**
 * Class _WebContentVisibility was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WebContentVisibility extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String REGION_KEY_PROPERTY = "regionKey";
    public static final String WEIGHT_PROPERTY = "weight";
    public static final String WEB_CONTENT_PROPERTY = "webContent";
    public static final String WEB_NODE_PROPERTY = "webNode";
    public static final String WEB_NODE_TYPE_PROPERTY = "webNodeType";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<RegionKey> REGION_KEY = Property.create("regionKey", RegionKey.class);
    public static final Property<Integer> WEIGHT = Property.create("weight", Integer.class);
    public static final Property<WebContent> WEB_CONTENT = Property.create("webContent", WebContent.class);
    public static final Property<WebNode> WEB_NODE = Property.create("webNode", WebNode.class);
    public static final Property<WebNodeType> WEB_NODE_TYPE = Property.create("webNodeType", WebNodeType.class);

    public void setRegionKey(RegionKey regionKey) {
        writeProperty("regionKey", regionKey);
    }
    public RegionKey getRegionKey() {
        return (RegionKey)readProperty("regionKey");
    }

    public void setWeight(Integer weight) {
        writeProperty("weight", weight);
    }
    public Integer getWeight() {
        return (Integer)readProperty("weight");
    }

    public void setWebContent(WebContent webContent) {
        setToOneTarget("webContent", webContent, true);
    }

    public WebContent getWebContent() {
        return (WebContent)readProperty("webContent");
    }


    public void setWebNode(WebNode webNode) {
        setToOneTarget("webNode", webNode, true);
    }

    public WebNode getWebNode() {
        return (WebNode)readProperty("webNode");
    }


    public void setWebNodeType(WebNodeType webNodeType) {
        setToOneTarget("webNodeType", webNodeType, true);
    }

    public WebNodeType getWebNodeType() {
        return (WebNodeType)readProperty("webNodeType");
    }


    protected abstract void onPostAdd();

}
