package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import ish.oncourse.model.WebContentVisibility;
import ish.oncourse.model.WebSiteVersion;

/**
 * Class _WebContent was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WebContent extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CONTENT_PROPERTY = "content";
    public static final String CONTENT_TEXTILE_PROPERTY = "contentTextile";
    public static final String CREATED_PROPERTY = "created";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String WEB_CONTENT_VISIBILITIES_PROPERTY = "webContentVisibilities";
    public static final String WEB_SITE_VERSION_PROPERTY = "webSiteVersion";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> CONTENT = Property.create("content", String.class);
    public static final Property<String> CONTENT_TEXTILE = Property.create("contentTextile", String.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<List<WebContentVisibility>> WEB_CONTENT_VISIBILITIES = Property.create("webContentVisibilities", List.class);
    public static final Property<WebSiteVersion> WEB_SITE_VERSION = Property.create("webSiteVersion", WebSiteVersion.class);

    public void setContent(String content) {
        writeProperty("content", content);
    }
    public String getContent() {
        return (String)readProperty("content");
    }

    public void setContentTextile(String contentTextile) {
        writeProperty("contentTextile", contentTextile);
    }
    public String getContentTextile() {
        return (String)readProperty("contentTextile");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToWebContentVisibilities(WebContentVisibility obj) {
        addToManyTarget("webContentVisibilities", obj, true);
    }
    public void removeFromWebContentVisibilities(WebContentVisibility obj) {
        removeToManyTarget("webContentVisibilities", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebContentVisibility> getWebContentVisibilities() {
        return (List<WebContentVisibility>)readProperty("webContentVisibilities");
    }


    public void setWebSiteVersion(WebSiteVersion webSiteVersion) {
        setToOneTarget("webSiteVersion", webSiteVersion, true);
    }

    public WebSiteVersion getWebSiteVersion() {
        return (WebSiteVersion)readProperty("webSiteVersion");
    }


    protected abstract void onPostAdd();

    protected abstract void onPreUpdate();

}
