package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.exp.Property;

import ish.oncourse.model.College;
import ish.oncourse.model.Invoice;
import ish.oncourse.model.LicenseFee;
import ish.oncourse.model.Preference;
import ish.oncourse.model.WebHostName;
import ish.oncourse.model.WebSiteVersion;

/**
 * Class _WebSite was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WebSite extends WillowCayenneObject {

    private static final long serialVersionUID = 1L; 

    public static final String COURSES_ROOT_TAG_NAME_PROPERTY = "coursesRootTagName";
    public static final String CREATED_PROPERTY = "created";
    public static final String GOOGLE_DIRECTIONS_FROM_PROPERTY = "googleDirectionsFrom";
    public static final String GOOGLE_TAGMANAGER_ACCOUNT_PROPERTY = "googleTagmanagerAccount";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String SITE_KEY_PROPERTY = "siteKey";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String COLLEGE_DOMAINS_PROPERTY = "collegeDomains";
    public static final String INVOICES_PROPERTY = "invoices";
    public static final String LICENSE_FEES_PROPERTY = "licenseFees";
    public static final String PREFERENCES_PROPERTY = "preferences";
    public static final String VERSIONS_PROPERTY = "versions";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> COURSES_ROOT_TAG_NAME = Property.create("coursesRootTagName", String.class);
    public static final Property<Date> CREATED = Property.create("created", Date.class);
    public static final Property<String> GOOGLE_DIRECTIONS_FROM = Property.create("googleDirectionsFrom", String.class);
    public static final Property<String> GOOGLE_TAGMANAGER_ACCOUNT = Property.create("googleTagmanagerAccount", String.class);
    public static final Property<Date> MODIFIED = Property.create("modified", Date.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<String> SITE_KEY = Property.create("siteKey", String.class);
    public static final Property<College> COLLEGE = Property.create("college", College.class);
    public static final Property<List<WebHostName>> COLLEGE_DOMAINS = Property.create("collegeDomains", List.class);
    public static final Property<List<Invoice>> INVOICES = Property.create("invoices", List.class);
    public static final Property<List<LicenseFee>> LICENSE_FEES = Property.create("licenseFees", List.class);
    public static final Property<List<Preference>> PREFERENCES = Property.create("preferences", List.class);
    public static final Property<List<WebSiteVersion>> VERSIONS = Property.create("versions", List.class);

    public void setCoursesRootTagName(String coursesRootTagName) {
        writeProperty("coursesRootTagName", coursesRootTagName);
    }
    public String getCoursesRootTagName() {
        return (String)readProperty("coursesRootTagName");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setGoogleDirectionsFrom(String googleDirectionsFrom) {
        writeProperty("googleDirectionsFrom", googleDirectionsFrom);
    }
    public String getGoogleDirectionsFrom() {
        return (String)readProperty("googleDirectionsFrom");
    }

    public void setGoogleTagmanagerAccount(String googleTagmanagerAccount) {
        writeProperty("googleTagmanagerAccount", googleTagmanagerAccount);
    }
    public String getGoogleTagmanagerAccount() {
        return (String)readProperty("googleTagmanagerAccount");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setSiteKey(String siteKey) {
        writeProperty("siteKey", siteKey);
    }
    public String getSiteKey() {
        return (String)readProperty("siteKey");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void addToCollegeDomains(WebHostName obj) {
        addToManyTarget("collegeDomains", obj, true);
    }
    public void removeFromCollegeDomains(WebHostName obj) {
        removeToManyTarget("collegeDomains", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebHostName> getCollegeDomains() {
        return (List<WebHostName>)readProperty("collegeDomains");
    }


    public void addToInvoices(Invoice obj) {
        addToManyTarget("invoices", obj, true);
    }
    public void removeFromInvoices(Invoice obj) {
        removeToManyTarget("invoices", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Invoice> getInvoices() {
        return (List<Invoice>)readProperty("invoices");
    }


    public void addToLicenseFees(LicenseFee obj) {
        addToManyTarget("licenseFees", obj, true);
    }
    public void removeFromLicenseFees(LicenseFee obj) {
        removeToManyTarget("licenseFees", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<LicenseFee> getLicenseFees() {
        return (List<LicenseFee>)readProperty("licenseFees");
    }


    public void addToPreferences(Preference obj) {
        addToManyTarget("preferences", obj, true);
    }
    public void removeFromPreferences(Preference obj) {
        removeToManyTarget("preferences", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Preference> getPreferences() {
        return (List<Preference>)readProperty("preferences");
    }


    public void addToVersions(WebSiteVersion obj) {
        addToManyTarget("versions", obj, true);
    }
    public void removeFromVersions(WebSiteVersion obj) {
        removeToManyTarget("versions", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebSiteVersion> getVersions() {
        return (List<WebSiteVersion>)readProperty("versions");
    }


}
