jetty:
  context: /
  connectors:
    - type: willow
      port: 11100
      host: 0.0.0.0
  compactPath: true
cxf:
  welcomeText: 'portal REST API'
  urlPattern: '/p/*'
jdbc:
  willow:
    driverClassName: org.mariadb.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    validationInterval: 30000
    timeBetweenEvictionRunsMillis: 3000
    maxActive: 100
    maxIdle: 5
    minIdle: 2
    removeAbandonedTimeout: 300
    removeAbandoned: true
    logAbandoned: true
    jmxEnabled: true
cayenne:
  datasource: willow
  configs:
    - cayenne-oncourse.xml