
package au.gov.training.services.organisation;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-05-06T18:49:01.296+03:00
 * Generated source version: 2.6.2
 */

@WebFault(name = "ValidationFault", targetNamespace = "http://training.gov.au/services/")
public class IOrganisationServiceGetServerTimeValidationFaultFaultFaultMessage extends Exception {
    
    private au.gov.training.services.organisation.ValidationFault validationFault;

    public IOrganisationServiceGetServerTimeValidationFaultFaultFaultMessage() {
        super();
    }
    
    public IOrganisationServiceGetServerTimeValidationFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public IOrganisationServiceGetServerTimeValidationFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IOrganisationServiceGetServerTimeValidationFaultFaultFaultMessage(String message, au.gov.training.services.organisation.ValidationFault validationFault) {
        super(message);
        this.validationFault = validationFault;
    }

    public IOrganisationServiceGetServerTimeValidationFaultFaultFaultMessage(String message, au.gov.training.services.organisation.ValidationFault validationFault, Throwable cause) {
        super(message, cause);
        this.validationFault = validationFault;
    }

    public au.gov.training.services.organisation.ValidationFault getFaultInfo() {
        return this.validationFault;
    }
}
