package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.CertificateOutcome;
import ish.oncourse.model.College;
import ish.oncourse.model.Qualification;
import ish.oncourse.model.Student;

/**
 * Class _Certificate was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Certificate extends CayenneDataObject {

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String CERTIFICATE_NUMBER_PROPERTY = "certificateNumber";
    public static final String CREATED_PROPERTY = "created";
    public static final String END_DATE_PROPERTY = "endDate";
    public static final String FUNDING_SOURCE_PROPERTY = "fundingSource";
    public static final String IS_QUALIFICATION_PROPERTY = "isQualification";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String PRINTED_WHEN_PROPERTY = "printedWhen";
    public static final String PRIVATE_NOTES_PROPERTY = "privateNotes";
    public static final String PUBLIC_NOTES_PROPERTY = "publicNotes";
    public static final String QUALIFICATION_ID_PROPERTY = "qualificationId";
    public static final String REVOKED_WHEN_PROPERTY = "revokedWhen";
    public static final String STUDENT_FIRST_NAME_PROPERTY = "studentFirstName";
    public static final String STUDENT_LAST_NAME_PROPERTY = "studentLastName";
    public static final String CERTIFICATE_OUTCOMES_PROPERTY = "certificateOutcomes";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String QUALIFICATION_PROPERTY = "qualification";
    public static final String STUDENT_PROPERTY = "student";

    public static final String ID_PK_COLUMN = "id";

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCertificateNumber(Long certificateNumber) {
        writeProperty("certificateNumber", certificateNumber);
    }
    public Long getCertificateNumber() {
        return (Long)readProperty("certificateNumber");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setEndDate(Date endDate) {
        writeProperty("endDate", endDate);
    }
    public Date getEndDate() {
        return (Date)readProperty("endDate");
    }

    public void setFundingSource(Integer fundingSource) {
        writeProperty("fundingSource", fundingSource);
    }
    public Integer getFundingSource() {
        return (Integer)readProperty("fundingSource");
    }

    public void setIsQualification(Boolean isQualification) {
        writeProperty("isQualification", isQualification);
    }
    public Boolean getIsQualification() {
        return (Boolean)readProperty("isQualification");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setPrintedWhen(Date printedWhen) {
        writeProperty("printedWhen", printedWhen);
    }
    public Date getPrintedWhen() {
        return (Date)readProperty("printedWhen");
    }

    public void setPrivateNotes(String privateNotes) {
        writeProperty("privateNotes", privateNotes);
    }
    public String getPrivateNotes() {
        return (String)readProperty("privateNotes");
    }

    public void setPublicNotes(String publicNotes) {
        writeProperty("publicNotes", publicNotes);
    }
    public String getPublicNotes() {
        return (String)readProperty("publicNotes");
    }

    public void setQualificationId(Long qualificationId) {
        writeProperty("qualificationId", qualificationId);
    }
    public Long getQualificationId() {
        return (Long)readProperty("qualificationId");
    }

    public void setRevokedWhen(Date revokedWhen) {
        writeProperty("revokedWhen", revokedWhen);
    }
    public Date getRevokedWhen() {
        return (Date)readProperty("revokedWhen");
    }

    public void setStudentFirstName(String studentFirstName) {
        writeProperty("studentFirstName", studentFirstName);
    }
    public String getStudentFirstName() {
        return (String)readProperty("studentFirstName");
    }

    public void setStudentLastName(String studentLastName) {
        writeProperty("studentLastName", studentLastName);
    }
    public String getStudentLastName() {
        return (String)readProperty("studentLastName");
    }

    public void addToCertificateOutcomes(CertificateOutcome obj) {
        addToManyTarget("certificateOutcomes", obj, true);
    }
    public void removeFromCertificateOutcomes(CertificateOutcome obj) {
        removeToManyTarget("certificateOutcomes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CertificateOutcome> getCertificateOutcomes() {
        return (List<CertificateOutcome>)readProperty("certificateOutcomes");
    }


    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


    public void setQualification(Qualification qualification) {
        setToOneTarget("qualification", qualification, true);
    }

    public Qualification getQualification() {
        return (Qualification)readProperty("qualification");
    }


    public void setStudent(Student student) {
        setToOneTarget("student", student, true);
    }

    public Student getStudent() {
        return (Student)readProperty("student");
    }


}
