package ish.oncourse.model.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.College;

/**
 * Class _LicenseFee was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _LicenseFee extends CayenneDataObject {

    public static final String FEE_PROPERTY = "fee";
    public static final String FREE_TRANSACTIONS_PROPERTY = "freeTransactions";
    public static final String KEY_CODE_PROPERTY = "keyCode";
    public static final String PLAN_NAME_PROPERTY = "planName";
    public static final String VALID_UNTIL_PROPERTY = "validUntil";
    public static final String COLLEGE_PROPERTY = "college";

    public static final String ID_PK_COLUMN = "id";

    public void setFee(BigDecimal fee) {
        writeProperty("fee", fee);
    }
    public BigDecimal getFee() {
        return (BigDecimal)readProperty("fee");
    }

    public void setFreeTransactions(Integer freeTransactions) {
        writeProperty("freeTransactions", freeTransactions);
    }
    public Integer getFreeTransactions() {
        return (Integer)readProperty("freeTransactions");
    }

    public void setKeyCode(String keyCode) {
        writeProperty("keyCode", keyCode);
    }
    public String getKeyCode() {
        return (String)readProperty("keyCode");
    }

    public void setPlanName(String planName) {
        writeProperty("planName", planName);
    }
    public String getPlanName() {
        return (String)readProperty("planName");
    }

    public void setValidUntil(Date validUntil) {
        writeProperty("validUntil", validUntil);
    }
    public Date getValidUntil() {
        return (Date)readProperty("validUntil");
    }

    public void setCollege(College college) {
        setToOneTarget("college", college, true);
    }

    public College getCollege() {
        return (College)readProperty("college");
    }


}
