package ish.oncourse.model.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _PostcodeDb was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PostcodeDb extends CayenneDataObject {

    public static final String DC_PROPERTY = "dc";
    public static final String LAT_PROPERTY = "lat";
    public static final String LON_PROPERTY = "lon";
    public static final String POSTCODE_PROPERTY = "postcode";
    public static final String STATE_PROPERTY = "state";
    public static final String SUBURB_PROPERTY = "suburb";
    public static final String TYPE_PROPERTY = "type";

    public static final String POSTCODE_PK_COLUMN = "postcode";
    public static final String SUBURB_PK_COLUMN = "suburb";

    public void setDc(String dc) {
        writeProperty("dc", dc);
    }
    public String getDc() {
        return (String)readProperty("dc");
    }

    public void setLat(Double lat) {
        writeProperty("lat", lat);
    }
    public Double getLat() {
        return (Double)readProperty("lat");
    }

    public void setLon(Double lon) {
        writeProperty("lon", lon);
    }
    public Double getLon() {
        return (Double)readProperty("lon");
    }

    public void setPostcode(Integer postcode) {
        writeProperty("postcode", postcode);
    }
    public Integer getPostcode() {
        return (Integer)readProperty("postcode");
    }

    public void setState(String state) {
        writeProperty("state", state);
    }
    public String getState() {
        return (String)readProperty("state");
    }

    public void setSuburb(String suburb) {
        writeProperty("suburb", suburb);
    }
    public String getSuburb() {
        return (String)readProperty("suburb");
    }

    public void setType(String type) {
        writeProperty("type", type);
    }
    public String getType() {
        return (String)readProperty("type");
    }

}
