package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.Attendance;
import ish.oncourse.model.Contact;
import ish.oncourse.model.MessagePerson;
import ish.oncourse.model.Session;
import ish.oncourse.model.SessionTutor;
import ish.oncourse.model.TutorRole;

/**
 * Class _Tutor was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Tutor extends CayenneDataObject {

    public static final String ANGEL_ID_PROPERTY = "angelId";
    public static final String COLLEGE_ID_PROPERTY = "collegeId";
    public static final String CREATED_PROPERTY = "created";
    public static final String FINISH_DATE_PROPERTY = "finishDate";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String RESUME_PROPERTY = "resume";
    public static final String RESUME_TEXTILE_PROPERTY = "resumeTextile";
    public static final String START_DATE_PROPERTY = "startDate";
    public static final String ATTENDANCES_PROPERTY = "attendances";
    public static final String CONTACT_PROPERTY = "contact";
    public static final String MESSAGE_PEOPLE_PROPERTY = "messagePeople";
    public static final String SESSION_TUTORS_PROPERTY = "sessionTutors";
    public static final String SESSIONS_PROPERTY = "sessions";
    public static final String TUTOR_ROLES_PROPERTY = "tutorRoles";

    public static final String ID_PK_COLUMN = "id";

    public void setAngelId(Long angelId) {
        writeProperty("angelId", angelId);
    }
    public Long getAngelId() {
        return (Long)readProperty("angelId");
    }

    public void setCollegeId(Long collegeId) {
        writeProperty("collegeId", collegeId);
    }
    public Long getCollegeId() {
        return (Long)readProperty("collegeId");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setFinishDate(Date finishDate) {
        writeProperty("finishDate", finishDate);
    }
    public Date getFinishDate() {
        return (Date)readProperty("finishDate");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setResume(String resume) {
        writeProperty("resume", resume);
    }
    public String getResume() {
        return (String)readProperty("resume");
    }

    public void setResumeTextile(String resumeTextile) {
        writeProperty("resumeTextile", resumeTextile);
    }
    public String getResumeTextile() {
        return (String)readProperty("resumeTextile");
    }

    public void setStartDate(Date startDate) {
        writeProperty("startDate", startDate);
    }
    public Date getStartDate() {
        return (Date)readProperty("startDate");
    }

    public void addToAttendances(Attendance obj) {
        addToManyTarget("attendances", obj, true);
    }
    public void removeFromAttendances(Attendance obj) {
        removeToManyTarget("attendances", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Attendance> getAttendances() {
        return (List<Attendance>)readProperty("attendances");
    }


    public void setContact(Contact contact) {
        setToOneTarget("contact", contact, true);
    }

    public Contact getContact() {
        return (Contact)readProperty("contact");
    }


    public void addToMessagePeople(MessagePerson obj) {
        addToManyTarget("messagePeople", obj, true);
    }
    public void removeFromMessagePeople(MessagePerson obj) {
        removeToManyTarget("messagePeople", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MessagePerson> getMessagePeople() {
        return (List<MessagePerson>)readProperty("messagePeople");
    }


    public void addToSessionTutors(SessionTutor obj) {
        addToManyTarget("sessionTutors", obj, true);
    }
    public void removeFromSessionTutors(SessionTutor obj) {
        removeToManyTarget("sessionTutors", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SessionTutor> getSessionTutors() {
        return (List<SessionTutor>)readProperty("sessionTutors");
    }


    public void addToSessions(Session obj) {
        addToManyTarget("sessions", obj, true);
    }
    public void removeFromSessions(Session obj) {
        removeToManyTarget("sessions", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Session> getSessions() {
        return (List<Session>)readProperty("sessions");
    }


    public void addToTutorRoles(TutorRole obj) {
        addToManyTarget("tutorRoles", obj, true);
    }
    public void removeFromTutorRoles(TutorRole obj) {
        removeToManyTarget("tutorRoles", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TutorRole> getTutorRoles() {
        return (List<TutorRole>)readProperty("tutorRoles");
    }


}
