package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.WebContentVisibility;
import ish.oncourse.model.WebNode;
import ish.oncourse.model.WebSite;

/**
 * Class _WebNodeType was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WebNodeType extends CayenneDataObject {

    public static final String CREATED_PROPERTY = "created";
    public static final String ID_PROPERTY = "id";
    public static final String LAYOUT_KEY_PROPERTY = "layoutKey";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String WEB_CONTENT_VISIBILITIES_PROPERTY = "webContentVisibilities";
    public static final String WEB_NODES_PROPERTY = "webNodes";
    public static final String WEB_SITE_PROPERTY = "webSite";

    public static final String ID_PK_COLUMN = "id";

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setId(Long id) {
        writeProperty("id", id);
    }
    public Long getId() {
        return (Long)readProperty("id");
    }

    public void setLayoutKey(String layoutKey) {
        writeProperty("layoutKey", layoutKey);
    }
    public String getLayoutKey() {
        return (String)readProperty("layoutKey");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToWebContentVisibilities(WebContentVisibility obj) {
        addToManyTarget("webContentVisibilities", obj, true);
    }
    public void removeFromWebContentVisibilities(WebContentVisibility obj) {
        removeToManyTarget("webContentVisibilities", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebContentVisibility> getWebContentVisibilities() {
        return (List<WebContentVisibility>)readProperty("webContentVisibilities");
    }


    public void addToWebNodes(WebNode obj) {
        addToManyTarget("webNodes", obj, true);
    }
    public void removeFromWebNodes(WebNode obj) {
        removeToManyTarget("webNodes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebNode> getWebNodes() {
        return (List<WebNode>)readProperty("webNodes");
    }


    public void setWebSite(WebSite webSite) {
        setToOneTarget("webSite", webSite, true);
    }

    public WebSite getWebSite() {
        return (WebSite)readProperty("webSite");
    }


}
