package ish.oncourse.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ish.oncourse.model.WebContentVisibility;
import ish.oncourse.model.WebMenu;
import ish.oncourse.model.WebNodeType;
import ish.oncourse.model.WebSite;
import ish.oncourse.model.WebUrlAlias;

/**
 * Class _WebNode was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WebNode extends CayenneDataObject {

    public static final String CREATED_PROPERTY = "created";
    public static final String IS_PUBLISHED_PROPERTY = "isPublished";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String NODE_NUMBER_PROPERTY = "nodeNumber";
    public static final String DEFAULT_WEB_URLALIAS_PROPERTY = "defaultWebURLAlias";
    public static final String WEB_CONTENT_VISIBILITY_PROPERTY = "webContentVisibility";
    public static final String WEB_MENU_PROPERTY = "webMenu";
    public static final String WEB_NODE_TYPE_PROPERTY = "webNodeType";
    public static final String WEB_SITE_PROPERTY = "webSite";
    public static final String WEB_URL_ALIASES_PROPERTY = "webUrlAliases";

    public static final String ID_PK_COLUMN = "id";

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setIsPublished(Boolean isPublished) {
        writeProperty("isPublished", isPublished);
    }
    public Boolean getIsPublished() {
        return (Boolean)readProperty("isPublished");
    }

    public void setModified(Date modified) {
        writeProperty("modified", modified);
    }
    public Date getModified() {
        return (Date)readProperty("modified");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setNodeNumber(Integer nodeNumber) {
        writeProperty("nodeNumber", nodeNumber);
    }
    public Integer getNodeNumber() {
        return (Integer)readProperty("nodeNumber");
    }

    public void setDefaultWebURLAlias(WebUrlAlias defaultWebURLAlias) {
        setToOneTarget("defaultWebURLAlias", defaultWebURLAlias, true);
    }

    public WebUrlAlias getDefaultWebURLAlias() {
        return (WebUrlAlias)readProperty("defaultWebURLAlias");
    }


    public void setWebContentVisibility(WebContentVisibility webContentVisibility) {
        setToOneTarget("webContentVisibility", webContentVisibility, true);
    }

    public WebContentVisibility getWebContentVisibility() {
        return (WebContentVisibility)readProperty("webContentVisibility");
    }


    public void setWebMenu(WebMenu webMenu) {
        setToOneTarget("webMenu", webMenu, true);
    }

    public WebMenu getWebMenu() {
        return (WebMenu)readProperty("webMenu");
    }


    public void setWebNodeType(WebNodeType webNodeType) {
        setToOneTarget("webNodeType", webNodeType, true);
    }

    public WebNodeType getWebNodeType() {
        return (WebNodeType)readProperty("webNodeType");
    }


    public void setWebSite(WebSite webSite) {
        setToOneTarget("webSite", webSite, true);
    }

    public WebSite getWebSite() {
        return (WebSite)readProperty("webSite");
    }


    public void addToWebUrlAliases(WebUrlAlias obj) {
        addToManyTarget("webUrlAliases", obj, true);
    }
    public void removeFromWebUrlAliases(WebUrlAlias obj) {
        removeToManyTarget("webUrlAliases", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebUrlAlias> getWebUrlAliases() {
        return (List<WebUrlAlias>)readProperty("webUrlAliases");
    }


    protected abstract void performInitialization();

}
