package ish.oncourse.webservices.soap.v7;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2020-10-29T19:55:37.110+11:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://ref.v7.soap.webservices.oncourse.ish/", name = "ReferencePortType")
@XmlSeeAlso({ish.oncourse.webservices.v7.stubs.reference.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ReferencePortType {

    @WebMethod
    @WebResult(name = "maxVersion", targetNamespace = "", partName = "maxVersion")
    public long getMaximumVersion();

    @WebMethod
    @WebResult(name = "results", targetNamespace = "", partName = "results")
    public ish.oncourse.webservices.v7.stubs.reference.ReferenceResult getRecords(
        @WebParam(partName = "ishVersion", name = "ishVersion", targetNamespace = "")
        long ishVersion
    );
}
