jetty:
  context: /editor
  connector:
    port: 10080
    host: 127.0.0.1
jdbc:
  willow:
    url: jdbc:mysql://localhost:3306/w2test_college?autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8
    username: user
    password: pass
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    validationInterval: 30000
    timeBetweenEvictionRunsMillis: 3000
    maxActive: 100
    maxIdle: 5
    minIdle: 2
    removeAbandonedTimeout: 300
    removeAbandoned: true
    logAbandoned: true
    jmxEnabled: true
cayenne:
  datasource: willow
  configs:
    - cayenne-oncourse.xml
