name: Test version increment

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Release type
        required: true
        options: 
        - major
        - minor
        default: minor

jobs:
  increment:
    runs-on: ubuntu-latest
    steps:
      - name: Get next version
      - uses: rmeneely/git-next-version@v1
        with:
          tag_pattern: 'v[0-9]*.[0-9]*'
          increment: ${{ inputs.type }}
    
      - name: Print version
        run: |
          echo 'Current tag is: $LAST_VERSION'
          echo 'Next tag is: $NEXT_VERSION'

  
