name: Test version increment

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Release type
        required: true
        options: 
        - major
        - minor
        - patch
        default: minor

jobs:
 increment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Get next version
      uses: rmeneely/git-next-version@v1
      with:
        tag_pattern: 'v[0-9]*.[0-9]*'
        increment: ${{ inputs.type }}
        
    - name: Format version
      id: format
      uses: frabert/replace-string-action@v2
      with:
        pattern: '(v)[0-9]*.[0-9]*'
        string: $LAST_VERSION
        replace-with: ''
        
    - name: Print version
      id: display
      run: echo "Replaced is ${{ steps.format.outputs.replaced }} "  
