name: Test version increment

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Release type
        required: true
        options: 
        - major
        - minor
        - patch
        default: minor

jobs:
 increment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Get next version
      uses: rmeneely/git-next-version@v1
      with:
        tag_pattern: 'v[0-9]*.[0-9]*'
        increment: ${{ inputs.type }}
        
    - name: Print version
      id: display
      run: echo "Current is ${{ env.LAST_VERSION//v }} and next is ${{ env.NEXT_VERSION//v }}"
