name: Test version increment

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Release type
        required: true
        options: 
        - major
        - minor
        - patch
        default: minor

jobs:
 increment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Get next version
      uses: rmeneely/git-next-version@v1
      with:
        increment: ${{ inputs.type }}
        
    - name: Format version
      id: format
      uses: mad9000/actions-find-and-replace-string@5
      with:
        source: ${{ env.NEXT_VERSION }} 
        find: 'v'        
        replace: ''
        
    - name: Print version
      id: display
      run: echo "Replaced is ${{ steps.format.outputs.value }} "  
